"""AWL 字頭的英文定義與詞性 —— 由 The Academic Word List (AWL) PDF 抽出。

補完卡片時會把定義放進備註，讓你手邊有意思可參考，
但例句、搭配詞、字根、同義詞還是要自己寫 —— 那才是記得住的部分。
"""

DEFINITIONS = {
    'abandon': ('v', 'go away from (a person or thing or place) not intending to return; forsake; desert'),
    'abstract': ('adj', 'existing in thought or as an idea but not having a physical or practical existence'),
    'academy': ('n', 'school for special training'),
    'access': ('n', 'means of approaching or entering (a place); way in'),
    'accommodate': ('v', 'provide lodging or room for'),
    'accompany': ('v', 'walk or travel with (sb) as a companion or helper; escort'),
    'accumulate': ('v', 'gradually get or gather together an increasing number or quantity of get (sth) in this way'),
    'accurate': ('adj', 'free from error'),
    'achieve': ('v', 'gain or reach (sth), usu by effort, skill, courage, etc'),
    'acknowledge': ('v', 'accept the truth of admit (sth)'),
    'acquire': ('v', "gain (sth) by one's own ability, efforts or behaviour"),
    'adapt': ('v', 'sth (for sth) make sth suitable for a new use, situation, etc; modify sth'),
    'adequate': ('adj', 'satisfactory in quantity or quality; sufficient'),
    'adjacent': ('', 'having a common endpoint or border also immediately preceding or following'),
    'adjust': ('v', 'put (sth) into the correct order or position; arrange administrate v. to administer'),
    'adult': ('adj', 'grown to full size or strength'),
    'advocate': ('v', 'speak publicly in favour of (sth); recommend; support'),
    'affect': ('v', 'have an influence on (sb/sth); produce an effect on'),
    'aggregate': ('v', 'sb (fml ) be formed or bring sb into an assembled group or amount'),
    'aid': ('n', 'help albeit conj although'),
    'allocate': ('v', 'sth allot or assign sth (to sb/sth) for a special purpose'),
    'alter': ('v', 'become different; change in character, position, size, shape, etc'),
    'alternative': ('adj', 'available in place of sth else; other'),
    'ambiguous': ('adj', 'having more than one possible meaning'),
    'amend': ('v', 'correct an error in (sth); make minor improvements in; change slightly'),
    'analogy': ('n', 'partial similarity between two things that are compared'),
    'analyse': ('v', 'separate into its parts in order to study its nature or structure'),
    'annual': ('adj', 'happening every year'),
    'apparent': ('adj', 'clearly seen or understood; obvious'),
    'append': ('v', 'sth (fml ) attach or add sth (esp in writing)'),
    'appreciate': ('v', 'understand and enjoy (sth); value highly'),
    'approach': ('v', 'come near or nearer to in space or time'),
    'appropriate': ('adj', 'suitable; right and proper'),
    'approximate': ('adj', 'almost correct or exact but not completely so'),
    'arbitrary': ('adj', 'based on personal opinion or impulse, not on reason'),
    'area': ('n', 'extent or measurement of a surface'),
    'aspect': ('n', 'particular part or feature of sth being considered'),
    'assemble': ('v', 'come together; collect'),
    'assess': ('v', 'sth decide or fix the amount of sth'),
    'assign': ('v', 'sth to sb give sth to sb as a share of work to be done or of things to be used'),
    'assist': ('v', 'in/with sth; ~ (sb) in doing sth (fml ) help'),
    'assume': ('v', 'accept as true before there is proof'),
    'assure': ('v', 'tell (sb) positively or confidently'),
    'attach': ('v', 'sth fasten or join sth (to sth)'),
    'attain': ('v', 'succeed in getting (sth); achieve'),
    'attitude': ('n', 'way of thinking or behaving'),
    'attribute': ('v', 'sth to sb/sth regard sth as belonging to, caused by or produced by sb/sth'),
    'author': ('n', 'writer of a book, play, etc'),
    'authority': ('n', 'power to give orders and make others obey'),
    'automate': ('v', 'cause to operate by automation'),
    'available': ('adj', 'that can be used or obtained'),
    'aware': ('adj', 'of sb/sth; ~ that... having knowledge or realization of sb/sth'),
    'behalf': ('n', "on behalf of sb/on sb's behalf; US in behalf of sb/in sb's behalf as the representative of or spokesman for sb; in the interest of sb"),
    'benefit': ('n', 'profit; gain; future good (used esp with the vs and preps shown)'),
    'bias': ('n', 'opinion or feeling that strongly favours one side in an argument or one item in a group orseries; predisposition; prejudice'),
    'bond': ('n', 'written agreement or promise that has legal force; covenant'),
    'brief': ('adj', 'lasting only a short time; short'),
    'bulk': ('n', 'size, quantity or volume, esp when great'),
    'capable': ('adj', 'having ability; able; competent'),
    'capacity': ('n', 'ability to hold or contain sth'),
    'category': ('n', 'class or group of things in a complete system of grouping'),
    'cease': ('v', 'come or bring (sth) to an end; stop'),
    'challenge': ('n', '(to do sth) invitation or call (to sb) to take part in a game, contest, fight etc to prove who is better, stronger, more able, etc'),
    'channel': ('n', 'sunken bed of a river, stream or canal'),
    'chapter': ('n', '(usu numbered) division of a book'),
    'chart': ('n', 'detailed map used to help navigation at sea, showing coasts, rocks, the depth of the sea, etc'),
    'chemical': ('adj', 'of or relating to chemistry'),
    'circumstance': ('n', 'condition or fact connected with an event or action cite quote; commend'),
    'civil': ('adj', 'of or relating to the citizens of a country'),
    'clarify': ('v', '(cause sth to) become clear or easier to understand'),
    'classic': ('adj', 'having a high quality that is recognized and unquestioned; of lasting value and importance'),
    'clause': ('n', 'group of words that includes a subject1(4a) and a verb, forming a sentence or part of a sentence'),
    'code': ('n', '(system of) words, letters, symbols, etc that represent others, used for secret messages or for presenting or recording information briefly'),
    'coherent': ('adj', 'connected logically or consistent; easy to understand; clear'),
    'coincide': ('v', '(of events) occur at the same time or occupy the same period of time as sth else'),
    'collapse': ('v', 'fall down or in suddenly'),
    'colleague': ('n', 'person with whom one works, esp in a profession or business'),
    'commence': ('v', 'begin (sth); start'),
    'comment': ('n', 'written or spoken remark giving an opinion on, explaining or criticizing (an event, a person, a situation, etc)'),
    'commission': ('n', 'action, task or piece of work given to sb to do'),
    'commit': ('v', 'do (sth illegal, wrong or foolish)'),
    'commodity': ('n', 'thing bought in a shop and put to use, esp in the home'),
    'communicate': ('v', 'sth make sth known; convey sth'),
    'community': ('n', 'the community the people living in one place, district or country, considered as a whole'),
    'compatible': ('adj', '(of people, ideas, arguments, principles, etc) suited; that can exist together'),
    'compensate': ('v', 'for sth give (sb) sth good to balance or lessen the bad effect of damage, loss, injury,etc;'),
    'compile': ('v', 'sth (for/from sth) collect (information) and arrange it in a book, list, report, etc'),
    'complement': ('n', 'thing that goes well or suitably with sth else, or makes it complete'),
    'complex': ('adj', 'made up of (usu several) closely connected parts'),
    'component': ('n', 'any of the parts of which sth is made'),
    'compound': ('n', 'thing made up of two or more separate things combined together'),
    'comprehensive': ('adj', 'that includes everything'),
    'comprise': ('v', 'have as parts or members; be made up of'),
    'compute': ('v', 'sth calculate sth with a computer'),
    'concentrate': ('v', "(sth) (on sth/doing sth) focus (one's attention, effort, etc) exclusively and intensely on sth, not thinking about other less important things"),
    'concept': ('n', 'idea underlying sth; general notion'),
    'conclude': ('v', '(with sth) (usu fml ) come or bring (sth) to an end'),
    'concurrent': ('adj', 'existing, happening or done at the same time'),
    'confer': ('v', '(with sb) (on/about sth) have discussions (esp in order to exchange opinions or get advice)'),
    'confine': ('v', 'sb/sth keep (a person or an animal) in a restricted space'),
    'confirm': ('v', 'provide evidence for the truth or correctness of (a report, an opinion, etc); establish the truth of'),
    'conform': ('v', 'keep to or comply with (generally accepted rules, standards, etc)'),
    'consent': ('v', 'give agreement or permission'),
    'consequent': ('adj', '(fml ) following sth as a result or an effect'),
    'considerable': ('adj', 'great in amount or size'),
    'consist': ('v', '(phr v) consist of sth be composed or made up of sth'),
    'constant': ('adj', 'going on all the time; happening again and again'),
    'constitute': ('v', '(fml ) make up or form (a whole); be the components of'),
    'constrain': ('v', 'make (sb) do sth by strong (moral) persuasion or by force'),
    'construct': ('v', 'build (sth); put or fit together; form'),
    'consult': ('v', 'sb/sth go to (a person, book, etc) for information, advice, etc'),
    'consume': ('v', 'use (sth) up'),
    'contact': ('n', 'state of touching (used esp with the vs shown)'),
    'contemporary': ('adj', 'of the time or period being referred to; belonging to the same time'),
    'context': ('', 'writings preceding and following passage quoted'),
    'contract': ('n', '(for sth/to do sth) legally binding agreement, usu in writing'),
    'contradict': ('v', 'say sth that conflicts with by (sb), suggesting that the person is mistaken or not telling the truth'),
    'contrary': ('adj', 'opposite in nature, tendency or direction'),
    'contrast': ('v', 'A and/with B compare so that differences are made clear'),
    'contribute': ('v', "(to/towards sth) give one's share of (money, help, advice, etc) to help a joint cause"),
    'controversy': ('n', 'public discussion or argument, often rather angry, about sth which many people disagreewith'),
    'convene': ('v', 'summon to come together; arrange (a meeting, etc)'),
    'converse': ('v', '(about sth); ~ (together) (fml ) talk'),
    'convert': ('v', '(sth) (from sth) (into/to sth) change (sth) from one form or use to another'),
    'convince': ('v', 'sb make sb feel certain; cause sb to realize'),
    'cooperate': ('', 'to work or act together'),
    'coordinate': ('', 'vt. to organize or integrate (diverse elements) in a harmonious operation'),
    'core': ('n', 'centre of such fruits as the apple and pear, containing the seeds'),
    'corporate': ('adj', 'of or shared by all the members of a group; collective'),
    'correspond': ('v', 'be in agreement; not contradict sth or each other'),
    'couple': ('n', 'two people or things that are seen together or associated, esp a man and woman together'),
    'create': ('v', 'cause to exist; make (sth new or original)'),
    'credit': ('n', 'permission to delay payment for goods and services until after they have been received; system of paying in this way'),
    'criteria': ('n', '(pl of criterion) standard by which sth is judged'),
    'crucial': ('adj', 'very important; decisive'),
    'culture': ('n', 'refined understanding and appreciation of art, literature, etc'),
    'currency': ('n', 'money system in use in a country'),
    'cycle': ('n', 'series of events that are regularly repeated in the same order'),
    'data': ('n', 'facts or information used in deciding or discussing sth'),
    'debate': ('n', 'formal argument or discussion of a question, eg at a public meeting or in Parliament, with two or more opposing speakers, and often ending in a vote'),
    'decade': ('n', 'period of ten years'),
    'decline': ('v', "say `no' to (sth); refuse (sth offered), usu politely"),
    'deduce': ('v', 'sth arrive at (facts, a theory, etc) by reasoning; infer sth'),
    'define': ('v', 'sth state precisely the meaning of (eg words)'),
    'definite': ('adj', 'clear; not doubtful'),
    'demonstrate': ('v', 'sth (to sb) show sth clearly by giving proof or evidence'),
    'denote': ('v', 'be the name, sign or symbol of (sth); refer to'),
    'deny': ('v', 'say that (sth) is not true'),
    'depress': ('v', 'make sad and without enthusiasm'),
    'derive': ('v', 'sth from sth obtain sth from sth; get sth from sth'),
    'design': ('n', '(for sth) drawing or outline from which sth may be made'),
    'despite': ('', 'prep without being affected by'),
    'detect': ('v', 'discover or recognize that (sth) is present'),
    'deviate': ('v', 'from sth stop following'),
    'device': ('n', 'thing made or adapted for a special purpose'),
    'devote': ('v', 'oneself/sth to sb/sth give to sb/sth; dedicate ;'),
    'differentiate': ('v', 'between A and B; ~ A (from B) see or show (two things) to be different; show sth to be different (from sth else)'),
    'dimension': ('n', 'measurement of any sort'),
    'diminish': ('v', 'become smaller or less; decrease'),
    'discriminate': ('v', '~ A from B see or make a difference (between two things)'),
    'displace': ('v', 'move from the usual or correct place'),
    'display': ('v', 'sth put sth on show'),
    'dispose': ('v', 'place(sb/sth) in a suitable way; arrange'),
    'distinct': ('adj', 'easily heard, seen, felt or understood; definite'),
    'distort': ('v', 'pull or twist out of its usual shape'),
    'distribute': ('v', 'sth separate sth into parts and give a share to each person or thing'),
    'diverse': ('adj', 'of different kinds; varied'),
    'document': ('n', 'paper, form, book, etc giving information about sth, evidence or proof of sth'),
    'domain': ('n', 'lands owned or ruled by a nobleman, government, etc'),
    'domestic': ('adj', 'of the home, household or family'),
    'dominate': ('v', 'have control of or a very strong influence on (people, events, etc)'),
    'draft': ('n', 'rough preliminary written version of sth'),
    'drama': ('n', 'play for the theatre, radio or TV'),
    'duration': ('n', 'time during which sth lasts or continues'),
    'dynamic': ('adj', 'of power or forces that produce movement'),
    'economy': ('n', 'avoidance of waste (of money, strength, time, resources, etc)'),
    'edit': ('v', 'prepare for publication, eg in a book, newspaper, or magazine'),
    'element': ('n', 'necessary or characteristic part of sth'),
    'eliminate': ('v', 'sb/sth remove (esp sb/sth that is not wanted or needed)'),
    'emerge': ('v', 'come out or up (from water, etc)'),
    'emphasis': ('n', 'force or stress given to a word or words when spoken, to make the meaning clear or to show importance'),
    'empirical': ('adj', 'based on observation or experiment, not on theory'),
    'enable': ('v', 'make able to do sth by giving him the necessary authority or means'),
    'encounter': ('v', 'meet or find oneself faced by (sth/sb unpleasant, dangerous, difficult, etc)'),
    'energy': ('n', 'ability to act or work with strength and eagerness'),
    'enforce': ('v', 'sth force people to obey (a law, etc); make sth effective'),
    'enhance': ('v', 'increase make (sb/sth) look better'),
    'enormous': ('adj', 'very large; immense'),
    'ensure': ('v', 'make sure; guarantee'),
    'entity': ('n', 'thing with distinct and real existence'),
    'environment': ('n', "conditions, circumstances, etc affecting people's lives"),
    'equate': ('v', 'sth consider sth as equal or equivalent (to sth else)'),
    'equip': ('v', 'sb/sth (with sth) supply sb/sth (with what is needed, for a particular purpose)'),
    'equivalent': ('adj', 'equal in value, amount, meaning, importance, etc'),
    'erode': ('v', 'destroy or wear (sth) away gradually'),
    'error': ('n', 'thing done wrongly; mistake'),
    'establish': ('v', 'set up on a firm or permanent basis'),
    'estate': ('n', 'area of land, esp in the country, with one owner'),
    'estimate': ('n', 'judgement or calculation of the approximate size, cost, value, etc of sth'),
    'ethic': ('n', 'system of moral principles; rules of conduct'),
    'ethnic': ('adj', 'of a national, racial or tribal group that has a common cultural tradition'),
    'evaluate': ('v', 'find out or form an idea of the amount or value of (sb/sth); assess'),
    'eventual': ('adj', 'happening at last as a result; ultimate'),
    'evident': ('adj', '(that...) obvious (to the eye or mind); clear'),
    'evolve': ('v', '(cause to) develop naturally and (usu) gradually'),
    'exceed': ('v', 'be greater or more numerous than (esp a quantity)'),
    'exclude': ('v', 'sb/sth prevent sb from entering somewhere, taking part in sth, etc; keep sb out'),
    'exhibit': ('n', 'object or collection of objects displayed for the public, eg in a museum'),
    'expand': ('v', '(into sth) (cause sth to) become greater in size, number or importance'),
    'expert': ('n', 'person with special knowledge, skill or training in a particular field'),
    'explicit': ('adj', '(of a statement, etc) clearly and fully expressed'),
    'exploit': ('n', 'brave or adventurous deed or action'),
    'expose': ('v', 'uncover or make (sth) visible; display'),
    'external': ('adj', 'outside; situated on the outside of sth (esp the body)'),
    'extract': ('v', 'sth take or get sth out, usu with effort or by force'),
    'facilitate': ('v', '(of an object, a process, etc but not of a person) make (sth) easy or less difficult'),
    'factor': ('n', 'fact, circumstance, etc that helps to produce a result'),
    'feature': ('n', 'one of the named parts of the face (eg nose, mouth, eyes) which together form its appearance'),
    'federal': ('', 'of or relating to a form of government or a country in which power is divided between one central and several regional government'),
    'fee': ('n', '(usu pl ) amount paid for professional advice or service, eg to private teachers, doctors, etc'),
    'file': ('n', 'metal tool with a rough surface for cutting, smoothing or shaping hard substances'),
    'final': ('adj', 'of the end; coming last'),
    'finance': ('n', 'management of money'),
    'finite': ('adj', 'having bounds; limited; not infinite'),
    'flexible': ('adj', 'that can bend easily without breaking'),
    'fluctuate': ('v', '(of a price, number, rate, etc) rise and fall; change irregularly'),
    'focus': ('n', '= >Usage at data data. point at which rays (of light, sound, etc) meet or from which theyappear to come'),
    'format': ('n', 'shape, size, binding, etc of a book'),
    'formula': ('n', '(chemistry ) set of symbols showing the elements that a substance is made of'),
    'forthcoming': ('adj', 'about to happen or appear in the near future'),
    'foundation': ('n', 'act of founding founded [ find: ] to meet with or discover by chance'),
    'framework': ('n', 'structure giving shape and support'),
    'function': ('n', 'special activity or purpose of a person or thing'),
    'fund': ('n', 'sum of money saved or made available for a particular purpose'),
    'fundamental': ('adj', 'of or forming the basis or foundation of sth; essential'),
    'furthermore': ('adv', 'in addition; moreover ;'),
    'gender': ('n', '(in certain languages) classification of a noun or pronoun as masculine or feminine'),
    'generate': ('v', 'cause to exist or occur; produce'),
    'globe': ('n', 'small spherical model of the earth showing the continents and usu also countries, rivers, cities, etc'),
    'goal': ('n', '(in football, hockey, etc) pair of posts with a crossbar, between which the ball has to be kicked, hit, etc in order to score'),
    'grade': ('n', 'step, stage or degree of rank, quality, etc; level of classification'),
    'grant': ('v', 'agree to give or allow (what is asked for)'),
    'guarantee': ('n', '(against sth) promise (usu in writing) that certain conditions agreed to in a transaction will be fulfilled'),
    'guideline': ('', 'a principle put forward to set standards or determine a course of actio'),
    'hence': ('adv', 'from this time'),
    'hierarchy': ('n', 'system with grades of authority or status from the lowest to the highest'),
    'highlight': ('n', 'best, most interesting or most exciting part of something'),
    'hypothesis': ('n', 'idea or suggestion that is based on known facts and is used as a basis for reasoning or further investigation'),
    'identical': ('adj', 'the ~ the same'),
    'identify': ('v', 'sb/sth as sb/sth show, prove, etc who or what sb/sth is; recognize sb/sth (as being the specified person or thing)'),
    'ideology': ('n', 'ideas that form the basis of an economic or political theory or that are held by a particular group or person ignorant adj. ~ (of sth)knowing little or nothing; lacking education or information; unaware'),
    'illustrate': ('v', 'supply with pictures, diagrams, etc'),
    'image': ('n', 'copy of the shape of a person or thing, esp one made in stone or wood; statue'),
    'immigrate': ('v', 'enter a foreign country in order to live there permanently'),
    'impact': ('n', 'hitting of one object against another'),
    'implement': ('n', 'tool or instrument'),
    'implicate': ('v', 'sb show that sb is involved in sth, esp a crime'),
    'implicit': ('adj', 'implied, but not expressed directly; not explicit'),
    'imply': ('v', 'suggest (sth) indirectly rather than state it directly; hint'),
    'impose': ('v', 'sth place (a penalty, tax, etc) officially on sb/sth'),
    'incentive': ('n', 'thing that encourages sb to do sth; stimulus'),
    'incidence': ('n', 'of sth extent to which sth happens or has an effect'),
    'incline': ('v', 'towards sth lean or slope in the direction of sth'),
    'income': ('n', 'money received over a certain period, esp as payment for work or as interest on investments'),
    'incorporate': ('v', 'sth (in/into sth) make sth part of a whole; include'),
    'index': ('n', 'list of names or topics referred to in a book, etc, usu arranged at the end in alphabetical order'),
    'indicate': ('v', 'sth (to sb) show sth, esp by pointing'),
    'induce': ('v', 'persuade or influence (sb) to do sth'),
    'inevitable': ('adj', 'that cannot be avoided; that is sure to happen'),
    'infer': ('v', 'sth (from sth) reach (an opinion) from facts or reasoning; conclude sth'),
    'infrastructure': ('n', 'subordinate parts, installations, etc that form the basis of a system, an organization oran enterprise (eg of an army) ,'),
    'inherent': ('adj', 'existing as a natural or permanent feature or quality of sb/sth'),
    'inhibit': ('v', 'sb prevent sb from doing sth that should be natural or easy to do'),
    'initial': ('adj', 'of or at the beginning; first'),
    'initiate': ('v', 'put (a scheme, etc) into operation; cause (sth) to begin'),
    'injure': ('v', 'hurt (sb); harm'),
    'innovate': ('v', 'make changes; introduce new things'),
    'input': ('n', 'action of putting sth in'),
    'insert': ('v', 'sth put, fit, place sth into sth or between two things'),
    'insight': ('n', '(approv ) ability to see into the true nature (of sth); deep understanding'),
    'inspect': ('v', 'examine (sth) closely'),
    'instance': ('n', 'particular occurrence of sth that happens generally or several times; example; case'),
    'institute': ('n', 'society or organization for a special (usu social, professional or educational) purpose'),
    'instruct': ('', 'to direct to do something; order'),
    'integral': ('adj', 'necessary for completeness'),
    'integrate': ('v', 'sth (into sth); ~ A and B/~ A with B combine sth in such a way that it becomes fully a part of sth else'),
    'integrity': ('n', 'quality of being honest and morally upright'),
    'intelligence': ('n', 'power of learning, understanding and reasoning; mental ability'),
    'intense': ('adj', '(of sensations) very great or severe; extreme'),
    'interact': ('v', 'act or have an effect on each other'),
    'intermediate': ('adj', 'situated or coming between two people, things, etc in time, space, degree, etc'),
    'internal': ('adj', 'of or on the inside'),
    'interpret': ('v', 'explain (sth which is not easily understandable)'),
    'interval': ('n', 'time between two events'),
    'intervene': ('v', '(of time) come or be between'),
    'intrinsic': ('adj', 'belonging naturally; existing within, not coming from outside'),
    'invest': ('v', '(in sth/with sb) use (money) to buy shares, property, etc, in order to earn interest or bring profit'),
    'investigate': ('v', 'find out and examine in order to obtain the truth'),
    'invoke': ('v', "use (sth) as a reason for one's action"),
    'involve': ('v', 'make necessary as a condition or result; entail'),
    'isolate': ('v', 'sb/sth put or keep sb/sth entirely apart from other people or things; separate sb/sth ;'),
    'item': ('n', 'single article or unit in a list, etc'),
    'job': ('n', 'the patience of job'),
    'journal': ('n', 'newspaper or periodical, esp one that is serious and deals with a specialized subject'),
    'justify': ('v', 'show that (sb/sth) is right, reasonable or just'),
    'label': ('n', 'piece of paper, cloth, metal, etc on or beside an object and describing its nature, name, owner, destination, etc'),
    'labour': ('n', 'physicalor mental work'),
    'layer': ('n', 'thickness of material laid over a surface or forming a horizontal division'),
    'lecture': ('n', '(on sth) talk giving information about a subject to an audience or a class, often as part of a teaching programme'),
    'legal': ('adj', 'of or based on the law'),
    'levy': ('v', 'sth (on sb) collect (a payment, etc) by authority or force; impose sth'),
    'liberal': ('adj', 'tolerant and open-minded; free from prejudice'),
    'licence': ('n', 'official document showing that permission has been given to own, use or do sth'),
    'link': ('n', 'one ring or loop of a chain'),
    'locate': ('v', 'discover the exact position or place of'),
    'logic': ('n', 'science of reasoning'),
    'maintain': ('v', 'sth cause sth to continue; keep sth in existence at the same level, standard, etc'),
    'manipulate': ('v', 'control or handle with skill'),
    'manual': ('adj', 'of, done with or controlled by the hands'),
    'margin': ('n', 'blank space round the written or printed matter on a page'),
    'mature': ('adj', "fully grown or developed mentally or physically; having achieved one's full potential"),
    'maximise': ('', '[ maximize: ] vt. to make as high or great as possible; increase to a maximum'),
    'mechanism': ('n', 'working parts of a machine, etc'),
    'media': ('n', 'the media means of mass communication, eg TV, radio, newspapers'),
    'mediate': ('v', 'act as a peacemaker or go-between for two or more people, groups, etc who disagree'),
    'medical': ('adj', 'of the art of medicine; of curing disease'),
    'medium': ('n', '(pl usu media) means by which sth is expressed or communicated'),
    'mental': ('adj', 'of, in or to the mind'),
    'migrate': ('v', '(to...) move from one place to go to live or work in another'),
    'military': ('adj', 'of or for soldiers or an army; of or for armed forces'),
    'minimal': ('adj', 'smallest in amount or degree'),
    'minimise': ('', '[ minimize: ] to reduce to or estimate at the least possible degree or amount'),
    'minimum': ('n', 'least or smallest amount, degree, etc possible'),
    'ministry': ('n', '(buildings containing a) government department'),
    'minor': ('adj', 'smaller, less serious, less important, etc'),
    'mode': ('n', '(fml ) way or manner in which sth is done'),
    'modify': ('v', 'change (sth) slightly, esp to make it less extreme or to improve it'),
    'monitor': ('n', 'device used to observe, record or test sth'),
    'motive': ('n', 'that which causes sb to act in a particular way; reason'),
    'mutual': ('adj', 'felt or done by each towards the other'),
    'negate': ('v', 'deny or disprove the existence of (sb/sth)'),
    'network': ('n', 'complex system of roads, etc crossingeach other'),
    'neutral': ('adj', 'not supporting or helping either side in a dispute, contest,war, etc; impartial'),
    'nevertheless': ('', 'adv, conj in spite of this; however; still'),
    'norm': ('n', 'standard or pattern that is typical (of a group, etc)'),
    'normal': ('adj', 'in accordance with what is typical, usual or regular'),
    'notion': ('n', 'idea or belief; concept'),
    'notwithstanding': ('', 'prep (can also follow the n to which it refers ) without being affected by (sth); in spite of'),
    'nuclear': ('adj', 'of a nucleus, esp of an atom'),
    'objective': ('adj', 'not influenced by personal feelings or opinions; unbiased; fair'),
    'obtain': ('v', 'sth et sth; come to own or possess sth (by buying, borrowing, taking, etc)'),
    'obvious': ('adj', 'easily seen, recognized or understood; clear'),
    'occupy': ('v', 'live in or have possession of (a house, land, etc)'),
    'occur': ('v', 'come into being as an event or a process; happen'),
    'odd': ('adj', 'strange; unusual; peculiar'),
    'offset': ('v', 'sth (by sth/doing sth) compensate for sth; balance sth'),
    'ongoing': ('adj', 'continuing to exist or progress'),
    'option': ('n', 'power or freedom of choosing; choice'),
    'orient': ('n', 'the Orient countries of the (Far) East (eg Japan, China)'),
    'outcome': ('n', 'effect or result (of an event, circumstances, etc)'),
    'output': ('n', 'quantity of goods, etc produced'),
    'overall': ('adj', 'including everything; total'),
    'overlap': ('v', 'partly cover (sth) by extending over its edge'),
    'overseas': ('adj', 'across the sea; foreign'),
    'panel': ('n', 'separate, usu rectangular, part of the surface of a door, wall, ceiling, etc, usu raisedaboveor sunk below the surrounding area'),
    'paradigm': ('n', 'set of all the different forms of a word'),
    'paragraph': ('n', 'distinct section of a written or printed text, usu consisting of several sentences dealingwith a single theme and starting on a new line'),
    'parallel': ('adj', '(of two or more lines) having the same distance between each other at every point'),
    'parameter': ('n', 'quantity that does not vary in a particular case but does vary in other cases'),
    'participate': ('v', 'take part or become involved (in an activity)'),
    'partner': ('n', 'person who takes part in an activity with another or others, esp one of several owners of a business'),
    'passive': ('adj', 'not active; submissive'),
    'perceive': ('v', 'become aware of (sb/sth); notice; observe percent'),
    'period': ('n', 'length or portion of time'),
    'persist': ('v', 'continue to do sth, esp in an obstinate and determined way and in spite of opposition, argument or failure'),
    'perspective': ('n', 'art of drawing solid objects on a flat surface so as to give the right impression of their height, width, depth and position in relation to each other'),
    'phase': ('n', 'stage in a process of change or development'),
    'phenomenon': ('n', 'fact or occurrence, esp in nature or society, that can be perceived by the senses'),
    'philosophy': ('n', 'search for knowledge and understanding of the nature and meaning of the universe and of human life'),
    'physical': ('adj', 'of or concerning material things'),
    'plus': ('', 'prep with the addition of'),
    'policy': ('n', 'plan of action, statement of ideals, etc proposed or adopted by a government, politicalparty, business, etc'),
    'portion': ('n', 'part or share into which sth is divided'),
    'pose': ('v', '(for sb) sit or stand in a particular position in order to be painted, drawn or photographed'),
    'positive': ('adj', 'with no possibility of doubt; clear and definite'),
    'potential': ('adj', 'that can or may come into existence; possible'),
    'practitioner': ('n', 'person who practises a skill or an art'),
    'precede': ('v', 'come or go before in time, order, rank, etc'),
    'precise': ('adj', 'stated clearly andaccurately'),
    'predict': ('v', 'say in advance that will happen; forecast'),
    'predominant': ('adj', 'having more power or influence than others'),
    'preliminary': ('adj', 'coming before a more important action or event; preparatory'),
    'presume': ('v', 'suppose to be true; take (sth) for granted'),
    'previous': ('adj', 'coming before in time or order'),
    'primary': ('adj', 'earliest in time or order of development'),
    'prime': ('adj', 'most important; chief; fundamental'),
    'principal': ('adj', 'first in rank or importance; chief; main'),
    'principle': ('n', 'basic general truth that underlies sth'),
    'prior': ('adj', 'coming before in time, order or importance'),
    'priority': ('n', '(state of) being more important (in rank)'),
    'proceed': ('v', '(to sth) go to a further or the next stage; go on'),
    'process': ('n', 'series of actions or operations performed in order to do, make or achieve sth'),
    'professional': ('adj', 'of or belonging to a profession'),
    'prohibit': ('v', 'sth/sb (from doing sth) forbid sth or sb from doing sth esp by laws, rules or regulations'),
    'project': ('n', 'scheme or undertaking'),
    'promote': ('', 'to contribute to the growth or prosperity of:FURTHER'),
    'proportion': ('n', 'comparative part or share of a whole; fraction'),
    'prospect': ('n', '(dated ) wide view of a landscape, etc'),
    'protocol': ('n', 'system of rules governing formal occasions, eg meetings between governments, diplomats, etc; official etiquette'),
    'psychology': ('n', 'science or study of the mind and how it functions'),
    'publication': ('n', 'action of making a book or periodical, available to the public'),
    'publish': ('v', 'prepare, have printed and distribute to the public (a book, periodical, etc)'),
    'purchase': ('n', '(action of) buying sth'),
    'pursue': ('v', 'follow (sb/sth), esp in order to catch or kill; chase ,'),
    'qualitative': ('adj', 'of or concerned with quality'),
    'quote': ('v', '(from sb/sth) repeat in speech or writing (words previously said or written by anotherperson)'),
    'radical': ('adj', 'of or from the root or base; fundamental'),
    'random': ('adj', 'done, chosen, etc without method or conscious choice; haphazard'),
    'range': ('n', 'connected line or row of mountains, hills, etc'),
    'ratio': ('n', 'relation between two amounts determined by the number of times one contains the other'),
    'rational': ('adj', 'able to reason'),
    'react': ('v', 'behave differently or change as a result of sth; respond'),
    'recover': ('v', 'sth find again (sth stolen, lost, etc); regain possession of sth'),
    'refine': ('v', 'remove impurities from (sth); purify'),
    'regime': ('n', 'method or system of government'),
    'region': ('n', 'part of a surface or bodyor space with or without definite boundaries or characteristicfeatures'),
    'register': ('n', 'official list or record of names, items, attendances, etc'),
    'regulate': ('v', 'control or direct by means of rules and restrictions'),
    'reinforce': ('v', 'make stronger by adding material, etc'),
    'reject': ('v', 'refuse to accept'),
    'relax': ('v', '(make sth) become less tight, stiff, etc'),
    'release': ('v', 'sb/sth (from sth) allow (a person or an animal) to go; set free or liberate sb/sth ;'),
    'relevant': ('adj', '(to sth/sb)connected with what is being discussed, what is happening,what is being done, etc reluctance Unwillingness.'),
    'rely': ('v', '(pt, pp relied) ~ on/upon sb/sth (to do sth) count or depend on sb/sth'),
    'remove': ('v', 'sth/sb (from sth) take sth/sb away from one place to another'),
    'require': ('v', 'depend on (sb/sth) for success, fulfilment, etc; need'),
    'research': ('n', '(on sb) careful study or investigation, esp in order to discover new facts or information'),
    'reside': ('v', "(in/at...) have one's home (in a certain place); live"),
    'resolve': ('v', 'on/upon/against sth/doing sth decide firmly; determine'),
    'resource': ('n', 'supply of raw materials, etc which bring a country, person, etc wealth'),
    'respond': ('v', '(with sth) give a verbal or written answer'),
    'restore': ('v', 'sth (fml ) give back (sth lost, etc) to its owner'),
    'restrain': ('v', 'sb/sthhold back sb/sth from movementor action; keep sb/sth under control or in check'),
    'restrict': ('v', 'sb/sth (to sth) put a limit on sb/sth'),
    'retain': ('v', "keep (sth) in one's possession or use"),
    'reveal': ('v', 'sth make (facts, etc) known'),
    'revenue': ('n', 'income, esp the total annual income of the State from taxes, etc'),
    'reverse': ('adj', 'contrary or opposite to what is expected'),
    'revise': ('v', 're-examine (sth), esp in order to correct or improve it'),
    'revolution': ('n', 'overthrow of a system of government, esp by force'),
    'rigid': ('adj', 'stiff; not bending or yielding'),
    'role': ('n', "actor's part in a play"),
    'route': ('n', 'way taken or planned to get from one place to another'),
    'scenario': ('n', 'written outline of a film, play, etc with details of the scenes and plot'),
    'schedule': ('n', 'programme of work to be done or of planned events'),
    'scheme': ('n', 'plan for doing or organizing sth'),
    'scope': ('n', 'opportunity to do or achieve sth'),
    'section': ('n', 'any of the parts into which sth may be or has been divided'),
    'sector': ('n', 'part of a circle lying between two straight lines drawn from the centre to the circumference .'),
    'secure': ('adj', 'not feeling worry, doubt, etc'),
    'seek': ('v', '(after/for sth) look (for sth); try to find or obtain (sth)'),
    'select': ('v', 'sb/sth choose sb/sth, esp as being the best or most suitable'),
    'sequence': ('n', 'set of events, numbers, actions, etc with each following the one before continuously or in a particular order'),
    'series': ('n', 'number of things, events, etc of a similar kind, esp. placed or occurring one after another'),
    'sex': ('n', 'condition of being male or female; gender'),
    'shift': ('v', '(sth/sb/oneself) (from.../to...); ~ (sth/sb/oneself) (about/around) (cause sth/sb/oneself to) change or move from one position or direction to another [/]'),
    'significant': ('adj', 'having a meaning, esp one that is immediately obvious'),
    'similar': ('adj', 'resembling sb/sth but not the same; alike'),
    'simulate': ('v', 'pretend to have or feel'),
    'site': ('n', 'place where a building, town, etc was, is, or will be situated'),
    'so-called': ('adj', '(used to suggest that the words used to describe sb/sth are not appropriate )'),
    'sole': ('n', 'flat sea-fish that is eaten as food'),
    'somewhat': ('', 'indef adv to some degree; rather'),
    'source': ('n', 'starting-point of a river'),
    'specific': ('adj', 'detailed, precise and exact'),
    'specify': ('v', '(esp fml ) state or name clearly and definitely (details, materials, etc)'),
    'sphere': ('n', 'solid figure that is entirely round (ie with every point on the surface at an equal distance from the centre)'),
    'stable': ('adj', 'firmly established or fixed; not likely to move or change'),
    'statistic': ('n', 'item of information expressed in numbers'),
    'status': ('n', "person's social, legal or professional position or rank in relation to others"),
    'straightforward': ('adj', 'honest and frank, without evasion'),
    'strategy': ('n', 'planning and directing an operation in a war or campaign'),
    'stress': ('n', 'mental or physical distress, difficult circumstances, etc'),
    'structure': ('n', 'way in which sth is put together, organized, built, etc'),
    'style': ('n', 'manner of writing or speaking, esp contrasted with what is actually written or said'),
    'submit': ('v', '(to sb/sth) accept the control, superior strength, etc (of sb/sth); yield (to sb/sth) ; ,'),
    'subordinate': ('adj', '(to sb) lower in rank or position'),
    'subsidy': ('n', 'money paid, esp by a government, to help an industry, to support the arts, to keep pricesdown, etc'),
    'substitute': ('n', 'person or thing that replaces, acts for or serves as sb or sth else'),
    'successor': ('n', 'person or thing that comes after and takes the place of (sb/sth)'),
    'summary': ('n', 'brief statement of themain points of sth'),
    'supplement': ('n', 'thing added to sth else to improve or complete it'),
    'survey': ('v', 'look carefully at all of (sth/sb), esp from a distance'),
    'survive': ('v', '~ (on sth) continue to live or exist'),
    'suspend': ('v', 'sth (fml ) hang sth up'),
    'sustain': ('v', 'bear (weight) without breaking or falling'),
    'symbol': ('n', 'image, object, etc that suggests or refers to sth else; emblem'),
    'tape': ('n', 'narrow strip of material used for tying, fastening or labelling things'),
    'target': ('n', 'object or mark that a person tries to hit in shooting, etc; disc marked with concentric circles for this purpose in archery ; .'),
    'task': ('n', 'piece of work that has to be done'),
    'team': ('n', 'group of players forming one side in certain games and sports'),
    'technical': ('adj', 'of or involving the mechanical arts and applied sciences'),
    'technique': ('n', 'method of doing or performing sth, esp in the arts or sciences'),
    'technology': ('n', 'scientificstudy and use of mechanical arts and applied sciences, eg engineering'),
    'temporary': ('adj', 'lasting or meant to last for a limited time only; notpermanent'),
    'tense': ('adj', 'stretched tightly; taut ;'),
    'terminate': ('v', 'come to an end or bring (sth) to an end'),
    'text': ('n', 'main written or printed part of a book or page'),
    'theme': ('n', "subject of a talk, a piece of writing or a person's thoughts; topic"),
    'theory': ('n', 'set of reasoned ideas intended to explain facts or events'),
    'thereby': ('adv', 'by that means'),
    'thesis': ('n', 'statement or theory put forward and supported by arguments'),
    'topic': ('n', 'subject of a discussion, talk, programme, written work, etc'),
    'trace': ('n', 'mark, track, sign, etc showing what has existed or happened'),
    'tradition': ('n', 'passing of beliefs or customs from one generation to the next, esp without writing'),
    'transfer': ('v', 'sth/sb (from...) (to...) move sth/sb from one place to another'),
    'transform': ('v', 'sth/sb (into sth) completely change the appearance or character of sth/sb'),
    'transit': ('n', 'process of going or being taken or transported from one place to another'),
    'transmit': ('', 'To send trough or across.'),
    'transport': ('v', 'sth/sb (to...) take sth/sb from one place to another in a vehicle'),
    'trend': ('n', 'general tendency or direction'),
    'trigger': ('n', 'lever that releases a spring, esp so as to fire a gun'),
    'ultimate': ('adj', 'beyond which no other exists or is possible; last or final'),
    'undergo': ('v', 'experience or endure (sth unpleasant or painful)'),
    'underlie': ('v', 'lie or exist beneath (sth)'),
    'undertake': ('v', '(fml ) (start to) make oneself responsible for (sth)'),
    'uniform': ('adj', 'not changing in form or character; unvarying'),
    'unify': ('v', 'form (sth) into a single unit or make uniform'),
    'unique': ('adj', 'being the only one of its type'),
    'utilise': ('', 'vt. (= utilize) to put to use, especially to find a profitable or practical use for'),
    'valid': ('adj', 'legally effective because made or done with the correct formalities'),
    'vary': ('v', '(in sth) be different in size, volume, strength, etc'),
    'vehicle': ('n', 'conveyance such as a car, lorry or cart used for transporting goods or passengers on land'),
    'version': ('n', 'account of an event, etc from the point of view of one person'),
    'via': ('', 'prep by way of (sth); through'),
    'violate': ('v', 'break or be contrary to'),
    'virtual': ('adj', 'being or acting as what is described, but not accepted as such in name or officially'),
    'visible': ('adj', 'that can be seen; in sight'),
    'vision': ('n', 'power of seeing; sight'),
    'visual': ('adj', 'concerned with or used in seeing'),
    'volume': ('n', 'book, esp one of a matching set or a series'),
    'voluntary': ('adj', 'acting,done or given willingly'),
    'welfare': ('n', 'good health, happiness, prosperity, etc of a person or group'),
    'whereas': ('', 'conj taking into consideration the fact that ...'),
    'whereby': ('', 'rel adv by which'),
    'widespread': ('', 'extending over a wide area'),
}

#: PDF 裡漏掉的 15 個字頭，補上詞性與定義。
#: 沒有定義的卡片在任何模式都出不了題（拼字模式沒線索、複習模式沒例句），
#: 只會卡在補完佇列裡，所以這些一定要補。
#: 寫法跟上面一致：學習型辭典的口吻、小寫開頭、句尾不加句號。
MISSING_FROM_PDF = {
    'albeit': ('conj', 'although; even though'),
    'anticipate': ('v', 'expect (sth); see what needs doing and do it in advance'),
    'cite': ('v', 'quote (a passage, book or author) as evidence for an argument'),
    'conceive': ('v', 'form (a plan or idea) in the mind; imagine'),
    'conflict': ('n', 'serious disagreement or clash between opposing ideas, interests or groups'),
    'discrete': ('adj', 'separate and distinct; not joined to or continuous with others'),
    'found': ('v', 'establish (an institution or organization), esp by providing money for it'),
    'generation': ('n', 'all the people born at about the same time; the production of sth such as electricity or heat'),
    'ignorance': ('n', 'lack of knowledge or information about sth'),
    'likewise': ('adv', 'in the same way; also'),
    'nonetheless': ('adv', 'in spite of that; nevertheless'),
    'reluctance': ('n', 'unwillingness to do sth; hesitation'),
    'subsequent': ('adj', 'coming after sth else in time; following'),
    'sufficient': ('adj', 'enough for a particular purpose'),
    'sum': ('n', 'an amount of money; the total obtained by adding numbers together'),
}

DEFINITIONS.update(MISSING_FROM_PDF)

#: PDF 有抽到定義、但詞性被寫在定義文字裡（"prep without being affected by"），
#: 或抽壞了（"To send trough or across."、"...course of actio"、":FURTHER"）。
#: 這裡把詞性拉出來、順手把句子修乾淨，寫法對齊上面。
CLEANED_FROM_PDF = {
    'adjacent': ('adj', 'having a common endpoint or border; immediately preceding or following'),
    'context': ('n', 'the words that come before and after a passage and fix its meaning; the situation in which sth happens'),
    'cooperate': ('v', 'work or act together'),
    'coordinate': ('v', 'organize or integrate (diverse elements) into a harmonious operation'),
    'despite': ('prep', 'without being affected by; in spite of'),
    'federal': ('adj', 'relating to a system of government in which power is divided between one central and several regional governments'),
    'guideline': ('n', 'a principle put forward to set standards or determine a course of action'),
    'instruct': ('v', 'direct (sb) to do sth; order'),
    'maximise': ('v', 'make as high or great as possible; increase to a maximum'),
    'minimise': ('v', 'reduce to the least possible degree or amount'),
    'nevertheless': ('adv', 'in spite of this; however; still'),
    'notwithstanding': ('prep', 'without being affected by (sth); in spite of'),
    'plus': ('prep', 'with the addition of'),
    'promote': ('v', 'contribute to the growth or prosperity of; further'),
    'somewhat': ('adv', 'to some degree; rather'),
    'transmit': ('v', 'send (sth) through or across'),
    'utilise': ('v', 'put to use, esp to find a profitable or practical use for'),
    'via': ('prep', 'by way of (sth); through'),
    'whereas': ('conj', 'in contrast with the fact that; while on the other hand'),
    'whereby': ('adv', 'by which'),
    'widespread': ('adj', 'extending over a wide area'),

    # 抽到的定義本身就有問題：'job' 抽到的是諺語（the patience of job），
    # 'orient' 抽到的是名詞「東方」而不是 AWL 要的動詞，其餘則是定義裡直接
    # 出現被定義的字（拼字模式會把它遮掉，等於白給一行看不懂的線索）。
    'automate': ('v', 'convert (a process or facility) to be operated by machines rather than people'),
    'behalf': ('n', 'the interest or support of a person or group, as when acting as their representative'),
    'job': ('n', 'a paid position of regular employment; a task or piece of work'),
    'media': ('n', 'the main means of mass communication — television, radio, newspapers and the internet — taken as a whole'),
    'orient': ('v', 'align or position (sth) relative to a fixed point; familiarize (sb) with a new situation'),
    'rely': ('v', 'depend on (sb/sth) with full trust or confidence; count on'),
}

DEFINITIONS.update(CLEANED_FROM_PDF)
