"""AWL Sublist 1 —— 學術英語最高頻的一組，四個維度全部寫齊。

（constitute 已寫在 data_awl.py 的 FULL 裡，這裡不重複。）
"""

SUBLIST_1 = [
    {
        "word": "analyse", "pos": "v.",
        "example": "Researchers analysed data from more than fifty countries.",
        "collocations": ["analyse data", "carefully analyse", "analyse the results"],
        "root": "ana-(徹底) + lys(鬆開, 同 analysis/paralysis) → 拆開來一項項看",
        "synonyms": ["examine", "study", "break down", "scrutinise"],
        "zh": "分析",
        "notes": "美式拼 analyze，雅思兩種都接受，但一份作文裡要統一",
    },
    {
        "word": "approach", "pos": "n.",
        "example": "The school has adopted a completely new approach to teaching maths.",
        "collocations": ["a new approach", "take an approach", "a holistic approach"],
        "root": "ap-(朝向) + proach(接近, 拉丁 prope 近, 同 proximity) → 走近某事的方式",
        "synonyms": ["method", "way", "strategy", "tactic"],
        "zh": "方法、途徑",
    },
    {
        "word": "area", "pos": "n.",
        "example": "Rainfall in coastal areas is twice the national average.",
        "collocations": ["a rural area", "in this area", "a key area of research"],
        "root": "拉丁 area「空地」→ 一塊範圍，抽象化後也指「領域」",
        "synonyms": ["region", "zone", "field", "sphere"],
        "zh": "區域、領域",
    },
    {
        "word": "assess", "pos": "v.",
        "example": "The report assesses the impact of tourism on local wildlife.",
        "collocations": ["assess the impact", "carefully assess", "assess progress"],
        "root": "as-(朝向) + sess(坐, 同 session/sedentary；法官坐下來核定稅額) → 坐下來評定",
        "synonyms": ["evaluate", "judge", "appraise", "gauge"],
        "zh": "評估",
    },
    {
        "word": "assume", "pos": "v.",
        "example": "Planners assumed that car ownership would keep rising.",
        "collocations": ["assume responsibility", "widely assumed", "safely assume"],
        "root": "as-(朝向) + sum(拿取, 同 consume/resume) → 直接拿過來當前提",
        "synonyms": ["presume", "take for granted", "suppose"],
        "zh": "假設；承擔",
    },
    {
        "word": "authority", "pos": "n.",
        "example": "The local authority approved the plan despite public opposition.",
        "collocations": ["the local authority", "in authority", "an authority on"],
        "root": "auth(創始者, 同 author) + -ity → 有資格說話的來源 → 權威、當局",
        "synonyms": ["power", "jurisdiction", "the officials", "expert"],
        "zh": "當局；權威",
    },
    {
        "word": "available", "pos": "adj.",
        "example": "Free legal advice is available to all students.",
        "collocations": ["readily available", "become available", "widely available"],
        "root": "a-(朝向) + val(價值、有效, 同 value/valid/prevail) + -able → 派得上用場的",
        "synonyms": ["obtainable", "accessible", "on hand", "to be had"],
        "zh": "可取得的",
    },
    {
        "word": "benefit", "pos": "n.",
        "example": "The main benefit of cycling is that it costs almost nothing.",
        "collocations": ["derive benefit from", "mutual benefit", "the benefits of"],
        "root": "bene(好, 同 benefactor/benevolent) + fit/fact(做) → 做好事帶給人的東西",
        "synonyms": ["advantage", "gain", "upside", "payoff"],
        "zh": "好處",
    },
    {
        "word": "concept", "pos": "n.",
        "example": "The concept of a four-day week is no longer unusual.",
        "collocations": ["grasp a concept", "the concept of", "an abstract concept"],
        "root": "con-(一起) + cept(拿, 同 accept/receive/capture) → 把想法整個抓起來",
        "synonyms": ["idea", "notion", "principle"],
        "zh": "概念",
    },
    {
        "word": "consist", "pos": "v.",
        "example": "The programme consists of four modules and a research project.",
        "collocations": ["consist of", "consist largely of", "the course consists of"],
        "root": "con-(一起) + sist(站, 同 assist/resist/insist) → 一起站著構成整體",
        "synonyms": ["be made up of", "comprise", "be composed of"],
        "zh": "由…組成",
        "notes": "consist of 沒有被動式，不能說 is consisted of",
    },
    {
        "word": "context", "pos": "n.",
        "example": "The figure means little without the wider economic context.",
        "collocations": ["in this context", "historical context", "out of context"],
        "root": "con-(一起) + text(編織, 同 textile/texture) → 一起織出來的背景",
        "synonyms": ["setting", "background", "circumstances"],
        "zh": "脈絡、背景",
    },
    {
        "word": "contract", "pos": "n.",
        "example": "Workers on short-term contracts have far fewer rights.",
        "collocations": ["sign a contract", "a binding contract", "under contract"],
        "root": "con-(一起) + tract(拉, 同 attract/extract/tractor) → 把雙方拉在一起",
        "synonyms": ["agreement", "deal", "formal arrangement"],
        "zh": "合約",
    },
    {
        "word": "create", "pos": "v.",
        "example": "The scheme created more than two thousand jobs in one year.",
        "collocations": ["create jobs", "create an impression", "newly created"],
        "root": "拉丁 creare「使生長」(同 creature/increase/recreation) → 讓東西生出來",
        "synonyms": ["produce", "generate", "bring about", "establish"],
        "zh": "創造",
    },
    {
        "word": "data", "pos": "n.",
        "example": "The data collected over ten years show a clear downward trend.",
        "collocations": ["collect data", "raw data", "data suggests"],
        "root": "拉丁 datum「被給予的東西」的複數 → 已經給定的事實",
        "synonyms": ["figures", "statistics", "information"],
        "zh": "數據",
        "notes": "學術寫作常當複數：the data show，不是 shows",
    },
    {
        "word": "define", "pos": "v.",
        "example": "The report never defines what it means by “poverty”.",
        "collocations": ["clearly define", "define the term", "be defined as"],
        "root": "de-(徹底) + fin(界線, 同 finish/finite/confine) → 把界線劃清楚",
        "synonyms": ["specify", "explain", "delineate", "set out"],
        "zh": "定義",
    },
    {
        "word": "derive", "pos": "v.",
        "example": "Most of the country's income derives from tourism.",
        "collocations": ["derive from", "be derived from", "derive benefit"],
        "root": "de-(從…而下) + riv(河流, 同 river/rival) → 從源頭把水引過來",
        "synonyms": ["come from", "stem from", "originate", "obtain"],
        "zh": "源自、取得",
    },
    {
        "word": "distribute", "pos": "v.",
        "example": "Vaccines were distributed to rural clinics first.",
        "collocations": ["distribute resources", "evenly distributed", "distribute aid"],
        "root": "dis-(分開) + tribut(給予, 同 tribute/contribute/attribute) → 分開發出去",
        "synonyms": ["hand out", "allocate", "spread", "disperse"],
        "zh": "分配、分送",
    },
    {
        "word": "economy", "pos": "n.",
        "example": "The economy grew by just under two per cent last year.",
        "collocations": ["the global economy", "a growing economy", "economies of scale"],
        "root": "eco(家, 希臘 oikos, 同 ecology) + nom(管理, 同 astronomy) → 管家 → 經濟",
        "synonyms": ["financial system", "market", "national finances"],
        "zh": "經濟",
    },
    {
        "word": "environment", "pos": "n.",
        "example": "Heavy industry has damaged the environment along the whole river.",
        "collocations": ["protect the environment", "a safe environment", "the working environment"],
        "root": "en-(在…之中) + viron(圍繞, 法文 virer 轉) + -ment → 圍在四周的一切",
        "synonyms": ["surroundings", "setting", "conditions", "habitat"],
        "zh": "環境",
    },
    {
        "word": "establish", "pos": "v.",
        "example": "The university established a research centre for renewable energy.",
        "collocations": ["establish a system", "well established", "establish a link"],
        "root": "拉丁 stabilire「使穩固」(sta 站, 同 stable/static/stand) → 立穩下來",
        "synonyms": ["set up", "found", "create", "institute"],
        "zh": "建立",
    },
    {
        "word": "estimate", "pos": "v.",
        "example": "Engineers estimate that repairs will take eighteen months.",
        "collocations": ["estimate the cost", "roughly estimate", "it is estimated that"],
        "root": "拉丁 aestimare「評定價值」(同 esteem/aim) → 抓個大概的價",
        "synonyms": ["calculate roughly", "put at", "reckon", "gauge"],
        "zh": "估計",
    },
    {
        "word": "evident", "pos": "adj.",
        "example": "It is evident from the graph that demand peaked in 2012.",
        "collocations": ["it is evident that", "clearly evident", "become evident"],
        "root": "e-(出來) + vid(看, 同 video/vision/provide) + -ent → 一看就看得出來的",
        "synonyms": ["obvious", "clear", "apparent", "plain"],
        "zh": "明顯的",
    },
    {
        "word": "export", "pos": "v.",
        "example": "The country exports more coffee than any other producer.",
        "collocations": ["export goods", "export to Europe", "a major export"],
        "root": "ex-(出去) + port(帶, 同 portable/transport/import) → 帶出國門",
        "synonyms": ["send abroad", "ship overseas", "sell overseas"],
        "zh": "出口",
    },
    {
        "word": "factor", "pos": "n.",
        "example": "Cost is the single biggest factor in choosing a university.",
        "collocations": ["a key factor", "contributing factors", "a major factor in"],
        "root": "fact(做, 同 factory/manufacture/affect) + -or → 促成事情發生的東西",
        "synonyms": ["element", "consideration", "cause", "influence"],
        "zh": "因素",
    },
    {
        "word": "finance", "pos": "v.",
        "example": "The new library was financed entirely by donations.",
        "collocations": ["finance a project", "publicly financed", "finance the scheme"],
        "root": "fin(結束, 同 finish/final)；原指「把債務結清」→ 出錢了結 → 資助",
        "synonyms": ["fund", "pay for", "back", "bankroll"],
        "zh": "提供資金",
    },
    {
        "word": "formula", "pos": "n.",
        "example": "There is no simple formula for reducing traffic in old cities.",
        "collocations": ["a simple formula", "apply a formula", "a winning formula"],
        "root": "拉丁 forma「形式」的小詞 → 一個固定的小格式",
        "synonyms": ["recipe", "method", "set procedure"],
        "zh": "公式、方法",
        "notes": "複數 formulae 或 formulas 都可以",
    },
    {
        "word": "function", "pos": "n.",
        "example": "The building's main function is to house the city archive.",
        "collocations": ["perform a function", "the main function", "function as"],
        "root": "funct(履行, 拉丁 fungi, 同 defunct 失效的) + -ion → 所要履行的事",
        "synonyms": ["role", "purpose", "job", "use"],
        "zh": "功能",
    },
    {
        "word": "identify", "pos": "v.",
        "example": "Researchers identified three causes of the decline.",
        "collocations": ["identify a problem", "correctly identify", "identify with"],
        "root": "ident(相同, 同 identical/identity) + -fy(使) → 認出這是同一個",
        "synonyms": ["recognise", "pinpoint", "name", "single out"],
        "zh": "辨識、指出",
    },
    {
        "word": "income", "pos": "n.",
        "example": "Households on a low income spend a third of it on rent.",
        "collocations": ["a low income", "household income", "disposable income"],
        "root": "in(進來) + come(來) → 進到口袋裡的錢",
        "synonyms": ["earnings", "revenue", "pay", "takings"],
        "zh": "收入",
    },
    {
        "word": "indicate", "pos": "v.",
        "example": "The survey indicates that most students study part-time.",
        "collocations": ["indicate a trend", "clearly indicate", "the figures indicate"],
        "root": "in-(朝向) + dic(說、指, 同 dictate/index/predict) + -ate → 指出來給人看",
        "synonyms": ["show", "suggest", "point to", "signal"],
        "zh": "顯示、指出",
        "notes": "Task 1 的高分替換：The graph indicates… 比 shows 更正式",
    },
    {
        "word": "individual", "pos": "adj.",
        "example": "Online courses can be adapted to individual needs.",
        "collocations": ["individual needs", "an individual choice", "each individual"],
        "root": "in-(不) + divid(分開, 同 divide/division) + -ual → 不能再分下去的",
        "synonyms": ["separate", "personal", "single", "particular"],
        "zh": "個別的",
    },
    {
        "word": "interpret", "pos": "v.",
        "example": "The same figures can be interpreted in two very different ways.",
        "collocations": ["interpret the data", "be interpreted as", "wrongly interpret"],
        "root": "inter-(之間) + pret(交易、價格, 拉丁 pretium) → 在雙方之間居中說明",
        "synonyms": ["explain", "make sense of", "read", "construe"],
        "zh": "解讀",
    },
    {
        "word": "involve", "pos": "v.",
        "example": "The job involves travelling abroad several times a year.",
        "collocations": ["involve risk", "be involved in", "closely involved"],
        "root": "in-(進入) + volv(捲, 同 revolve/evolve/volume 卷軸) → 把事情捲進來",
        "synonyms": ["entail", "include", "require", "draw in"],
        "zh": "牽涉、包含",
    },
    {
        "word": "issue", "pos": "n.",
        "example": "Housing is the issue that voters mention most often.",
        "collocations": ["a key issue", "raise an issue", "address the issue"],
        "root": "拉丁 exire「出去」(ex- 出 + ire 走, 同 exit) → 冒出來要處理的事",
        "synonyms": ["matter", "question", "problem", "topic"],
        "zh": "議題、問題",
    },
    {
        "word": "labour", "pos": "n.",
        "example": "Factories moved abroad in search of cheaper labour.",
        "collocations": ["manual labour", "cheap labour", "the labour market"],
        "root": "拉丁 labor「辛苦、費力」→ 出力氣的工作",
        "synonyms": ["work", "toil", "workforce", "manpower"],
        "zh": "勞動、勞力",
        "notes": "美式拼 labor",
    },
    {
        "word": "legal", "pos": "adj.",
        "example": "Employers have a legal duty to provide safety training.",
        "collocations": ["legal advice", "take legal action", "a legal requirement"],
        "root": "leg(法律, 拉丁 lex/legis, 同 legislate/legitimate) + -al → 法律上的",
        "synonyms": ["lawful", "permitted", "legitimate", "judicial"],
        "zh": "法律的、合法的",
    },
    {
        "word": "legislate", "pos": "v.",
        "example": "Several countries have legislated against single-use plastics.",
        "collocations": ["legislate against", "legislate to protect", "the power to legislate"],
        "root": "leg(法律, 同 legal) + lat(帶來, 同 translate/relate) → 把法律帶出來",
        "synonyms": ["make laws", "pass laws", "enact legislation"],
        "zh": "立法",
    },
    {
        "word": "major", "pos": "adj.",
        "example": "Traffic is a major source of air pollution in the city.",
        "collocations": ["a major factor", "a major change", "play a major role"],
        "root": "拉丁 major「較大的」(同 majority/mayor/maximum) → 比較大的那個",
        "synonyms": ["main", "principal", "significant", "leading"],
        "zh": "主要的",
    },
    {
        "word": "method", "pos": "n.",
        "example": "The study compares two methods of teaching reading.",
        "collocations": ["a teaching method", "a reliable method", "the method used"],
        "root": "meta-(沿著) + hod(路, 希臘 hodos, 同 exodus) → 沿著一條路走的方式",
        "synonyms": ["approach", "technique", "procedure", "way"],
        "zh": "方法",
    },
    {
        "word": "occur", "pos": "v.",
        "example": "Flooding now occurs three times as often as it did in 1980.",
        "collocations": ["occur naturally", "frequently occur", "it occurred to me"],
        "root": "oc-(朝向) + cur(跑, 同 current/recur/course) → 跑過來發生",
        "synonyms": ["happen", "take place", "arise", "come about"],
        "zh": "發生",
        "notes": "拼字陷阱：occurred / occurring 要雙寫 r",
    },
    {
        "word": "percent", "pos": "n.",
        "example": "Almost forty percent of graduates work outside their field.",
        "collocations": ["ten percent of", "a percent increase", "percent of the total"],
        "root": "per(每) + cent(百, 同 century/centimetre) → 每一百當中有幾個",
        "synonyms": ["per cent", "out of a hundred", "proportion"],
        "zh": "百分比",
        "notes": "英式常寫成兩個字 per cent，Task 1 用哪種都行但要一致",
    },
    {
        "word": "period", "pos": "n.",
        "example": "Rainfall was unusually low over the whole period.",
        "collocations": ["over the period", "a long period", "the period shown"],
        "root": "peri-(周圍, 同 perimeter) + od(路, 希臘 hodos) → 繞完一圈的時間",
        "synonyms": ["time", "span", "era", "stretch"],
        "zh": "期間",
    },
    {
        "word": "policy", "pos": "n.",
        "example": "The government reversed its policy on tuition fees.",
        "collocations": ["government policy", "implement a policy", "a policy of"],
        "root": "polis(城邦, 希臘, 同 politics/police/metropolis) → 治理城邦的方針",
        "synonyms": ["strategy", "approach", "guidelines", "course of action"],
        "zh": "政策",
    },
    {
        "word": "principle", "pos": "n.",
        "example": "The design follows one simple principle: nothing is wasted.",
        "collocations": ["in principle", "a guiding principle", "the principle of"],
        "root": "prin(第一, 同 prime/prince) + cip(拿, 同 capture) → 最先要抓住的東西",
        "synonyms": ["rule", "doctrine", "fundamental idea", "tenet"],
        "zh": "原則",
        "notes": "別跟 principal（主要的／校長）搞混",
    },
    {
        "word": "proceed", "pos": "v.",
        "example": "Construction proceeded despite the objections of residents.",
        "collocations": ["proceed with", "proceed to", "the work proceeded"],
        "root": "pro-(向前) + ceed(走, 同 exceed/succeed/process) → 往前走下去",
        "synonyms": ["continue", "go ahead", "carry on", "move on"],
        "zh": "繼續進行",
    },
    {
        "word": "process", "pos": "n.",
        "example": "The application process takes about six weeks.",
        "collocations": ["the whole process", "a lengthy process", "in the process of"],
        "root": "pro-(向前) + cess(走, 同 proceed/access) → 一步步往前走的整段",
        "synonyms": ["procedure", "operation", "course", "method"],
        "zh": "過程",
    },
    {
        "word": "require", "pos": "v.",
        "example": "The course requires no previous knowledge of statistics.",
        "collocations": ["require permission", "be required to", "require attention"],
        "root": "re-(一再) + quir(尋求, 同 question/inquire/conquer) → 反覆去要 → 需要",
        "synonyms": ["need", "demand", "call for", "necessitate"],
        "zh": "需要、要求",
    },
    {
        "word": "research", "pos": "n.",
        "example": "Recent research suggests that short naps improve memory.",
        "collocations": ["conduct research", "extensive research", "research suggests"],
        "root": "re-(一再) + search(尋找) → 一再地找 → 研究",
        "synonyms": ["investigation", "study", "inquiry", "fieldwork"],
        "zh": "研究",
        "notes": "不可數：不能說 a research 或 researches",
    },
    {
        "word": "respond", "pos": "v.",
        "example": "The council responded to complaints by adding more bins.",
        "collocations": ["respond to criticism", "respond quickly", "fail to respond"],
        "root": "re-(回) + spond(承諾、保證, 同 sponsor/correspond) → 回話回去",
        "synonyms": ["reply", "react", "answer", "come back"],
        "zh": "回應",
    },
    {
        "word": "role", "pos": "n.",
        "example": "Grandparents play a much larger role in childcare than before.",
        "collocations": ["play a role", "a key role", "the role of"],
        "root": "原指寫著演員台詞的捲軸(roll) → 所扮演的角色",
        "synonyms": ["part", "function", "position", "capacity"],
        "zh": "角色、作用",
    },
    {
        "word": "section", "pos": "n.",
        "example": "The final section of the report deals with funding.",
        "collocations": ["a section of the report", "a cross-section", "in this section"],
        "root": "sect(切, 同 dissect/insect 被切成節的/sector) + -ion → 切下來的一塊",
        "synonyms": ["part", "segment", "portion", "division"],
        "zh": "部分、章節",
    },
    {
        "word": "sector", "pos": "n.",
        "example": "The service sector now employs three quarters of the workforce.",
        "collocations": ["the public sector", "the private sector", "the service sector"],
        "root": "sect(切) + -or → 從整體切出來的一塊領域",
        "synonyms": ["part", "branch", "area", "division"],
        "zh": "部門、產業",
    },
    {
        "word": "significant", "pos": "adj.",
        "example": "There was a significant fall in road deaths after the limit changed.",
        "collocations": ["a significant increase", "statistically significant", "significant differences"],
        "root": "sign(記號) + fic(做, 同 factory) + -ant → 值得做記號標起來的",
        "synonyms": ["important", "considerable", "notable", "marked"],
        "zh": "顯著的、重要的",
    },
    {
        "word": "similar", "pos": "adj.",
        "example": "The two cities show a similar pattern of population growth.",
        "collocations": ["similar to", "broadly similar", "a similar pattern"],
        "root": "拉丁 similis「像」(同 simulate/assemble/resemble) → 長得像的",
        "synonyms": ["alike", "comparable", "much the same", "parallel"],
        "zh": "相似的",
    },
    {
        "word": "source", "pos": "n.",
        "example": "Coal is still the main source of electricity in the region.",
        "collocations": ["a reliable source", "the main source of", "renewable sources"],
        "root": "拉丁 surgere「湧出」(同 surge/resource/resurrect) → 水湧出來的地方",
        "synonyms": ["origin", "supply", "provider", "root"],
        "zh": "來源",
    },
    {
        "word": "specific", "pos": "adj.",
        "example": "The essay needs specific examples rather than general claims.",
        "collocations": ["a specific example", "be specific about", "specific requirements"],
        "root": "spec(看, 同 species/inspect/spectator) + fic(做) → 做出可辨認外觀的 → 特定的",
        "synonyms": ["particular", "precise", "definite", "exact"],
        "zh": "特定的、具體的",
    },
    {
        "word": "structure", "pos": "n.",
        "example": "The structure of the essay matters as much as its content.",
        "collocations": ["the structure of", "a rigid structure", "sentence structure"],
        "root": "struct(建造, 同 construct/instruct/destroy) + -ure → 建起來的整個樣子",
        "synonyms": ["framework", "organisation", "arrangement", "make-up"],
        "zh": "結構",
    },
    {
        "word": "theory", "pos": "n.",
        "example": "In theory the system works; in practice it rarely does.",
        "collocations": ["in theory", "a theory of", "support a theory"],
        "root": "希臘 theoria「觀看、思索」(同 theatre 看的地方) → 看過之後想出的說法",
        "synonyms": ["hypothesis", "explanation", "model", "principle"],
        "zh": "理論",
    },
    {
        "word": "vary", "pos": "v.",
        "example": "Rents vary widely between districts of the same city.",
        "collocations": ["vary widely", "vary according to", "prices vary"],
        "root": "拉丁 varius「各式各樣」(同 various/variety/variable) → 變得不一樣",
        "synonyms": ["differ", "fluctuate", "range", "change"],
        "zh": "變化、不同",
    },
]

for _entry in SUBLIST_1:
    _entry["category"] = "AWL"
    _entry["topic"] = "Sublist 1"
