"""Task 1 圖表描述用語。

topic 是功能分組（上升／下降／穩定／極值／幅度／比較／比例／綜述），
在 App 裡可以只練「下降」那一組，寫 Task 1 時腦子裡就有一整排替換字。
"""

TASK1 = [
    # ---------------------------------------------------------- 上升
    {
        "word": "soar", "pos": "v.",
        "example": "House prices soared by almost 40 per cent between 2015 and 2020.",
        "collocations": ["soar to a record high", "prices soared", "soaring demand"],
        "root": "古法文 essorer 讓鳥乘風高飛 → 像鳥一樣往上衝",
        "synonyms": ["rocket", "surge", "shoot up", "climb sharply"],
        "category": "Task1圖表用語", "topic": "上升", "zh": "飆升",
        "notes": "只用在幅度很大的上升，小幅上升用 rise / edge up",
    },
    {
        "word": "surge", "pos": "n.",
        "example": "The chart shows a sharp surge in online orders after 2018.",
        "collocations": ["a surge in demand", "a sudden surge", "surge to a peak"],
        "root": "sur-(從下往上) + reg(升起, 同 erect/regent) → 像浪一樣湧上來",
        "synonyms": ["a sharp rise", "a jump", "a leap", "an upswing"],
        "category": "Task1圖表用語", "topic": "上升", "zh": "激增",
    },
    {
        "word": "climb", "pos": "v.",
        "example": "Car ownership climbed steadily throughout the twenty-year period.",
        "collocations": ["climb steadily", "climb to a peak", "figures climbed"],
        "root": "古英語 climban 攀爬 → 一階一階往上",
        "synonyms": ["rise", "increase", "go up", "ascend"],
        "category": "Task1圖表用語", "topic": "上升", "zh": "攀升",
    },
    {
        "word": "escalate", "pos": "v.",
        "example": "Waste production escalated rapidly once the population passed one million.",
        "collocations": ["escalate rapidly", "costs escalated", "escalating figures"],
        "root": "escalator(手扶梯) 的動詞化 → 像手扶梯一樣持續往上",
        "synonyms": ["increase sharply", "mount", "intensify", "spiral"],
        "category": "Task1圖表用語", "topic": "上升", "zh": "急遽上升",
    },
    {
        "word": "edge up", "pos": "phr v.",
        "example": "Unemployment edged up slightly in the final two years of the period.",
        "collocations": ["edge up slightly", "figures edged up", "edge up to"],
        "root": "edge(邊緣) + up → 只往上挪一個邊的距離 → 微幅上升",
        "synonyms": ["rise slightly", "creep up", "inch up"],
        "category": "Task1圖表用語", "topic": "上升", "zh": "微幅上升",
    },

    # ---------------------------------------------------------- 下降
    {
        "word": "plummet", "pos": "v.",
        "example": "Newspaper sales plummeted from 12 million to under 4 million copies.",
        "collocations": ["plummet to a low", "sales plummeted", "plummeting numbers"],
        "root": "plumb(鉛錘, 同 plumber 水管工原本用鉛錘測垂直) → 像鉛錘一樣直直落下",
        "synonyms": ["plunge", "nosedive", "drop sharply", "tumble"],
        "category": "Task1圖表用語", "topic": "下降", "zh": "暴跌",
    },
    {
        "word": "plunge", "pos": "v.",
        "example": "Visitor numbers plunged by half after the border closed.",
        "collocations": ["plunge by half", "plunge to a record low", "a dramatic plunge"],
        "root": "plumb(鉛錘) 的另一支 → 整個人跳進水裡 → 猛然下墜",
        "synonyms": ["plummet", "dive", "fall sharply", "slump"],
        "category": "Task1圖表用語", "topic": "下降", "zh": "驟降",
    },
    {
        "word": "decline", "pos": "n.",
        "example": "There was a steady decline in coal consumption across the whole period.",
        "collocations": ["a steady decline", "a sharp decline", "a decline in numbers"],
        "root": "de-(向下) + clin(傾斜, 同 incline/recline/climate) → 向下傾",
        "synonyms": ["fall", "drop", "decrease", "downturn"],
        "category": "Task1圖表用語", "topic": "下降", "zh": "下降",
        "notes": "名詞動詞都可用；a decline in 後面接名詞",
    },
    {
        "word": "dip", "pos": "v.",
        "example": "Sales dipped briefly in 2012 before recovering the following year.",
        "collocations": ["dip slightly", "a slight dip", "dip below"],
        "root": "古英語 dyppan 浸一下 → 短暫沉下去又起來",
        "synonyms": ["fall slightly", "drop briefly", "ease"],
        "category": "Task1圖表用語", "topic": "下降", "zh": "微幅下滑",
        "notes": "指短暫下降後回升，不是持續下跌",
    },
    {
        "word": "slump", "pos": "n.",
        "example": "The graph shows a slump in manufacturing output during the recession.",
        "collocations": ["a slump in sales", "an economic slump", "slump to a low"],
        "root": "擬聲字，東西「噗通」塌下去的聲音 → 突然垮掉",
        "synonyms": ["sharp fall", "downturn", "collapse", "plunge"],
        "category": "Task1圖表用語", "topic": "下降", "zh": "驟跌、低迷",
    },
    {
        "word": "dwindle", "pos": "v.",
        "example": "Fish stocks dwindled steadily as commercial fishing expanded.",
        "collocations": ["dwindle steadily", "dwindling numbers", "dwindle to almost nothing"],
        "root": "古英語 dwinan 枯萎 → 一點一點縮小到幾乎沒有",
        "synonyms": ["shrink", "diminish", "decrease gradually", "taper off"],
        "category": "Task1圖表用語", "topic": "下降", "zh": "逐漸減少",
    },

    # ---------------------------------------------------------- 穩定
    {
        "word": "plateau", "pos": "v.",
        "example": "After a sharp rise, the figure plateaued at around 60 per cent.",
        "collocations": ["plateau at", "reach a plateau", "plateau after 2010"],
        "root": "法文 plat(平的, 同 plate/plain) → 高原 → 走成平的一段",
        "synonyms": ["level off", "stabilise", "flatten out", "remain steady"],
        "category": "Task1圖表用語", "topic": "穩定", "zh": "趨於平穩",
        "notes": "名詞、動詞都可用；plateau at + 數值",
    },
    {
        "word": "level off", "pos": "phr v.",
        "example": "Energy consumption rose quickly and then levelled off at 90 units.",
        "collocations": ["level off at", "begin to level off", "levelling off"],
        "root": "level(水平) + off → 從斜的走成水平",
        "synonyms": ["plateau", "stabilise", "flatten out", "even out"],
        "category": "Task1圖表用語", "topic": "穩定", "zh": "持平",
    },
    {
        "word": "stabilise", "pos": "v.",
        "example": "Prices stabilised at just under two dollars per litre after 2016.",
        "collocations": ["stabilise at", "prices stabilised", "begin to stabilise"],
        "root": "sta(站立, 同 stand/static/stable) + -ise → 站得住不再晃",
        "synonyms": ["level off", "steady", "remain constant", "settle"],
        "category": "Task1圖表用語", "topic": "穩定", "zh": "趨於穩定",
    },
    {
        "word": "fluctuate", "pos": "v.",
        "example": "Between 2005 and 2010, sales fluctuated between 20 and 35 million units.",
        "collocations": ["fluctuate wildly", "fluctuate between", "figures fluctuated"],
        "root": "flu(流動, 同 fluid/influence/fluent) + -ate → 像水一樣起起伏伏",
        "synonyms": ["vary", "oscillate", "swing", "go up and down"],
        "category": "Task1圖表用語", "topic": "穩定", "zh": "波動、起伏",
        "notes": "描述不規則變化的首選字；fluctuate between A and B",
    },
    {
        "word": "constant", "pos": "adj.",
        "example": "The proportion of rural residents remained constant at 15 per cent.",
        "collocations": ["remain constant", "a constant rate", "constant throughout"],
        "root": "con-(完全) + sta(站立, 同 stand/stable) → 完全站著不動",
        "synonyms": ["steady", "unchanged", "stable", "uniform"],
        "category": "Task1圖表用語", "topic": "穩定", "zh": "不變的",
    },

    # ---------------------------------------------------------- 極值
    {
        "word": "peak", "pos": "v.",
        "example": "Unemployment peaked at 12 per cent in 2009 before falling steadily.",
        "collocations": ["peak at", "reach a peak", "peak in 2009"],
        "root": "peak 山頂 → 圖上的最高點",
        "synonyms": ["reach a maximum", "culminate", "top out", "hit a high"],
        "category": "Task1圖表用語", "topic": "極值", "zh": "達到高峰",
        "notes": "peak at + 數值 / peak in + 年份，介系詞不要搞混",
    },
    {
        "word": "trough", "pos": "n.",
        "example": "The graph reaches a trough of just 5,000 visitors in January.",
        "collocations": ["reach a trough", "a trough of", "the trough of the cycle"],
        "root": "古英語 trog 食槽 → 凹下去的地方 → 谷底",
        "synonyms": ["low point", "bottom", "minimum", "lowest level"],
        "category": "Task1圖表用語", "topic": "極值", "zh": "谷底",
    },
    {
        "word": "bottom out", "pos": "phr v.",
        "example": "Car sales bottomed out in 2013 and then began to recover.",
        "collocations": ["bottom out at", "bottom out in 2013", "finally bottom out"],
        "root": "bottom(底) + out → 走到底了，不會再往下",
        "synonyms": ["reach the lowest point", "hit rock bottom", "stop falling"],
        "category": "Task1圖表用語", "topic": "極值", "zh": "觸底",
    },
    {
        "word": "rebound", "pos": "v.",
        "example": "Tourism rebounded strongly in the two years after the crisis.",
        "collocations": ["rebound strongly", "a sharp rebound", "rebound to"],
        "root": "re-(回) + bound(彈跳, 同 bounce) → 撞到底再彈回來",
        "synonyms": ["recover", "bounce back", "pick up", "revive"],
        "category": "Task1圖表用語", "topic": "極值", "zh": "回升",
    },
    {
        "word": "outstrip", "pos": "v.",
        "example": "Demand for housing outstripped supply throughout the decade.",
        "collocations": ["outstrip supply", "outstrip growth", "far outstrip"],
        "root": "out-(超過) + strip(奔跑, 舊義) → 跑贏對方",
        "synonyms": ["exceed", "surpass", "overtake", "be greater than"],
        "category": "Task1圖表用語", "topic": "極值", "zh": "超過、勝過",
    },

    # ---------------------------------------------------------- 幅度
    {
        "word": "steadily", "pos": "adv.",
        "example": "The number of graduates rose steadily from 2000 to 2015.",
        "collocations": ["rise steadily", "steadily increase", "grow steadily"],
        "root": "stead(位置, 同 instead/homestead) + -y + -ly → 一直待在同一個節奏",
        "synonyms": ["consistently", "gradually", "progressively", "at a constant rate"],
        "category": "Task1圖表用語", "topic": "幅度", "zh": "穩定地",
    },
    {
        "word": "dramatically", "pos": "adv.",
        "example": "Internet use grew dramatically after broadband became affordable.",
        "collocations": ["rise dramatically", "fall dramatically", "change dramatically"],
        "root": "drama(戲劇, 希臘 dran 行動) + -ic + -ally → 像戲劇一樣誇張",
        "synonyms": ["sharply", "markedly", "significantly", "strikingly"],
        "category": "Task1圖表用語", "topic": "幅度", "zh": "劇烈地",
    },
    {
        "word": "marginally", "pos": "adv.",
        "example": "Spending on transport increased only marginally over the period.",
        "collocations": ["increase marginally", "marginally higher", "differ marginally"],
        "root": "margin(邊緣, 同 margin 頁邊) + -al + -ly → 只在邊緣動一點點",
        "synonyms": ["slightly", "fractionally", "a little", "minimally"],
        "category": "Task1圖表用語", "topic": "幅度", "zh": "微幅地",
    },
    {
        "word": "considerably", "pos": "adv.",
        "example": "Figures for the two cities differ considerably in the second half of the period.",
        "collocations": ["rise considerably", "considerably higher", "vary considerably"],
        "root": "con-(完全) + sider(星星, 原指觀星占卜 → 仔細考量) + -ably → 值得注意的程度",
        "synonyms": ["significantly", "substantially", "markedly", "greatly"],
        "category": "Task1圖表用語", "topic": "幅度", "zh": "相當大幅地",
    },
    {
        "word": "gradual", "pos": "adj.",
        "example": "The chart shows a gradual shift from coal to renewable sources.",
        "collocations": ["a gradual increase", "a gradual decline", "a gradual shift"],
        "root": "grad(步伐, 同 grade/graduate/progress) + -ual → 一步一步來的",
        "synonyms": ["steady", "progressive", "slow", "incremental"],
        "category": "Task1圖表用語", "topic": "幅度", "zh": "逐漸的",
    },
    {
        "word": "approximately", "pos": "adv.",
        "example": "Approximately one in five households owned two or more cars.",
        "collocations": ["approximately half", "approximately 20 per cent", "approximately equal"],
        "root": "ad-(接近) + proxim(最近的, 同 proximity/approach) + -ate + -ly → 靠近某個數",
        "synonyms": ["roughly", "about", "around", "in the region of"],
        "category": "Task1圖表用語", "topic": "幅度", "zh": "大約",
    },

    # ---------------------------------------------------------- 比較
    {
        "word": "respectively", "pos": "adv.",
        "example": "Spending on housing and transport rose to 30 and 18 per cent respectively.",
        "collocations": ["A and B respectively", "rose to X and Y respectively"],
        "root": "re-(回) + spect(看, 同 inspect/respect/spectator) + -ive + -ly → 各自回頭對應著看",
        "synonyms": ["in that order", "correspondingly"],
        "category": "Task1圖表用語", "topic": "比較", "zh": "分別地",
        "notes": "放句尾，讓兩組數據一次講完",
    },
    {
        "word": "whereas", "pos": "conj.",
        "example": "Sales in Europe fell, whereas the figure for Asia more than doubled.",
        "collocations": ["X rose whereas Y fell", "whereas the figure for"],
        "root": "where(在何處) + as(如同) → 「相對於某處的情況」→ 對比連接詞",
        "synonyms": ["while", "by contrast", "on the other hand"],
        "category": "Task1圖表用語", "topic": "比較", "zh": "然而、相對地",
    },
    {
        "word": "overtake", "pos": "v.",
        "example": "Online sales overtook high-street sales for the first time in 2019.",
        "collocations": ["overtake sales of", "overtake in 2019", "eventually overtake"],
        "root": "over-(越過) + take → 從後面追上去越過",
        "synonyms": ["surpass", "exceed", "outstrip", "pass"],
        "category": "Task1圖表用語", "topic": "比較", "zh": "超越",
    },
    {
        "word": "outnumber", "pos": "v.",
        "example": "Male graduates outnumbered female graduates by roughly two to one.",
        "collocations": ["outnumber by two to one", "far outnumber", "outnumber the rest"],
        "root": "out-(超過) + number → 數量壓過對方",
        "synonyms": ["exceed in number", "be more numerous than", "surpass"],
        "category": "Task1圖表用語", "topic": "比較", "zh": "數量超過",
    },
    {
        "word": "double", "pos": "v.",
        "example": "The number of international students doubled over the twenty-year period.",
        "collocations": ["double in size", "more than double", "double over the period"],
        "root": "du(二, 同 dual/duo/duet) + -ble → 變成兩份",
        "synonyms": ["increase twofold", "grow by 100 per cent", "multiply by two"],
        "category": "Task1圖表用語", "topic": "比較", "zh": "加倍",
    },
    {
        "word": "halve", "pos": "v.",
        "example": "Carbon emissions from transport halved between 2010 and 2030.",
        "collocations": ["halve in a decade", "almost halve", "halve the figure"],
        "root": "half 的動詞形 → 切成一半",
        "synonyms": ["fall by half", "be cut in half", "drop 50 per cent"],
        "category": "Task1圖表用語", "topic": "比較", "zh": "減半",
    },

    # ---------------------------------------------------------- 比例
    {
        "word": "account for", "pos": "phr v.",
        "example": "Renewable sources accounted for just under a third of total output.",
        "collocations": ["account for 30 per cent", "account for the majority", "collectively account for"],
        "root": "account(計算, 同 count) + for → 算一算佔了多少",
        "synonyms": ["make up", "constitute", "represent", "comprise"],
        "category": "Task1圖表用語", "topic": "比例", "zh": "佔（比例）",
        "notes": "Task 1 講圓餅圖比例最常用的動詞",
    },
    {
        "word": "proportion", "pos": "n.",
        "example": "A large proportion of household waste was sent to landfill.",
        "collocations": ["a large proportion of", "the proportion of", "in proportion to"],
        "root": "pro-(向前) + portion(份, 同 part/portion) → 分出來的那一份",
        "synonyms": ["share", "percentage", "fraction", "ratio"],
        "category": "Task1圖表用語", "topic": "比例", "zh": "比例",
    },
    {
        "word": "figure", "pos": "n.",
        "example": "The figure for private car use rose faster than any other category.",
        "collocations": ["the figure for", "figures rose", "the corresponding figure"],
        "root": "fig(塑形, 同 figure 形狀/configure) → 呈現出來的形 → 數字",
        "synonyms": ["number", "statistic", "level", "amount"],
        "category": "Task1圖表用語", "topic": "比例", "zh": "數字、數據",
        "notes": "the figure for X 是避免重複 the number of X 的標準替換",
    },

    # ---------------------------------------------------------- 綜述
    {
        "word": "overall", "pos": "adv.",
        "example": "Overall, the three countries followed very similar trends.",
        "collocations": ["overall, the trend", "the overall figure", "an overall increase"],
        "root": "over(蓋過) + all(全部) → 蓋過全部來看",
        "synonyms": ["in general", "on the whole", "broadly", "taken as a whole"],
        "category": "Task1圖表用語", "topic": "綜述", "zh": "整體而言",
        "notes": "Overview 段落的起手式",
    },
    {
        "word": "throughout", "pos": "prep.",
        "example": "Demand for water remained high throughout the period shown.",
        "collocations": ["throughout the period", "throughout the decade", "stable throughout"],
        "root": "through(穿過) + out(到底) → 從頭穿到尾",
        "synonyms": ["for the whole period", "during the entire", "across"],
        "category": "Task1圖表用語", "topic": "綜述", "zh": "整段期間",
    },
    {
        "word": "witness", "pos": "v.",
        "example": "The final decade witnessed a rapid expansion in solar capacity.",
        "collocations": ["the period witnessed", "the city witnessed growth", "witness a rise"],
        "root": "wit(知道, 同 wit/wisdom) + -ness → 親眼見到 → 某段期間「出現了」某變化",
        "synonyms": ["see", "experience", "undergo", "record"],
        "category": "Task1圖表用語", "topic": "綜述", "zh": "（某期間）出現",
        "notes": "把時間當主詞：The 1990s witnessed... 讓句型不再都是 X rose",
    },
]
