"""高頻話題字：環境、教育、科技（每個主題 20 字）。"""

TOPICS_A = [
    # ==================================================== 環境
    {
        "word": "mitigate", "pos": "v.",
        "example": "Governments must act now to mitigate the effects of climate change.",
        "collocations": ["mitigate the effects", "mitigate the impact", "mitigate risk"],
        "root": "mit(緩和、變柔軟, 同 mild) + -igate(使…) → 使變柔和",
        "synonyms": ["alleviate", "reduce", "ease", "lessen"],
        "category": "高頻話題字", "topic": "環境", "zh": "減輕、緩和",
    },
    {
        "word": "sustainable", "pos": "adj.",
        "example": "Cities need sustainable transport systems that do not rely on private cars.",
        "collocations": ["sustainable development", "sustainable growth", "environmentally sustainable"],
        "root": "sus-(在下) + tain(持有, 同 contain/retain/maintain) + -able → 在底下撐得住的",
        "synonyms": ["viable", "enduring", "long-term", "environmentally sound"],
        "category": "高頻話題字", "topic": "環境", "zh": "可持續的",
    },
    {
        "word": "renewable", "pos": "adj.",
        "example": "Denmark now generates over half its electricity from renewable sources.",
        "collocations": ["renewable energy", "renewable sources", "shift to renewables"],
        "root": "re-(再) + new(新) + -able → 可以一再變新的",
        "synonyms": ["sustainable", "clean", "green", "inexhaustible"],
        "category": "高頻話題字", "topic": "環境", "zh": "可再生的",
    },
    {
        "word": "emission", "pos": "n.",
        "example": "Carbon emissions from road transport fell for the third year running.",
        "collocations": ["carbon emissions", "cut emissions", "greenhouse gas emissions"],
        "root": "e-(出去) + miss(送, 同 mission/transmit/dismiss) + -ion → 送出去的東西",
        "synonyms": ["discharge", "release", "output", "fumes"],
        "category": "高頻話題字", "topic": "環境", "zh": "排放（物）",
    },
    {
        "word": "carbon footprint", "pos": "n. phr.",
        "example": "Flying less is the fastest way to shrink your carbon footprint.",
        "collocations": ["reduce your carbon footprint", "a large carbon footprint", "measure the carbon footprint"],
        "root": "footprint(腳印) → 你踩在地球上留下的碳的印子",
        "synonyms": ["carbon impact", "emissions total", "environmental impact"],
        "category": "高頻話題字", "topic": "環境", "zh": "碳足跡",
    },
    {
        "word": "greenhouse gas", "pos": "n. phr.",
        "example": "Methane is a greenhouse gas far more potent than carbon dioxide.",
        "collocations": ["greenhouse gas emissions", "cut greenhouse gases", "a greenhouse gas effect"],
        "root": "greenhouse(溫室) → 像溫室玻璃一樣把熱關在裡面的氣體",
        "synonyms": ["heat-trapping gas", "carbon emissions"],
        "category": "高頻話題字", "topic": "環境", "zh": "溫室氣體",
    },
    {
        "word": "deforestation", "pos": "n.",
        "example": "Large-scale deforestation has destroyed much of the region's rainforest.",
        "collocations": ["large-scale deforestation", "tackle deforestation", "rates of deforestation"],
        "root": "de-(去除) + forest(森林) + -ation → 把森林去掉這件事",
        "synonyms": ["forest clearance", "logging", "tree loss"],
        "category": "高頻話題字", "topic": "環境", "zh": "森林砍伐",
    },
    {
        "word": "biodiversity", "pos": "n.",
        "example": "Wetlands support far greater biodiversity than most people realise.",
        "collocations": ["protect biodiversity", "loss of biodiversity", "rich biodiversity"],
        "root": "bio(生命, 同 biology) + divers(不同, 同 diverse/diversity) → 生命的多樣性",
        "synonyms": ["variety of species", "ecological diversity", "wildlife variety"],
        "category": "高頻話題字", "topic": "環境", "zh": "生物多樣性",
    },
    {
        "word": "landfill", "pos": "n.",
        "example": "Nearly half of all household waste still ends up in landfill.",
        "collocations": ["end up in landfill", "landfill sites", "reduce landfill waste"],
        "root": "land(土地) + fill(填) → 挖坑把垃圾填進土地",
        "synonyms": ["waste site", "dump", "tip", "rubbish site"],
        "category": "高頻話題字", "topic": "環境", "zh": "垃圾掩埋場",
    },
    {
        "word": "conservation", "pos": "n.",
        "example": "Conservation groups have campaigned for the forest to be protected.",
        "collocations": ["wildlife conservation", "energy conservation", "conservation efforts"],
        "root": "con-(一起) + serv(保存, 同 preserve/reserve/observe) + -ation → 一起守住",
        "synonyms": ["protection", "preservation", "safeguarding"],
        "category": "高頻話題字", "topic": "環境", "zh": "保育、保護",
    },
    {
        "word": "habitat", "pos": "n.",
        "example": "Road building has destroyed the natural habitat of several rare species.",
        "collocations": ["natural habitat", "habitat loss", "destroy habitats"],
        "root": "拉丁 habitare 居住（同 inhabit/habit） → 生物居住的地方",
        "synonyms": ["natural environment", "home range", "natural surroundings"],
        "category": "高頻話題字", "topic": "環境", "zh": "棲息地",
    },
    {
        "word": "pollutant", "pos": "n.",
        "example": "Traffic releases pollutants that damage children's developing lungs.",
        "collocations": ["airborne pollutants", "industrial pollutants", "release pollutants"],
        "root": "拉丁 polluere 弄髒（同 pollution） + -ant(做…的東西) → 弄髒環境的東西",
        "synonyms": ["contaminant", "toxin", "impurity"],
        "category": "高頻話題字", "topic": "環境", "zh": "污染物",
    },
    {
        "word": "depletion", "pos": "n.",
        "example": "The depletion of groundwater has forced farmers to change what they grow.",
        "collocations": ["resource depletion", "ozone depletion", "the depletion of stocks"],
        "root": "de-(去除) + plet(填滿, 同 complete/replete) + -ion → 把填滿的東西掏空",
        "synonyms": ["exhaustion", "using up", "reduction", "draining"],
        "category": "高頻話題字", "topic": "環境", "zh": "耗竭",
    },
    {
        "word": "ecosystem", "pos": "n.",
        "example": "Coral reefs are among the most fragile ecosystems on the planet.",
        "collocations": ["a fragile ecosystem", "damage ecosystems", "marine ecosystems"],
        "root": "eco(家, 希臘 oikos, 同 economy) + system → 生物的「家」這整套系統",
        "synonyms": ["natural system", "biological community", "habitat network"],
        "category": "高頻話題字", "topic": "環境", "zh": "生態系",
    },
    {
        "word": "degradation", "pos": "n.",
        "example": "Environmental degradation is hardest to reverse in poorer regions.",
        "collocations": ["environmental degradation", "soil degradation", "land degradation"],
        "root": "de-(向下) + grad(階, 同 grade/gradual/degree) + -ation → 一階一階降下去",
        "synonyms": ["deterioration", "damage", "decline", "worsening"],
        "category": "高頻話題字", "topic": "環境", "zh": "惡化、退化",
    },
    {
        "word": "contaminate", "pos": "v.",
        "example": "Industrial waste has contaminated the river for several kilometres.",
        "collocations": ["contaminate water supplies", "heavily contaminated", "contaminate the soil"],
        "root": "con-(一起) + tamin(接觸, 同 contact/contagion) + -ate → 碰到而變髒",
        "synonyms": ["pollute", "taint", "poison", "infect"],
        "category": "高頻話題字", "topic": "環境", "zh": "污染",
    },
    {
        "word": "extinction", "pos": "n.",
        "example": "Several bird species now face extinction within a single generation.",
        "collocations": ["face extinction", "on the brink of extinction", "mass extinction"],
        "root": "ex-(完全) + stinct(熄滅, 同 distinguish/instinct) + -ion → 整個熄掉不再有",
        "synonyms": ["dying out", "disappearance", "eradication"],
        "category": "高頻話題字", "topic": "環境", "zh": "滅絕",
    },
    {
        "word": "drought", "pos": "n.",
        "example": "A prolonged drought left reservoirs at a third of their normal level.",
        "collocations": ["a severe drought", "prolonged drought", "drought-hit areas"],
        "root": "古英語 drugath「乾」（同 dry） + -th(狀態) → 乾的狀態",
        "synonyms": ["water shortage", "dry spell", "arid conditions"],
        "category": "高頻話題字", "topic": "環境", "zh": "乾旱",
    },
    {
        "word": "erosion", "pos": "n.",
        "example": "Coastal erosion has washed away nearly ten metres of cliff since 1990.",
        "collocations": ["soil erosion", "coastal erosion", "prevent erosion"],
        "root": "e-(出去) + ros/rod(啃, 同 rodent 齧齒類/corrode) + -ion → 一點一點被啃掉",
        "synonyms": ["wearing away", "gradual loss", "wearing down"],
        "category": "高頻話題字", "topic": "環境", "zh": "侵蝕",
    },
    {
        "word": "curb", "pos": "v.",
        "example": "The city introduced a congestion charge to curb traffic in the centre.",
        "collocations": ["curb emissions", "curb pollution", "curb the use of"],
        "root": "curb 原指馬勒的鍊條 → 拉住不讓牠亂跑",
        "synonyms": ["restrict", "limit", "rein in", "check"],
        "category": "高頻話題字", "topic": "環境", "zh": "抑制",
    },

    # ==================================================== 教育
    {
        "word": "curriculum", "pos": "n.",
        "example": "Financial literacy should be part of the national curriculum.",
        "collocations": ["the school curriculum", "curriculum design", "a core curriculum"],
        "root": "curr(跑, 同 current/occur/course) + -iculum → 要跑完的一段路程 → 課程",
        "synonyms": ["syllabus", "course of study", "programme"],
        "category": "高頻話題字", "topic": "教育", "zh": "課程（總體）",
        "notes": "複數是 curricula",
    },
    {
        "word": "substantial", "pos": "adj.",
        "example": "There has been a substantial increase in tuition fees over the past decade.",
        "collocations": ["a substantial increase", "substantial evidence", "a substantial amount of"],
        "root": "sub-(在下) + stant(站立, 同 stand/constant) + -ial → 站得住腳的 → 有實質分量的",
        "synonyms": ["considerable", "significant", "sizeable", "marked"],
        "category": "高頻話題字", "topic": "教育", "zh": "大量的、實質的",
    },
    {
        "word": "literacy", "pos": "n.",
        "example": "Adult literacy rates have risen sharply since the programme began.",
        "collocations": ["adult literacy", "literacy rates", "financial literacy"],
        "root": "liter(字母, 同 letter/literature) + -acy → 認得字的能力",
        "synonyms": ["reading ability", "being able to read and write"],
        "category": "高頻話題字", "topic": "教育", "zh": "識字能力、素養",
        "notes": "digital literacy / financial literacy 都是高分搭配",
    },
    {
        "word": "numeracy", "pos": "n.",
        "example": "Employers complain that basic numeracy is weaker than it used to be.",
        "collocations": ["basic numeracy", "numeracy skills", "literacy and numeracy"],
        "root": "numer(數字, 同 number/numerous) + -acy → 處理數字的能力",
        "synonyms": ["mathematical ability", "number skills"],
        "category": "高頻話題字", "topic": "教育", "zh": "算術能力",
    },
    {
        "word": "tuition", "pos": "n.",
        "example": "Tuition fees have tripled since the system was reformed.",
        "collocations": ["tuition fees", "pay tuition", "private tuition"],
        "root": "tuit(照看, 同 tutor/intuition) + -ion → 被看顧著教導",
        "synonyms": ["teaching", "instruction", "course fees"],
        "category": "高頻話題字", "topic": "教育", "zh": "學費、教學",
    },
    {
        "word": "scholarship", "pos": "n.",
        "example": "She won a full scholarship to study engineering abroad.",
        "collocations": ["win a scholarship", "a full scholarship", "apply for scholarships"],
        "root": "schol(學校, 希臘 skholē 原意「閒暇」→ 有閒暇才能學習) + -ship → 學者的身分／補助",
        "synonyms": ["grant", "bursary", "financial award"],
        "category": "高頻話題字", "topic": "教育", "zh": "獎學金",
    },
    {
        "word": "vocational", "pos": "adj.",
        "example": "Vocational training often leads to work faster than an academic degree.",
        "collocations": ["vocational training", "vocational courses", "vocational qualifications"],
        "root": "voc(呼喚, 同 voice/vocation 天職) + -ation + -al → 為了「天職」而做的訓練",
        "synonyms": ["job-related", "occupational", "practical", "career-focused"],
        "category": "高頻話題字", "topic": "教育", "zh": "職業的、技職的",
    },
    {
        "word": "rote learning", "pos": "n. phr.",
        "example": "Rote learning helps with exams but rarely produces real understanding.",
        "collocations": ["rely on rote learning", "rote learning of facts", "move away from rote learning"],
        "root": "rote 原意「固定的路線」→ 照著固定套路死記",
        "synonyms": ["memorisation", "learning by heart", "mechanical learning"],
        "category": "高頻話題字", "topic": "教育", "zh": "死記硬背",
    },
    {
        "word": "critical thinking", "pos": "n. phr.",
        "example": "Group debates are one of the best ways to develop critical thinking.",
        "collocations": ["develop critical thinking", "critical thinking skills", "encourage critical thinking"],
        "root": "crit(判斷, 同 criterion/critic/crisis) → 會判斷的思考",
        "synonyms": ["analytical thinking", "reasoning", "independent thought"],
        "category": "高頻話題字", "topic": "教育", "zh": "批判性思考",
    },
    {
        "word": "assessment", "pos": "n.",
        "example": "Continuous assessment reduces the pressure of a single final exam.",
        "collocations": ["continuous assessment", "formal assessment", "assessment criteria"],
        "root": "as-(朝向) + sess(坐, 同 session/sedentary；法官「坐下來」評定稅額) + -ment → 坐下來評定",
        "synonyms": ["evaluation", "appraisal", "testing", "marking"],
        "category": "高頻話題字", "topic": "教育", "zh": "評量",
    },
    {
        "word": "enrol", "pos": "v.",
        "example": "Over four thousand students enrolled in online courses last year.",
        "collocations": ["enrol in a course", "enrol students", "enrolment rates"],
        "root": "en-(進入) + rol(名冊, 同 roll 卷軸) → 把名字寫進名冊",
        "synonyms": ["sign up", "register", "enter", "join"],
        "category": "高頻話題字", "topic": "教育", "zh": "註冊、入學",
    },
    {
        "word": "dropout rate", "pos": "n. phr.",
        "example": "The dropout rate fell once the university introduced study mentors.",
        "collocations": ["a high dropout rate", "reduce the dropout rate", "the dropout rate among"],
        "root": "drop(掉落) + out → 中途掉出隊伍的比例",
        "synonyms": ["attrition rate", "withdrawal rate", "leaving rate"],
        "category": "高頻話題字", "topic": "教育", "zh": "輟學率",
    },
    {
        "word": "discipline", "pos": "n.",
        "example": "Classroom discipline suffers when classes are too large.",
        "collocations": ["classroom discipline", "strict discipline", "self-discipline"],
        "root": "disc(學習, 同 disciple 門徒/docile) + -ine → 學習該有的規矩",
        "synonyms": ["order", "self-control", "behaviour management"],
        "category": "高頻話題字", "topic": "教育", "zh": "紀律、自律",
        "notes": "另一個意思是「學科」：an academic discipline",
    },
    {
        "word": "extracurricular", "pos": "adj.",
        "example": "Extracurricular activities matter as much as grades on an application.",
        "collocations": ["extracurricular activities", "extracurricular clubs", "take part in extracurricular"],
        "root": "extra-(之外, 同 extraordinary) + curricul(課程) + -ar → 正課之外的",
        "synonyms": ["out-of-class", "after-school", "non-academic"],
        "category": "高頻話題字", "topic": "教育", "zh": "課外的",
    },
    {
        "word": "peer pressure", "pos": "n. phr.",
        "example": "Teenagers often start smoking because of peer pressure rather than curiosity.",
        "collocations": ["under peer pressure", "resist peer pressure", "intense peer pressure"],
        "root": "peer(同輩, 拉丁 par 相等, 同 pair/par) → 同輩之間的壓力",
        "synonyms": ["social pressure", "group influence"],
        "category": "高頻話題字", "topic": "教育", "zh": "同儕壓力",
    },
    {
        "word": "mentor", "pos": "n.",
        "example": "Every first-year student is assigned a mentor from the year above.",
        "collocations": ["act as a mentor", "a mentor programme", "assign a mentor"],
        "root": "源自《奧德賽》裡受託教導主角兒子的人物 Mentor → 引路人",
        "synonyms": ["adviser", "guide", "coach", "tutor"],
        "category": "高頻話題字", "topic": "教育", "zh": "導師、引路人",
    },
    {
        "word": "plagiarism", "pos": "n.",
        "example": "Universities now use software to detect plagiarism in essays.",
        "collocations": ["accused of plagiarism", "avoid plagiarism", "plagiarism detection"],
        "root": "拉丁 plagiarius「綁架者」→ 把別人的東西擄走當自己的",
        "synonyms": ["copying", "academic dishonesty", "intellectual theft"],
        "category": "高頻話題字", "topic": "教育", "zh": "抄襲",
    },
    {
        "word": "truancy", "pos": "n.",
        "example": "Truancy fell after the school introduced later start times.",
        "collocations": ["reduce truancy", "truancy rates", "persistent truancy"],
        "root": "truant(遊蕩者, 古法文 truant 乞丐) + -cy → 該上學卻在外面晃",
        "synonyms": ["skipping school", "absenteeism", "unauthorised absence"],
        "category": "高頻話題字", "topic": "教育", "zh": "曠課",
    },
    {
        "word": "lifelong learning", "pos": "n. phr.",
        "example": "Rapid changes at work make lifelong learning a necessity rather than a choice.",
        "collocations": ["promote lifelong learning", "a culture of lifelong learning", "commit to lifelong learning"],
        "root": "life(一生) + long(那麼長) → 學習持續一輩子",
        "synonyms": ["continuous education", "ongoing study", "adult learning"],
        "category": "高頻話題字", "topic": "教育", "zh": "終身學習",
    },
    {
        "word": "attainment", "pos": "n.",
        "example": "Educational attainment still depends heavily on family income.",
        "collocations": ["educational attainment", "attainment levels", "raise attainment"],
        "root": "at-(朝向) + tain(持有, 同 contain/maintain/obtain) + -ment → 伸手拿到的程度",
        "synonyms": ["achievement", "accomplishment", "performance"],
        "category": "高頻話題字", "topic": "教育", "zh": "學習成就",
    },

    # ==================================================== 科技
    {
        "word": "automation", "pos": "n.",
        "example": "Automation has replaced many routine tasks in warehouses.",
        "collocations": ["increasing automation", "workplace automation", "the automation of tasks"],
        "root": "auto(自己, 同 automatic/autonomy) + mat(動, 同 automaton) + -ion → 自己會動",
        "synonyms": ["mechanisation", "computerisation", "robotisation"],
        "category": "高頻話題字", "topic": "科技", "zh": "自動化",
    },
    {
        "word": "algorithm", "pos": "n.",
        "example": "The recommendation algorithm decides what most users see first.",
        "collocations": ["a recommendation algorithm", "tweak the algorithm", "algorithms decide"],
        "root": "源自波斯數學家 al-Khwārizmī 的名字拉丁化 → 一套計算步驟",
        "synonyms": ["procedure", "formula", "set of rules"],
        "category": "高頻話題字", "topic": "科技", "zh": "演算法",
    },
    {
        "word": "artificial intelligence", "pos": "n. phr.",
        "example": "Artificial intelligence is already used to screen job applications.",
        "collocations": ["advances in artificial intelligence", "regulate artificial intelligence", "artificial intelligence systems"],
        "root": "arti(技藝, 同 art/artisan) + fic(製造, 同 factory/fiction) → 人造的 + 智能",
        "synonyms": ["AI", "machine intelligence", "computer intelligence"],
        "category": "高頻話題字", "topic": "科技", "zh": "人工智慧",
    },
    {
        "word": "cybersecurity", "pos": "n.",
        "example": "Hospitals have had to invest heavily in cybersecurity after recent attacks.",
        "collocations": ["invest in cybersecurity", "a cybersecurity breach", "cybersecurity measures"],
        "root": "cyber(控制, 希臘 kybernan 掌舵, 同 govern) + security → 網路空間的防護",
        "synonyms": ["online security", "information security", "data protection"],
        "category": "高頻話題字", "topic": "科技", "zh": "網路資安",
    },
    {
        "word": "innovation", "pos": "n.",
        "example": "Tax breaks are meant to encourage innovation in small firms.",
        "collocations": ["technological innovation", "drive innovation", "a major innovation"],
        "root": "in-(進入) + nov(新, 同 novel/novice/renew) + -ation → 把新東西帶進來",
        "synonyms": ["breakthrough", "advance", "new development"],
        "category": "高頻話題字", "topic": "科技", "zh": "創新",
    },
    {
        "word": "obsolete", "pos": "adj.",
        "example": "Video rental shops became obsolete almost overnight.",
        "collocations": ["become obsolete", "technically obsolete", "render obsolete"],
        "root": "ob-(離開) + sol(習慣, 拉丁 solere) → 不再被使用習慣留著 → 過時",
        "synonyms": ["outdated", "out of date", "superseded", "no longer used"],
        "category": "高頻話題字", "topic": "科技", "zh": "過時的、淘汰的",
    },
    {
        "word": "screen time", "pos": "n. phr.",
        "example": "Parents are often advised to limit screen time before bed.",
        "collocations": ["limit screen time", "excessive screen time", "daily screen time"],
        "root": "screen(螢幕) + time → 盯著螢幕的時間",
        "synonyms": ["time spent on devices", "device use"],
        "category": "高頻話題字", "topic": "科技", "zh": "螢幕使用時間",
    },
    {
        "word": "misinformation", "pos": "n.",
        "example": "Health misinformation spreads faster than corrections ever do.",
        "collocations": ["spread misinformation", "combat misinformation", "online misinformation"],
        "root": "mis-(錯誤, 同 mistake/misuse) + information → 錯的資訊",
        "synonyms": ["false information", "fake news", "inaccurate claims"],
        "category": "高頻話題字", "topic": "科技", "zh": "錯誤資訊",
    },
    {
        "word": "encryption", "pos": "n.",
        "example": "End-to-end encryption means the provider cannot read your messages.",
        "collocations": ["end-to-end encryption", "strong encryption", "encryption keys"],
        "root": "en-(進入) + crypt(隱藏, 同 cryptic/crypt 地窖) + -ion → 把訊息藏起來",
        "synonyms": ["encoding", "scrambling", "cipher protection"],
        "category": "高頻話題字", "topic": "科技", "zh": "加密",
    },
    {
        "word": "digital divide", "pos": "n. phr.",
        "example": "The pandemic exposed a digital divide between urban and rural pupils.",
        "collocations": ["bridge the digital divide", "widen the digital divide", "a growing digital divide"],
        "root": "divide(分開, 同 division) → 數位科技造成的一道裂縫",
        "synonyms": ["technology gap", "access inequality", "digital gap"],
        "category": "高頻話題字", "topic": "科技", "zh": "數位落差",
    },
    {
        "word": "user-friendly", "pos": "adj.",
        "example": "The app succeeded because its interface was genuinely user-friendly.",
        "collocations": ["a user-friendly interface", "make it more user-friendly", "user-friendly design"],
        "root": "user(使用者) + friendly(友善) → 對使用者友善的",
        "synonyms": ["easy to use", "intuitive", "accessible", "straightforward"],
        "category": "高頻話題字", "topic": "科技", "zh": "容易上手的",
    },
    {
        "word": "streamline", "pos": "v.",
        "example": "Digital forms have streamlined the whole application process.",
        "collocations": ["streamline the process", "streamline operations", "streamline procedures"],
        "root": "stream(水流) + line(線) → 做成水流的形狀 → 去掉阻力",
        "synonyms": ["simplify", "make more efficient", "rationalise"],
        "category": "高頻話題字", "topic": "科技", "zh": "簡化流程",
    },
    {
        "word": "disrupt", "pos": "v.",
        "example": "Streaming services disrupted the film industry within a decade.",
        "collocations": ["disrupt an industry", "disruptive technology", "disrupt traditional retail"],
        "root": "dis-(分開) + rupt(破裂, 同 rupture/interrupt/erupt) → 把原本的樣子打破",
        "synonyms": ["upend", "transform", "shake up", "overturn"],
        "category": "高頻話題字", "topic": "科技", "zh": "顛覆、打亂",
    },
    {
        "word": "breakthrough", "pos": "n.",
        "example": "Cheap battery storage was the breakthrough that made solar power viable.",
        "collocations": ["a major breakthrough", "a scientific breakthrough", "achieve a breakthrough"],
        "root": "break(打破) + through(穿過) → 突破一道擋牆",
        "synonyms": ["major advance", "leap forward", "milestone", "development"],
        "category": "高頻話題字", "topic": "科技", "zh": "突破",
    },
    {
        "word": "prototype", "pos": "n.",
        "example": "The team built a working prototype in under three months.",
        "collocations": ["build a prototype", "an early prototype", "test a prototype"],
        "root": "proto(最初, 同 protocol/protagonist) + type(型) → 最初的那個型",
        "synonyms": ["model", "first version", "trial design"],
        "category": "高頻話題字", "topic": "科技", "zh": "原型",
    },
    {
        "word": "redundant", "pos": "adj.",
        "example": "Automation has made several checking jobs redundant.",
        "collocations": ["make workers redundant", "become redundant", "a redundant system"],
        "root": "red-(回) + und(波浪, 同 abundant/inundate) + -ant → 一波波多出來 → 多餘",
        "synonyms": ["unnecessary", "superfluous", "surplus", "no longer needed"],
        "category": "高頻話題字", "topic": "科技", "zh": "多餘的、被裁的",
    },
    {
        "word": "connectivity", "pos": "n.",
        "example": "Poor connectivity still limits what rural schools can offer.",
        "collocations": ["internet connectivity", "poor connectivity", "global connectivity"],
        "root": "con-(一起) + nect(綁, 同 connect/annex) + -ivity → 綁在一起的程度",
        "synonyms": ["network access", "internet access", "linkage"],
        "category": "高頻話題字", "topic": "科技", "zh": "連線能力",
    },
    {
        "word": "reliance", "pos": "n.",
        "example": "Our reliance on a single search engine worries competition regulators.",
        "collocations": ["heavy reliance on", "growing reliance", "reduce reliance on"],
        "root": "re-(回) + li(綁, 同 rely/ligament/liable) + -ance → 把自己綁回去靠著",
        "synonyms": ["dependence", "dependency", "need for"],
        "category": "高頻話題字", "topic": "科技", "zh": "依賴",
    },
    {
        "word": "upgrade", "pos": "v.",
        "example": "Users are pushed to upgrade their phones long before they stop working.",
        "collocations": ["upgrade a system", "upgrade to a newer model", "a free upgrade"],
        "root": "up(向上) + grade(等級, 同 gradual/degree) → 往上換一個等級",
        "synonyms": ["improve", "modernise", "update", "enhance"],
        "category": "高頻話題字", "topic": "科技", "zh": "升級",
    },
    {
        "word": "cutting-edge", "pos": "adj.",
        "example": "The hospital uses cutting-edge imaging equipment to detect tumours early.",
        "collocations": ["cutting-edge technology", "cutting-edge research", "at the cutting edge of"],
        "root": "cutting edge(刀刃最前緣) → 走在最前面的",
        "synonyms": ["state-of-the-art", "advanced", "leading", "pioneering"],
        "category": "高頻話題字", "topic": "科技", "zh": "尖端的",
    },
]
