"""AWL Sublist 4 —— 四個維度全部寫齊。"""

SUBLIST_4 = [
    {
        "word": "access", "pos": "n./v.",
        "example": "Millions of rural households still have no access to clean water.",
        "collocations": ["have access to", "gain access to", "easy access"],
        "root": "ac-(朝向) + cess(走, 同 process/proceed/exceed) → 走得進去 → 進入的門路",
        "synonyms": ["entry", "admission", "availability", "approach"],
        "zh": "取得管道、使用權",
        "notes": "access to something —— 介系詞是 to，不是 of",
    },
    {
        "word": "adequate", "pos": "adj.",
        "example": "The shelter provides adequate food but very little privacy.",
        "collocations": ["adequate funding", "barely adequate", "adequate protection"],
        "root": "ad-(朝向) + equ(相等, 同 equal/equation) + -ate → 剛好對得上需求",
        "synonyms": ["sufficient", "satisfactory", "acceptable", "enough"],
        "zh": "足夠的、勉強夠的",
        "notes": "語感偏「剛好夠、不特別好」，跟 excellent 是不同層級",
    },
    {
        "word": "annual", "pos": "adj.",
        "example": "Annual rainfall in the region has fallen by a third since 1980.",
        "collocations": ["annual income", "an annual report", "annual growth"],
        "root": "ann(年, 拉丁 annus, 同 anniversary/annual) + -ual → 每年的",
        "synonyms": ["yearly", "each year", "twelve-monthly"],
        "zh": "每年的、年度的",
    },
    {
        "word": "apparent", "pos": "adj.",
        "example": "It soon became apparent that the new timetable was not working.",
        "collocations": ["become apparent", "for no apparent reason", "an apparent contradiction"],
        "root": "ap-(朝向) + par(顯現, 同 appear/transparent) + -ent → 顯露出來的",
        "synonyms": ["obvious", "evident", "clear", "noticeable"],
        "zh": "明顯的、看似的",
    },
    {
        "word": "approximate", "pos": "adj./v.",
        "example": "The map gives only the approximate location of each well.",
        "collocations": ["an approximate figure", "approximate cost", "approximate to"],
        "root": "ap-(朝向) + proxim(接近, 同 proximity/approach) + -ate → 靠近但不精確",
        "synonyms": ["rough", "estimated", "near", "close"],
        "zh": "大約的、近似的",
        "notes": "副詞 approximately 在 Task 1 描述數字時很好用",
    },
    {
        "word": "attitude", "pos": "n.",
        "example": "Public attitudes towards recycling have changed dramatically.",
        "collocations": ["attitudes towards", "a positive attitude", "change attitudes"],
        "root": "拉丁 aptitudo「適合的姿態」(同 aptitude/apt) → 心裡擺出的姿態",
        "synonyms": ["outlook", "mindset", "stance", "viewpoint"],
        "zh": "態度、看法",
        "notes": "attitude towards/to something，介系詞別用 of",
    },
    {
        "word": "civil", "pos": "adj.",
        "example": "The protest was organised by a coalition of civil society groups.",
        "collocations": ["civil rights", "civil society", "a civil servant"],
        "root": "civ(公民, 同 citizen/city/civilisation) + -il → 關於公民的",
        "synonyms": ["public", "civic", "communal", "non-military"],
        "zh": "公民的、民間的",
    },
    {
        "word": "code", "pos": "n./v.",
        "example": "Every hospital follows a strict code of conduct on patient privacy.",
        "collocations": ["a code of conduct", "a dress code", "the building code"],
        "root": "拉丁 codex「書板、法典」→ 一套寫定的規則或符號",
        "synonyms": ["rules", "regulations", "cipher", "system"],
        "zh": "守則、代碼",
    },
    {
        "word": "commit", "pos": "v.",
        "example": "The government has committed billions to upgrading the rail network.",
        "collocations": ["commit resources", "commit to", "commit a crime"],
        "root": "com-(一起) + mit(送出, 同 mission/transmit/submit) → 把自己送出去 → 投入",
        "synonyms": ["pledge", "dedicate", "devote", "undertake"],
        "zh": "投入、承諾；犯（罪）",
        "notes": "commit a crime（犯罪）與 be committed to（致力於）意思差很多",
    },
    {
        "word": "communicate", "pos": "v.",
        "example": "Doctors need to communicate risk in language patients actually understand.",
        "collocations": ["communicate effectively", "communicate with", "communicate ideas"],
        "root": "commun(共同, 同 common/community) + -icate → 把訊息變成共有的",
        "synonyms": ["convey", "express", "transmit", "get across"],
        "zh": "溝通、傳達",
    },
    {
        "word": "concentrate", "pos": "v.",
        "example": "Wealth remains concentrated in a handful of coastal cities.",
        "collocations": ["concentrate on", "be concentrated in", "concentrate efforts"],
        "root": "con-(一起) + centr(中心, 同 centre/central) + -ate → 往中心聚攏",
        "synonyms": ["focus", "cluster", "gather", "centre"],
        "zh": "集中、專注",
    },
    {
        "word": "confer", "pos": "v.",
        "example": "The judges conferred for an hour before announcing their decision.",
        "collocations": ["confer with", "confer a degree", "confer an advantage"],
        "root": "con-(一起) + fer(帶, 同 transfer/refer/offer) → 把意見帶到一起 → 商議",
        "synonyms": ["consult", "discuss", "deliberate", "grant"],
        "zh": "商議；授予",
    },
    {
        "word": "contrast", "pos": "n./v.",
        "example": "The report contrasts life expectancy in rich and poor districts.",
        "collocations": ["in contrast", "a sharp contrast", "contrast with"],
        "root": "contra-(相反, 同 contradict/contrary) + st(站立, 同 stand) → 站在對立面",
        "synonyms": ["difference", "comparison", "distinction", "opposition"],
        "zh": "對比、對照",
        "notes": "Task 1 比較兩組數據常用 In contrast, ... / by contrast",
    },
    {
        "word": "cycle", "pos": "n./v.",
        "example": "Breaking the cycle of poverty requires investment in early education.",
        "collocations": ["a vicious cycle", "the water cycle", "break the cycle"],
        "root": "希臘 kyklos「圓圈」(同 cyclone/bicycle/encyclopedia) → 繞回原點",
        "synonyms": ["loop", "sequence", "rotation", "round"],
        "zh": "循環、週期",
    },
    {
        "word": "debate", "pos": "n./v.",
        "example": "The proposal sparked a fierce debate about press freedom.",
        "collocations": ["a heated debate", "spark a debate", "the debate over"],
        "root": "de-(徹底) + bat(打, 同 battle/combat) → 言語上的交鋒",
        "synonyms": ["discussion", "argument", "dispute", "controversy"],
        "zh": "辯論、爭論",
        "notes": "Task 2 開頭常用 There is an ongoing debate about whether...",
    },
    {
        "word": "despite", "pos": "prep.",
        "example": "Despite heavy investment, journey times have barely improved.",
        "collocations": ["despite the fact that", "despite this", "despite efforts to"],
        "root": "de-(向下) + spite(看, 拉丁 specere, 同 spectacle/despise) → 看不起阻礙 → 儘管",
        "synonyms": ["in spite of", "notwithstanding", "regardless of", "even with"],
        "zh": "儘管",
        "notes": "後面接名詞或 V-ing；要接子句得寫 despite the fact that",
    },
    {
        "word": "dimension", "pos": "n.",
        "example": "The crisis has an environmental dimension as well as an economic one.",
        "collocations": ["a new dimension", "the social dimension", "add a dimension"],
        "root": "di-(徹底) + mens(測量, 同 measure/immense) + -ion → 量出來的面向",
        "synonyms": ["aspect", "facet", "element", "scale"],
        "zh": "面向、層面",
    },
    {
        "word": "domestic", "pos": "adj.",
        "example": "Domestic waste accounts for a quarter of the city's rubbish.",
        "collocations": ["domestic waste", "domestic violence", "the domestic market"],
        "root": "dom(家, 拉丁 domus, 同 dome/domicile) + -estic → 家裡的；引申為國內的",
        "synonyms": ["household", "home", "internal", "national"],
        "zh": "家庭的；國內的",
    },
    {
        "word": "emerge", "pos": "v.",
        "example": "A clear pattern emerged after the third round of testing.",
        "collocations": ["emerge as", "a pattern emerges", "emerge from"],
        "root": "e-(向外) + merg(沉沒, 同 submerge/merge) → 從水裡浮出來",
        "synonyms": ["appear", "arise", "surface", "come to light"],
        "zh": "浮現、出現",
    },
    {
        "word": "error", "pos": "n.",
        "example": "A single data entry error skewed the whole survey.",
        "collocations": ["a human error", "make an error", "margin of error"],
        "root": "拉丁 errare「走偏」(同 err/erratic/errant) → 走錯路",
        "synonyms": ["mistake", "fault", "inaccuracy", "slip"],
        "zh": "錯誤",
    },
    {
        "word": "ethnic", "pos": "adj.",
        "example": "The city is home to more than forty ethnic groups.",
        "collocations": ["an ethnic group", "ethnic diversity", "ethnic minority"],
        "root": "希臘 ethnos「民族」(同 ethnography) → 屬於某個民族的",
        "synonyms": ["cultural", "racial", "tribal", "national"],
        "zh": "族群的、民族的",
    },
    {
        "word": "goal", "pos": "n.",
        "example": "Cutting emissions by half is an ambitious but achievable goal.",
        "collocations": ["achieve a goal", "a long-term goal", "set a goal"],
        "root": "中古英語 gol「界線、終點」→ 要抵達的那條線",
        "synonyms": ["aim", "objective", "target", "purpose"],
        "zh": "目標",
    },
    {
        "word": "grant", "pos": "n./v.",
        "example": "The council granted planning permission despite local objections.",
        "collocations": ["grant permission", "a research grant", "take for granted"],
        "root": "拉丁 credentem「相信」→ 古法語 graunter「答應」→ 答應給出去",
        "synonyms": ["award", "give", "allow", "bestow"],
        "zh": "准予、補助金",
        "notes": "take something for granted = 把某事視為理所當然",
    },
    {
        "word": "hence", "pos": "adv.",
        "example": "Fuel is heavily taxed and hence car ownership remains low.",
        "collocations": ["and hence", "hence the name", "hence the need for"],
        "root": "古英語 heonan「從這裡」→ 從這一點推出去 → 因此",
        "synonyms": ["therefore", "thus", "consequently", "as a result"],
        "zh": "因此",
        "notes": "後面常直接接名詞片語（hence the delay），不一定要接完整子句",
    },
    {
        "word": "hypothesis", "pos": "n.",
        "example": "The data support the hypothesis that noise disrupts learning.",
        "collocations": ["test a hypothesis", "support a hypothesis", "the null hypothesis"],
        "root": "hypo-(在下面, 同 hypodermic) + thesis(放置, 同 thesis/synthesis) → 先擺在底下的假設",
        "synonyms": ["theory", "assumption", "proposition", "premise"],
        "zh": "假設",
        "notes": "複數是 hypotheses",
    },
    {
        "word": "implicate", "pos": "v.",
        "example": "Two former officials were implicated in the corruption scandal.",
        "collocations": ["be implicated in", "implicate someone in", "heavily implicated"],
        "root": "im-(進入) + plic(摺疊, 同 apply/complex/imply) → 被摺進事情裡 → 牽連",
        "synonyms": ["involve", "incriminate", "connect", "entangle"],
        "zh": "牽連、暗示涉及",
    },
    {
        "word": "impose", "pos": "v.",
        "example": "Several cities have imposed a congestion charge on private cars.",
        "collocations": ["impose a ban", "impose restrictions", "impose a tax"],
        "root": "im-(在上面) + pos(放置, 同 position/compose/expose) → 壓在別人身上",
        "synonyms": ["enforce", "levy", "inflict", "introduce"],
        "zh": "強制實施、課徵",
        "notes": "impose sth on sb —— 介系詞是 on",
    },
    {
        "word": "internal", "pos": "adj.",
        "example": "An internal review found serious failings in the safety system.",
        "collocations": ["an internal review", "internal affairs", "internal migration"],
        "root": "intern(內部, 拉丁 internus, 同 interior/intern) + -al → 裡面的",
        "synonyms": ["inner", "inside", "domestic", "in-house"],
        "zh": "內部的",
    },
    {
        "word": "investigate", "pos": "v.",
        "example": "Scientists are investigating why the coral recovered so quickly.",
        "collocations": ["investigate a claim", "thoroughly investigate", "investigate the cause"],
        "root": "in-(進入) + vestig(足跡, 同 vestige) + -ate → 跟著腳印追下去",
        "synonyms": ["examine", "look into", "research", "probe"],
        "zh": "調查、研究",
    },
    {
        "word": "job", "pos": "n.",
        "example": "Automation has already eliminated thousands of manufacturing jobs.",
        "collocations": ["create jobs", "a full-time job", "job satisfaction"],
        "root": "來源不明的中古英語 jobbe「一團、一份活」→ 一份要做的工作",
        "synonyms": ["employment", "post", "occupation", "position"],
        "zh": "工作、職位",
    },
    {
        "word": "label", "pos": "n./v.",
        "example": "Foods must be labelled with their sugar content.",
        "collocations": ["a warning label", "label as", "read the label"],
        "root": "古法語 label「布條」→ 掛上去說明身分的東西",
        "synonyms": ["tag", "mark", "classify", "brand"],
        "zh": "標籤；貼標籤",
    },
    {
        "word": "mechanism", "pos": "n.",
        "example": "The treaty sets up a mechanism for settling trade disputes.",
        "collocations": ["a coping mechanism", "a defence mechanism", "put a mechanism in place"],
        "root": "mechan(機器, 希臘 mechane, 同 machine/mechanic) + -ism → 運作的方式",
        "synonyms": ["process", "system", "procedure", "means"],
        "zh": "機制、機構",
    },
    {
        "word": "obvious", "pos": "adj.",
        "example": "There is no obvious reason why prices differ so widely between regions.",
        "collocations": ["an obvious choice", "for obvious reasons", "it is obvious that"],
        "root": "ob-(朝向) + vi(道路, 同 via/previous/obviate) → 擋在路上的 → 一眼就看到",
        "synonyms": ["clear", "evident", "apparent", "plain"],
        "zh": "明顯的",
    },
    {
        "word": "occupy", "pos": "v.",
        "example": "Informal settlements now occupy much of the land beside the river.",
        "collocations": ["occupy a position", "occupy space", "be occupied with"],
        "root": "oc-(朝向) + cup(拿取, 同 capture/capable/accept) → 拿下來佔住",
        "synonyms": ["take up", "inhabit", "fill", "hold"],
        "zh": "佔據、佔用",
    },
    {
        "word": "option", "pos": "n.",
        "example": "For many commuters, cycling is simply not a realistic option.",
        "collocations": ["a viable option", "have no option", "the best option"],
        "root": "opt(選擇, 拉丁 optare, 同 opt/adopt/optional) + -ion → 可以選的東西",
        "synonyms": ["choice", "alternative", "possibility", "selection"],
        "zh": "選項、選擇",
    },
    {
        "word": "output", "pos": "n.",
        "example": "Factory output fell sharply during the second quarter.",
        "collocations": ["industrial output", "increase output", "total output"],
        "root": "out(向外) + put(放) → 產出來的東西",
        "synonyms": ["production", "yield", "productivity", "product"],
        "zh": "產量、輸出",
        "notes": "Task 1 描述生產數據常用 output rose / fell",
    },
    {
        "word": "parallel", "pos": "adj./n.",
        "example": "There are clear parallels between the two cities' housing crises.",
        "collocations": ["draw a parallel", "in parallel with", "a parallel case"],
        "root": "para-(旁邊, 同 paragraph/parallel) + allel(彼此) → 並排而行",
        "synonyms": ["similar", "comparable", "corresponding", "analogous"],
        "zh": "平行的、相似之處",
    },
    {
        "word": "parameter", "pos": "n.",
        "example": "The study worked within very narrow parameters.",
        "collocations": ["set the parameters", "within the parameters", "key parameters"],
        "root": "para-(旁邊) + meter(測量, 同 metre/thermometer) → 用來界定範圍的量",
        "synonyms": ["limit", "boundary", "variable", "criterion"],
        "zh": "參數、界限",
    },
    {
        "word": "phase", "pos": "n.",
        "example": "The first phase of the project focused on flood defences.",
        "collocations": ["the first phase", "phase out", "a transitional phase"],
        "root": "希臘 phasis「顯現」(同 emphasis/phenomenon) → 顯現出來的一個階段",
        "synonyms": ["stage", "period", "step", "chapter"],
        "zh": "階段",
        "notes": "phase something out = 逐步淘汰，Task 2 講政策很好用",
    },
    {
        "word": "predict", "pos": "v.",
        "example": "Economists predict that housing costs will keep rising.",
        "collocations": ["predict that", "accurately predict", "as predicted"],
        "root": "pre-(事先) + dict(說, 同 dictate/verdict/contradict) → 事先說出來",
        "synonyms": ["forecast", "foresee", "anticipate", "project"],
        "zh": "預測",
    },
    {
        "word": "principal", "pos": "adj./n.",
        "example": "Agriculture remains the principal source of income in the valley.",
        "collocations": ["the principal cause", "the principal reason", "a school principal"],
        "root": "princip(第一, 拉丁 princeps, 同 prince/principle) + -al → 排第一的",
        "synonyms": ["main", "chief", "primary", "leading"],
        "zh": "主要的；校長",
        "notes": "principal（主要的）vs principle（原則）—— 拼字題常考",
    },
    {
        "word": "prior", "pos": "adj.",
        "example": "No prior experience is required for the training scheme.",
        "collocations": ["prior to", "prior knowledge", "prior approval"],
        "root": "拉丁 prior「更前面的」(同 primary/prime) → 時間上在前的",
        "synonyms": ["previous", "earlier", "preceding", "former"],
        "zh": "先前的",
        "notes": "prior to = before，正式寫作常用",
    },
    {
        "word": "professional", "pos": "adj./n.",
        "example": "Nurses receive ongoing professional development throughout their careers.",
        "collocations": ["professional development", "a health professional", "professional standards"],
        "root": "profess(公開宣稱, pro-(向前) + fess(說, 同 confess)) + -ional → 公開宣稱以此為業",
        "synonyms": ["expert", "qualified", "skilled", "vocational"],
        "zh": "專業的；專業人士",
    },
    {
        "word": "project", "pos": "n./v.",
        "example": "The population is projected to double within thirty years.",
        "collocations": ["a pilot project", "be projected to", "a research project"],
        "root": "pro-(向前) + ject(投擲, 同 reject/inject/eject) → 向前投出去",
        "synonyms": ["scheme", "plan", "forecast", "venture"],
        "zh": "計畫；推估",
        "notes": "Task 1 講未來數據常用 is projected to rise",
    },
    {
        "word": "promote", "pos": "v.",
        "example": "The campaign promotes cycling as a cheap alternative to driving.",
        "collocations": ["promote awareness", "promote growth", "actively promote"],
        "root": "pro-(向前) + mot(移動, 同 motion/motive/remove) → 往前推",
        "synonyms": ["encourage", "advance", "foster", "boost"],
        "zh": "促進、推廣",
    },
    {
        "word": "regime", "pos": "n.",
        "example": "The new regime abolished tuition fees in its first year.",
        "collocations": ["a military regime", "a strict regime", "the previous regime"],
        "root": "reg(統治, 同 regular/regulate/royal) + -ime → 統治的方式",
        "synonyms": ["government", "administration", "system", "rule"],
        "zh": "政權、制度",
    },
    {
        "word": "resolve", "pos": "v./n.",
        "example": "The dispute was finally resolved through mediation.",
        "collocations": ["resolve a dispute", "resolve an issue", "resolve to do"],
        "root": "re-(徹底) + solv(鬆開, 同 solve/dissolve/solution) → 把糾結鬆開",
        "synonyms": ["settle", "solve", "sort out", "determine"],
        "zh": "解決；決心",
    },
    {
        "word": "retain", "pos": "v.",
        "example": "Schools struggle to retain experienced teachers in rural areas.",
        "collocations": ["retain staff", "retain control", "retain information"],
        "root": "re-(往回) + tain(握住, 同 contain/maintain/detain) → 握住不放",
        "synonyms": ["keep", "hold on to", "preserve", "maintain"],
        "zh": "保留、留住",
    },
    {
        "word": "series", "pos": "n.",
        "example": "A series of heatwaves damaged crops across the region.",
        "collocations": ["a series of", "a whole series", "the latest series"],
        "root": "拉丁 serere「串連」(同 serial/insert) → 串成一列",
        "synonyms": ["sequence", "succession", "string", "run"],
        "zh": "一系列",
        "notes": "單複數同形；a series of + 複數名詞，動詞用單數",
    },
    {
        "word": "statistic", "pos": "n.",
        "example": "Official statistics show a steady fall in violent crime.",
        "collocations": ["official statistics", "crime statistics", "a shocking statistic"],
        "root": "stat(國家、狀態, 同 state/status) + -istic → 國家蒐集的數字",
        "synonyms": ["figure", "data point", "number", "measure"],
        "zh": "統計數字",
        "notes": "單數 statistic 指一個數字，複數 statistics 才是統計資料",
    },
    {
        "word": "status", "pos": "n.",
        "example": "Socioeconomic status strongly predicts a child's exam results.",
        "collocations": ["social status", "legal status", "status quo"],
        "root": "拉丁 status「站立的位置」(同 stand/state/statue) → 站在哪個位置",
        "synonyms": ["standing", "position", "rank", "condition"],
        "zh": "地位、狀態",
    },
    {
        "word": "stress", "pos": "n./v.",
        "example": "Long commutes are a major source of stress for city workers.",
        "collocations": ["under stress", "cause stress", "stress the importance of"],
        "root": "拉丁 strictus「拉緊」(同 strict/restrict/distress) → 被拉緊的狀態",
        "synonyms": ["pressure", "strain", "tension", "emphasise"],
        "zh": "壓力；強調",
    },
    {
        "word": "subsequent", "pos": "adj.",
        "example": "The subsequent investigation revealed a series of safety failures.",
        "collocations": ["subsequent years", "a subsequent study", "subsequent to"],
        "root": "sub-(接著) + sequ(跟隨, 同 sequence/consequence) + -ent → 跟在後面的",
        "synonyms": ["following", "later", "succeeding", "ensuing"],
        "zh": "隨後的",
    },
    {
        "word": "sum", "pos": "n./v.",
        "example": "The city spent a considerable sum on the flood barrier.",
        "collocations": ["a large sum", "sum up", "the sum of"],
        "root": "拉丁 summa「最高、總計」(同 summit/summary) → 加起來的頂點",
        "synonyms": ["amount", "total", "figure", "quantity"],
        "zh": "金額、總和",
        "notes": "sum up = 總結，口說結尾常用 To sum up, ...",
    },
    {
        "word": "summary", "pos": "n.",
        "example": "In summary, the benefits clearly outweigh the costs.",
        "collocations": ["in summary", "a brief summary", "a summary of findings"],
        "root": "summ(總計, 同 sum/summit) + -ary → 把重點加總起來",
        "synonyms": ["overview", "outline", "synopsis", "digest"],
        "zh": "摘要、總結",
        "notes": "Task 1 必寫的 overview 段落，就是一種 summary",
    },
    {
        "word": "undertake", "pos": "v.",
        "example": "The university undertook a five-year study of urban air quality.",
        "collocations": ["undertake research", "undertake a study", "undertake to do"],
        "root": "under(在下面) + take(拿) → 把責任接下來扛住",
        "synonyms": ["carry out", "take on", "conduct", "commit to"],
        "zh": "著手進行、承擔",
        "notes": "不規則變化：undertake / undertook / undertaken",
    },
]

for _entry in SUBLIST_4:
    _entry["category"] = "AWL"
    _entry["topic"] = "Sublist 4"
