"""AWL Sublist 8 —— 搭配詞、字根、同義詞、中文都寫好了，
例句欄故意留白給使用者自己寫 —— example_ref 是卡住時才看的參考。"""

SUBLIST_8 = [
    {
        "word": "abandon", "pos": "v.",
        "example_ref": "The company abandoned the project after two years of delays.",
        "example_ref_zh": "延宕兩年之後，這家公司放棄了這項計畫。",
        "collocations": ["abandon a plan", "abandon a project", "be abandoned"],
        "root": "古法語 a bandon「交由他人處置」→ 放手不管",
        "synonyms": ["give up", "drop", "desert", "discard"],
        "zh": "放棄、拋棄",
    },
    {
        "word": "accompany", "pos": "v.",
        "example_ref": "The rise in temperature was accompanied by a sharp fall in rainfall.",
        "example_ref_zh": "氣溫上升的同時伴隨著降雨量的大幅下降。",
        "collocations": ["be accompanied by", "accompany someone", "accompanying notes"],
        "root": "ac-(朝向) + company(同伴, com-(一起) + pan(麵包)) → 一起吃飯的人 → 陪同",
        "synonyms": ["go with", "escort", "attend", "come with"],
        "zh": "陪同、伴隨",
        "notes": "Task 1 描述兩個變化同時發生：X was accompanied by Y",
    },
    {
        "word": "ambiguous", "pos": "adj.",
        "example_ref": "The wording of the question was ambiguous and confused candidates.",
        "example_ref_zh": "這道題目的措辭模稜兩可，讓考生感到困惑。",
        "collocations": ["deliberately ambiguous", "an ambiguous result", "highly ambiguous"],
        "root": "ambi-(兩邊, 同 ambidextrous/ambition) + ag(驅動, 同 act/agent) → 往兩邊跑 → 兩種解讀",
        "synonyms": ["unclear", "vague", "equivocal", "open to interpretation"],
        "zh": "模稜兩可的",
    },
    {
        "word": "append", "pos": "v.",
        "example_ref": "A list of sources was appended to the end of the report.",
        "example_ref_zh": "報告末尾附上了一份參考資料清單。",
        "collocations": ["append to", "append a note", "appended documents"],
        "root": "ap-(朝向) + pend(懸掛, 同 pendant/depend/suspend) → 掛在後面",
        "synonyms": ["add", "attach", "affix", "tack on"],
        "zh": "附加、附錄",
    },
    {
        "word": "appreciate", "pos": "v.",
        "example_ref": "Few commuters appreciate how much the subsidy costs the city.",
        "example_ref_zh": "很少通勤者了解這項補貼讓城市付出多少代價。",
        "collocations": ["fully appreciate", "appreciate the difficulty", "appreciate the value of"],
        "root": "ap-(朝向) + preci(價值, 同 price/precious) + -ate → 看出它的價值",
        "synonyms": ["understand", "recognise", "value", "grasp"],
        "zh": "理解、重視",
    },
    {
        "word": "arbitrary", "pos": "adj.",
        "example_ref": "The cut-off age of sixty-five is entirely arbitrary.",
        "example_ref_zh": "以六十五歲作為分界完全是任意訂的。",
        "collocations": ["an arbitrary decision", "purely arbitrary", "arbitrary power"],
        "root": "arbitr(仲裁者, 同 arbitrate/arbiter) + -ary → 全憑仲裁者高興 → 隨意的",
        "synonyms": ["random", "capricious", "unjustified", "subjective"],
        "zh": "任意的、武斷的",
    },
    {
        "word": "automate", "pos": "v.",
        "example_ref": "Ports that automated early lost the most jobs.",
        "example_ref_zh": "愈早自動化的港口，失去的工作機會愈多。",
        "collocations": ["automate a process", "fully automated", "automate production"],
        "root": "auto-(自己, 同 automatic/autonomy) + mat(思考、行動) + -ate → 讓它自己動",
        "synonyms": ["mechanise", "computerise", "streamline"],
        "zh": "自動化",
    },
    {
        "word": "chart", "pos": "n./v.",
        "example_ref": "The chart shows electricity use in four countries between 2000 and 2020.",
        "example_ref_zh": "這張圖表顯示四個國家在 2000 到 2020 年的用電量。",
        "collocations": ["a bar chart", "a pie chart", "the chart shows"],
        "root": "希臘 khartes「紙草紙」(同 card/charter) → 畫在紙上的圖表",
        "synonyms": ["graph", "diagram", "table", "map"],
        "zh": "圖表",
        "notes": "Task 1 開頭必用：The chart shows / illustrates...",
    },
    {
        "word": "clarify", "pos": "v.",
        "example_ref": "The minister was asked to clarify what the new rules actually mean.",
        "example_ref_zh": "部長被要求說明新規定實際上是什麼意思。",
        "collocations": ["clarify a point", "clarify the situation", "seek to clarify"],
        "root": "clar(清楚, 拉丁 clarus, 同 clear/declare) + -ify → 使變清楚",
        "synonyms": ["explain", "make clear", "elucidate", "spell out"],
        "zh": "澄清、說明",
    },
    {
        "word": "commodity", "pos": "n.",
        "example_ref": "Clean water is becoming a scarce commodity in the region.",
        "example_ref_zh": "乾淨的水在這個地區正變成稀缺的商品。",
        "collocations": ["a scarce commodity", "commodity prices", "a valuable commodity"],
        "root": "com-(一起) + mod(尺度, 同 mode/moderate) + -ity → 有標準規格、可以交易的東西",
        "synonyms": ["goods", "product", "resource", "merchandise"],
        "zh": "商品、物資",
    },
    {
        "word": "complement", "pos": "n./v.",
        "example_ref": "Online lessons complement classroom teaching rather than replacing it.",
        "example_ref_zh": "線上課程是課堂教學的補充，而不是取代。",
        "collocations": ["complement each other", "a perfect complement", "complement nicely"],
        "root": "com-(一起) + ple(填滿, 同 complete/supply/plenty) → 補上缺的那塊",
        "synonyms": ["supplement", "go with", "complete", "enhance"],
        "zh": "補足、相輔相成",
        "notes": "complement（補足）vs compliment（稱讚）—— 拼字題常考",
    },
    {
        "word": "conform", "pos": "v.",
        "example_ref": "All new buildings must conform to strict energy standards.",
        "example_ref_zh": "所有新建築都必須符合嚴格的節能標準。",
        "collocations": ["conform to", "conform with", "refuse to conform"],
        "root": "con-(一起) + form(形狀) → 做成同一個形狀 → 遵守",
        "synonyms": ["comply", "adhere", "follow", "fit in"],
        "zh": "遵守、符合",
    },
    {
        "word": "contemporary", "pos": "adj./n.",
        "example_ref": "Contemporary art museums have become major tourist attractions.",
        "example_ref_zh": "當代藝術博物館已經成為主要的觀光景點。",
        "collocations": ["contemporary society", "contemporary art", "a contemporary of"],
        "root": "con-(一起) + tempor(時間, 同 temporary/tempo) + -ary → 同一個時代的",
        "synonyms": ["modern", "current", "present-day", "of the same era"],
        "zh": "當代的；同時代的人",
    },
    {
        "word": "contradict", "pos": "v.",
        "example_ref": "The latest figures contradict the government's own forecasts.",
        "example_ref_zh": "最新的數字與政府自己的預測相互矛盾。",
        "collocations": ["contradict a claim", "flatly contradict", "contradict oneself"],
        "root": "contra-(相反, 同 contrast/contrary) + dict(說, 同 dictate/predict) → 說反話",
        "synonyms": ["dispute", "refute", "conflict with", "deny"],
        "zh": "反駁、與…矛盾",
    },
    {
        "word": "crucial", "pos": "adj.",
        "example_ref": "The first three years of life are crucial for language development.",
        "example_ref_zh": "生命的頭三年對語言發展至關重要。",
        "collocations": ["a crucial role", "crucial evidence", "absolutely crucial"],
        "root": "拉丁 crux「十字路口」(同 cross/crux) → 決定往哪走的關鍵點",
        "synonyms": ["vital", "essential", "critical", "decisive"],
        "zh": "關鍵的",
        "notes": "play a crucial role in 是 Task 2 高分搭配",
    },
    {
        "word": "currency", "pos": "n.",
        "example_ref": "A weak currency made imported food far more expensive.",
        "example_ref_zh": "貨幣疲軟使進口食品變得貴得多。",
        "collocations": ["foreign currency", "a strong currency", "gain currency"],
        "root": "curr(流動, 同 current/occur/course) + -ency → 在市面上流通的東西",
        "synonyms": ["money", "legal tender", "cash", "acceptance"],
        "zh": "貨幣；流通",
    },
    {
        "word": "denote", "pos": "v.",
        "example_ref": "In the diagram, the dotted line denotes the projected figure.",
        "example_ref_zh": "在這張圖中，虛線代表推估的數值。",
        "collocations": ["denote a change", "commonly denote", "denote something"],
        "root": "de-(徹底) + not(記號, 同 note/notice/notion) → 明確標示出",
        "synonyms": ["indicate", "signify", "represent", "mean"],
        "zh": "表示、代表",
    },
    {
        "word": "detect", "pos": "v.",
        "example_ref": "The sensors can detect leaks long before they become visible.",
        "example_ref_zh": "這些感測器能在漏水肉眼可見之前就偵測到。",
        "collocations": ["detect a problem", "early detection", "hard to detect"],
        "root": "de-(去除) + tect(覆蓋, 同 protect/detective) → 把蓋子掀掉 → 察覺",
        "synonyms": ["discover", "identify", "spot", "sense"],
        "zh": "偵測、察覺",
    },
    {
        "word": "deviate", "pos": "v.",
        "example_ref": "The results deviate sharply from what the model predicted.",
        "example_ref_zh": "結果與模型的預測有很大的偏離。",
        "collocations": ["deviate from", "deviate significantly", "deviate from the norm"],
        "root": "de-(離開) + via(道路, 同 via/obvious/previous) + -ate → 走離原本的路",
        "synonyms": ["depart", "diverge", "stray", "differ"],
        "zh": "偏離",
    },
    {
        "word": "displace", "pos": "v.",
        "example_ref": "The dam displaced more than forty thousand villagers.",
        "example_ref_zh": "這座水壩迫使超過四萬名村民遷離。",
        "collocations": ["displaced people", "displace workers", "be displaced by"],
        "root": "dis-(離開) + place(地方) → 從原地趕走",
        "synonyms": ["uproot", "relocate", "replace", "oust"],
        "zh": "使遷離、取代",
    },
    {
        "word": "drama", "pos": "n.",
        "example_ref": "Television drama remains the most watched genre among older viewers.",
        "example_ref_zh": "電視劇仍是年長觀眾收看最多的類型。",
        "collocations": ["a television drama", "a courtroom drama", "high drama"],
        "root": "希臘 dran「行動」(同 dramatic/drastic) → 演出來的行動",
        "synonyms": ["play", "theatre", "production", "spectacle"],
        "zh": "戲劇",
    },
    {
        "word": "eventual", "pos": "adj.",
        "example_ref": "The eventual cost was three times the original estimate.",
        "example_ref_zh": "最終的成本是原先估計的三倍。",
        "collocations": ["the eventual outcome", "eventual success", "the eventual winner"],
        "root": "event(發生的事, e-(向外) + ven(來)) + -ual → 事情走完之後的",
        "synonyms": ["final", "ultimate", "resulting", "end"],
        "zh": "最終的",
        "notes": "副詞 eventually（最終）比形容詞更常用",
    },
    {
        "word": "exhibit", "pos": "v./n.",
        "example_ref": "Patients who exhibit these symptoms should be tested immediately.",
        "example_ref_zh": "出現這些症狀的病人應該立即接受檢驗。",
        "collocations": ["exhibit symptoms", "exhibit behaviour", "on exhibit"],
        "root": "ex-(向外) + hib(握住, 同 prohibit/inhibit/habit) → 拿出來給人看",
        "synonyms": ["display", "show", "demonstrate", "present"],
        "zh": "表現出、展出",
    },
    {
        "word": "exploit", "pos": "v./n.",
        "example_ref": "Companies have been accused of exploiting migrant workers.",
        "example_ref_zh": "這些公司被指控剝削移工。",
        "collocations": ["exploit resources", "exploit workers", "fully exploit"],
        "root": "ex-(向外) + ploit(摺疊, 拉丁 plicare, 同 employ/apply) → 攤開來用到極致",
        "synonyms": ["take advantage of", "use", "make use of", "abuse"],
        "zh": "利用、剝削",
        "notes": "exploit resources（開發資源）中性；exploit workers（剝削）負面",
    },
    {
        "word": "guideline", "pos": "n.",
        "example_ref": "The new guidelines recommend at least an hour of exercise a day.",
        "example_ref_zh": "新的指引建議每天至少運動一小時。",
        "collocations": ["follow guidelines", "issue guidelines", "official guidelines"],
        "root": "guide(引導) + line(線) → 畫出來讓人照著走的線",
        "synonyms": ["recommendation", "rule", "standard", "principle"],
        "zh": "指導方針",
    },
    {
        "word": "highlight", "pos": "v./n.",
        "example_ref": "The report highlights the shortage of affordable housing.",
        "example_ref_zh": "這份報告突顯了平價住宅的短缺。",
        "collocations": ["highlight the need for", "highlight a problem", "the highlight of"],
        "root": "high(高) + light(光) → 打光讓它突出來",
        "synonyms": ["emphasise", "underline", "draw attention to", "stress"],
        "zh": "強調、突顯",
        "notes": "Task 1 概述段很好用：The chart highlights...",
    },
    {
        "word": "implicit", "pos": "adj.",
        "example_ref": "There is an implicit assumption that everyone owns a smartphone.",
        "example_ref_zh": "這裡有一個隱含的假設：每個人都有智慧型手機。",
        "collocations": ["an implicit assumption", "implicit in", "implicit trust"],
        "root": "im-(進入) + plic(摺疊, 同 imply/complex/apply) → 摺在裡面沒攤開",
        "synonyms": ["implied", "unspoken", "tacit", "understood"],
        "zh": "隱含的",
        "notes": "反義字 explicit（明確的）",
    },
    {
        "word": "induce", "pos": "v.",
        "example_ref": "Higher parking charges induced many drivers to switch to buses.",
        "example_ref_zh": "更高的停車費促使許多駕駛改搭公車。",
        "collocations": ["induce someone to", "induce a change", "induce sleep"],
        "root": "in-(進入) + duce(引導, 同 conduct/reduce/produce) → 引導進來",
        "synonyms": ["persuade", "prompt", "bring about", "cause"],
        "zh": "促使、引發",
    },
    {
        "word": "inspect", "pos": "v.",
        "example_ref": "Officials inspect every restaurant at least once a year.",
        "example_ref_zh": "官員每年至少檢查每家餐廳一次。",
        "collocations": ["inspect a site", "closely inspect", "inspect for damage"],
        "root": "in-(進入) + spect(看, 同 spectacle/respect/suspect) → 看進去 → 檢查",
        "synonyms": ["examine", "check", "survey", "scrutinise"],
        "zh": "檢查、視察",
    },
    {
        "word": "intense", "pos": "adj.",
        "example_ref": "Intense competition for places has pushed entry requirements higher.",
        "example_ref_zh": "名額的激烈競爭把入學門檻推得更高。",
        "collocations": ["intense competition", "intense pressure", "intense heat"],
        "root": "in-(進入) + tens(拉緊, 同 tension/extend/tense) → 繃到極緊",
        "synonyms": ["extreme", "severe", "fierce", "acute"],
        "zh": "強烈的、激烈的",
    },
    {
        "word": "manipulate", "pos": "v.",
        "example_ref": "Critics accused the newspaper of manipulating public opinion.",
        "example_ref_zh": "批評者指控該報操弄輿論。",
        "collocations": ["manipulate data", "manipulate public opinion", "easily manipulated"],
        "root": "manu(手, 同 manual/manufacture) + pl(填滿) + -ate → 用手操弄",
        "synonyms": ["control", "influence", "handle", "distort"],
        "zh": "操控、操縱",
    },
    {
        "word": "minimise", "pos": "v.",
        "example_ref": "Careful planning can minimise disruption to residents.",
        "example_ref_zh": "周全的規劃可以把對居民的干擾降到最低。",
        "collocations": ["minimise the risk", "minimise disruption", "minimise costs"],
        "root": "minim(最小, 拉丁 minimus, 同 minimum/minor) + -ise → 使降到最小",
        "synonyms": ["reduce", "cut", "lessen", "curtail"],
        "zh": "使最小化",
        "notes": "美式拼 minimize；反義字 maximise",
    },
    {
        "word": "nuclear", "pos": "adj.",
        "example_ref": "Nuclear power supplies a fifth of the country's electricity.",
        "example_ref_zh": "核能供應了這個國家五分之一的電力。",
        "collocations": ["nuclear power", "nuclear energy", "a nuclear plant"],
        "root": "nucle(核心, 拉丁 nucleus 果仁, 同 nucleus) + -ar → 關於原子核的",
        "synonyms": ["atomic", "fission-based"],
        "zh": "核能的",
    },
    {
        "word": "paragraph", "pos": "n.",
        "example_ref": "Each paragraph should begin with a clear topic sentence.",
        "example_ref_zh": "每一段都應該以清楚的主題句開頭。",
        "collocations": ["the opening paragraph", "a topic sentence in a paragraph", "the final paragraph"],
        "root": "para-(旁邊) + graph(書寫, 同 graphic/biography) → 旁邊做記號分出的段落",
        "synonyms": ["section", "passage", "block of text"],
        "zh": "段落",
        "notes": "Task 2 的段落結構直接影響 Coherence 分數",
    },
    {
        "word": "plus", "pos": "prep./n.",
        "example_ref": "The fee covers tuition plus all course materials.",
        "example_ref_zh": "這筆費用涵蓋學費以及所有課程教材。",
        "collocations": ["plus the cost of", "a big plus", "plus interest"],
        "root": "拉丁 plus「更多」(同 plural/plenty/surplus) → 再加上",
        "synonyms": ["in addition to", "and", "with", "advantage"],
        "zh": "加上；優點",
    },
    {
        "word": "practitioner", "pos": "n.",
        "example_ref": "General practitioners refer patients to hospital specialists.",
        "example_ref_zh": "家庭醫師會把病人轉診給醫院的專科醫師。",
        "collocations": ["a general practitioner", "a medical practitioner", "experienced practitioners"],
        "root": "practi(實作, 同 practice/practical) + -tioner → 實際在做這行的人",
        "synonyms": ["professional", "specialist", "expert", "clinician"],
        "zh": "從業人員、開業者",
    },
    {
        "word": "predominant", "pos": "adj.",
        "example_ref": "Rice is the predominant crop in the southern provinces.",
        "example_ref_zh": "稻米是南部各省最主要的作物。",
        "collocations": ["the predominant view", "predominantly male", "the predominant cause"],
        "root": "pre-(在前) + dominant(支配的, 同 dominate/domain) → 壓過其他的",
        "synonyms": ["main", "prevailing", "dominant", "chief"],
        "zh": "佔多數的、主要的",
        "notes": "副詞 predominantly 在 Task 1 描述比例時很好用",
    },
    {
        "word": "prospect", "pos": "n.",
        "example_ref": "Graduates face better job prospects than they did a decade ago.",
        "example_ref_zh": "畢業生面對的就業前景比十年前好。",
        "collocations": ["job prospects", "the prospect of", "little prospect"],
        "root": "pro-(向前) + spect(看, 同 inspect/spectacle) → 往前看到的景象",
        "synonyms": ["outlook", "possibility", "chance", "expectation"],
        "zh": "前景、可能性",
    },
    {
        "word": "radical", "pos": "adj./n.",
        "example_ref": "Meeting the target will require radical changes to how we travel.",
        "example_ref_zh": "要達成這個目標，我們的移動方式必須有根本性的改變。",
        "collocations": ["a radical change", "radical reform", "radically different"],
        "root": "radic(根, 拉丁 radix, 同 radish/eradicate) + -al → 動到根本的",
        "synonyms": ["fundamental", "sweeping", "drastic", "extreme"],
        "zh": "根本的、激進的",
    },
    {
        "word": "random", "pos": "adj.",
        "example_ref": "Participants were assigned to the two groups at random.",
        "example_ref_zh": "受試者被隨機分配到兩個組別。",
        "collocations": ["at random", "a random sample", "randomly selected"],
        "root": "古法語 randon「猛衝」→ 沒有章法地衝 → 隨機",
        "synonyms": ["chance", "arbitrary", "haphazard", "unplanned"],
        "zh": "隨機的",
        "notes": "a random sample（隨機抽樣）是學術寫作常用",
    },
    {
        "word": "reinforce", "pos": "v.",
        "example_ref": "The findings reinforce earlier research on sleep and memory.",
        "example_ref_zh": "這些發現強化了先前關於睡眠與記憶的研究。",
        "collocations": ["reinforce a message", "reinforce stereotypes", "reinforce the view"],
        "root": "re-(再) + in-(使) + force(力量) → 再加一道力",
        "synonyms": ["strengthen", "support", "bolster", "confirm"],
        "zh": "強化、加強",
    },
    {
        "word": "restore", "pos": "v.",
        "example_ref": "Planting mangroves helped restore the damaged coastline.",
        "example_ref_zh": "種植紅樹林有助於復育受損的海岸線。",
        "collocations": ["restore confidence", "restore a building", "fully restore"],
        "root": "re-(再) + stor(建立, 拉丁 instaurare, 同 store/instaurate) → 再立起來",
        "synonyms": ["repair", "renew", "reinstate", "bring back"],
        "zh": "恢復、修復",
    },
    {
        "word": "revise", "pos": "v.",
        "example_ref": "The forecast was revised downwards twice in three months.",
        "example_ref_zh": "這份預測在三個月內被向下修正了兩次。",
        "collocations": ["revise a figure", "revise upwards", "revise an estimate"],
        "root": "re-(再) + vis(看, 同 vision/supervise/visit) → 再看一次改一改",
        "synonyms": ["amend", "update", "rework", "adjust"],
        "zh": "修訂、修正",
        "notes": "Task 1 講數據被修正：revised upwards / downwards",
    },
    {
        "word": "schedule", "pos": "n./v.",
        "example_ref": "The line opened two years behind schedule.",
        "example_ref_zh": "這條路線比原定時程晚了兩年通車。",
        "collocations": ["behind schedule", "ahead of schedule", "a busy schedule"],
        "root": "拉丁 schedula「小紙條」(同 cedula) → 寫在紙條上的時間表",
        "synonyms": ["timetable", "plan", "programme", "agenda"],
        "zh": "時程表、安排",
    },
    {
        "word": "tense", "pos": "adj./n.",
        "example_ref": "Relations between the two councils remain tense.",
        "example_ref_zh": "這兩個議會之間的關係依然緊張。",
        "collocations": ["a tense situation", "become tense", "the past tense"],
        "root": "拉丁 tendere「拉緊」(同 tension/extend/intense) → 繃緊的",
        "synonyms": ["strained", "edgy", "fraught", "taut"],
        "zh": "緊張的；時態",
    },
    {
        "word": "terminate", "pos": "v.",
        "example_ref": "The contract was terminated after repeated safety breaches.",
        "example_ref_zh": "在多次違反安全規定之後，這份合約被終止。",
        "collocations": ["terminate a contract", "terminate an agreement", "terminate early"],
        "root": "termin(界線, 拉丁 terminus, 同 terminal/determine) + -ate → 走到界線 → 結束",
        "synonyms": ["end", "cancel", "conclude", "discontinue"],
        "zh": "終止",
    },
    {
        "word": "theme", "pos": "n.",
        "example_ref": "Sustainability was the central theme of this year's conference.",
        "example_ref_zh": "永續是今年這場研討會的核心主題。",
        "collocations": ["the central theme", "a recurring theme", "a common theme"],
        "root": "希臘 thema「擺出來的東西」(同 thesis/hypothesis) → 貫穿全文的主軸",
        "synonyms": ["subject", "topic", "motif", "idea"],
        "zh": "主題",
    },
    {
        "word": "thereby", "pos": "adv.",
        "example_ref": "The scheme cut journeys by a fifth, thereby reducing emissions.",
        "example_ref_zh": "這個方案使行程減少五分之一，藉此降低了排放。",
        "collocations": ["thereby reducing", "thereby avoiding", "thereby creating"],
        "root": "there(那) + by(藉由) → 藉由那件事",
        "synonyms": ["thus", "in that way", "consequently", "hence"],
        "zh": "藉此、因而",
        "notes": "後面常接 V-ing，是把兩句合成一句的高分寫法",
    },
    {
        "word": "uniform", "pos": "adj./n.",
        "example_ref": "Rainfall is far from uniform across the country.",
        "example_ref_zh": "全國的降雨量遠遠稱不上均勻。",
        "collocations": ["a uniform standard", "uniform across", "school uniform"],
        "root": "uni-(一, 同 unit/unique) + form(形狀) → 都同一個形狀",
        "synonyms": ["consistent", "even", "standard", "unvarying"],
        "zh": "一致的；制服",
    },
    {
        "word": "vehicle", "pos": "n.",
        "example_ref": "Electric vehicles accounted for a third of new sales last year.",
        "example_ref_zh": "電動車佔了去年新車銷量的三分之一。",
        "collocations": ["a motor vehicle", "electric vehicles", "a vehicle for change"],
        "root": "拉丁 vehere「運送」(同 convey/vector) + -icle → 載東西的工具",
        "synonyms": ["car", "transport", "means", "medium"],
        "zh": "車輛；媒介",
    },
    {
        "word": "via", "pos": "prep.",
        "example_ref": "Most applications are now submitted via the council's website.",
        "example_ref_zh": "現在大多數申請都是透過議會網站送出。",
        "collocations": ["via email", "travel via", "via the internet"],
        "root": "拉丁 via「道路」(同 previous/obvious/deviate) → 經由某條路",
        "synonyms": ["through", "by way of", "by means of", "using"],
        "zh": "經由、透過",
    },
    {
        "word": "virtual", "pos": "adj.",
        "example_ref": "Virtual meetings have replaced most short business trips.",
        "example_ref_zh": "視訊會議已經取代了大部分的短程商務出差。",
        "collocations": ["virtual reality", "a virtual meeting", "a virtual monopoly"],
        "root": "virtu(能力, 拉丁 virtus, 同 virtue) + -al → 實質上有效果的；引申為「模擬的」",
        "synonyms": ["simulated", "online", "near-total", "effective"],
        "zh": "虛擬的；實際上的",
        "notes": "a virtual monopoly = 實質上的壟斷，跟「虛擬」無關",
    },
    {
        "word": "visual", "pos": "adj.",
        "example_ref": "Visual aids help students remember far more of a lecture.",
        "example_ref_zh": "視覺輔助能幫助學生記住更多課堂內容。",
        "collocations": ["visual aids", "visual impact", "visually impaired"],
        "root": "vis(看, 同 vision/visible/supervise) + -ual → 靠眼睛的",
        "synonyms": ["optical", "graphic", "pictorial", "seen"],
        "zh": "視覺的",
    },
    {
        "word": "widespread", "pos": "adj.",
        "example_ref": "There is widespread support for banning single-use plastics.",
        "example_ref_zh": "禁用一次性塑膠獲得了廣泛的支持。",
        "collocations": ["widespread support", "widespread damage", "become widespread"],
        "root": "wide(廣) + spread(散開) → 散得很開的",
        "synonyms": ["extensive", "prevalent", "common", "far-reaching"],
        "zh": "普遍的、廣泛的",
    },
]

for _entry in SUBLIST_8:
    _entry["category"] = "AWL"
    _entry["topic"] = "Sublist 8"
