"""高頻話題字：健康、都市化、犯罪、媒體（每個主題 20 字）。"""

TOPICS_B = [
    # ==================================================== 健康
    {
        "word": "obesity", "pos": "n.",
        "example": "Childhood obesity has doubled in urban areas over the past twenty years.",
        "collocations": ["childhood obesity", "obesity rates", "tackle obesity"],
        "root": "拉丁 obesus「吃過頭而胖」(ob- 完全 + edere 吃) + -ity → 肥胖的狀態",
        "synonyms": ["excess weight", "being overweight", "corpulence"],
        "category": "高頻話題字", "topic": "健康", "zh": "肥胖（症）",
    },
    {
        "word": "deteriorate", "pos": "v.",
        "example": "Air quality in the capital has deteriorated sharply since 2010.",
        "collocations": ["deteriorate rapidly", "conditions deteriorate", "deteriorating health"],
        "root": "拉丁 deterior「更壞」+ -ate → 變得更壞",
        "synonyms": ["worsen", "decline", "degenerate", "get worse"],
        "category": "高頻話題字", "topic": "健康", "zh": "惡化",
        "notes": "Task 1 描述下降趨勢也可用",
    },
    {
        "word": "constraint", "pos": "n.",
        "example": "Budget constraints forced the hospital to postpone the new wing.",
        "collocations": ["financial constraints", "time constraints", "impose constraints"],
        "root": "con-(一起) + strain/strict(拉緊, 同 restrict/strain) → 綁緊 → 限制",
        "synonyms": ["limitation", "restriction", "restraint", "barrier"],
        "category": "高頻話題字", "topic": "健康", "zh": "限制、約束",
    },
    {
        "word": "sedentary", "pos": "adj.",
        "example": "A sedentary lifestyle raises the risk of heart disease considerably.",
        "collocations": ["a sedentary lifestyle", "sedentary work", "increasingly sedentary"],
        "root": "sed(坐, 同 sediment 沉積物/session/reside) + -ary → 一直坐著的",
        "synonyms": ["inactive", "desk-bound", "physically inactive"],
        "category": "高頻話題字", "topic": "健康", "zh": "久坐不動的",
    },
    {
        "word": "life expectancy", "pos": "n. phr.",
        "example": "Average life expectancy has risen by almost ten years since 1980.",
        "collocations": ["average life expectancy", "life expectancy at birth", "raise life expectancy"],
        "root": "expect(期待, ex- 出去 + spect 看 → 往外看著等) → 預期能活多久",
        "synonyms": ["lifespan", "longevity", "average age at death"],
        "category": "高頻話題字", "topic": "健康", "zh": "平均壽命",
    },
    {
        "word": "longevity", "pos": "n.",
        "example": "Researchers link longevity to strong social ties as much as to diet.",
        "collocations": ["increased longevity", "the secret of longevity", "longevity in old age"],
        "root": "long(長) + ev(年歲, 拉丁 aevum 時代, 同 eternal/medieval) + -ity → 長的年歲",
        "synonyms": ["long life", "lifespan", "living to an old age"],
        "category": "高頻話題字", "topic": "健康", "zh": "長壽",
    },
    {
        "word": "well-being", "pos": "n.",
        "example": "Flexible hours improved staff well-being more than a pay rise did.",
        "collocations": ["mental well-being", "improve well-being", "a sense of well-being"],
        "root": "well(好) + being(存在的狀態) → 整體活得好的狀態",
        "synonyms": ["welfare", "quality of life", "wellness"],
        "category": "高頻話題字", "topic": "健康", "zh": "身心健康",
    },
    {
        "word": "epidemic", "pos": "n.",
        "example": "Doctors describe rising diabetes rates as a slow-moving epidemic.",
        "collocations": ["an obesity epidemic", "reach epidemic levels", "contain an epidemic"],
        "root": "epi-(在…之上, 同 epicentre) + dem(人民, 同 democracy/demographic) → 落在人民身上的",
        "synonyms": ["outbreak", "widespread disease", "plague"],
        "category": "高頻話題字", "topic": "健康", "zh": "流行病",
    },
    {
        "word": "vaccination", "pos": "n.",
        "example": "Vaccination rates fell in districts where clinics had closed.",
        "collocations": ["mass vaccination", "vaccination rates", "a vaccination programme"],
        "root": "拉丁 vacca「牛」→ 最早的疫苗來自牛痘 → 接種",
        "synonyms": ["immunisation", "inoculation", "jab"],
        "category": "高頻話題字", "topic": "健康", "zh": "疫苗接種",
    },
    {
        "word": "sanitation", "pos": "n.",
        "example": "Poor sanitation remains the main cause of disease in the camps.",
        "collocations": ["poor sanitation", "access to sanitation", "basic sanitation"],
        "root": "sanit(健康, 拉丁 sanus, 同 sane/sanitary) + -ation → 讓環境變健康",
        "synonyms": ["hygiene", "waste management", "cleanliness"],
        "category": "高頻話題字", "topic": "健康", "zh": "衛生設施",
    },
    {
        "word": "malnutrition", "pos": "n.",
        "example": "One child in eight still suffers from malnutrition in the region.",
        "collocations": ["suffer from malnutrition", "childhood malnutrition", "chronic malnutrition"],
        "root": "mal-(壞, 同 malfunction/malicious) + nutrition(營養) → 營養不良",
        "synonyms": ["undernourishment", "poor nutrition", "food deficiency"],
        "category": "高頻話題字", "topic": "健康", "zh": "營養不良",
    },
    {
        "word": "hygiene", "pos": "n.",
        "example": "Simple hand hygiene prevents a surprising number of infections.",
        "collocations": ["personal hygiene", "food hygiene", "poor hygiene"],
        "root": "源自希臘健康女神 Hygieia 的名字 → 保持健康的做法",
        "synonyms": ["cleanliness", "sanitation"],
        "category": "高頻話題字", "topic": "健康", "zh": "衛生",
    },
    {
        "word": "preventive", "pos": "adj.",
        "example": "Spending on preventive care saves far more than it costs.",
        "collocations": ["preventive care", "preventive measures", "preventive medicine"],
        "root": "pre-(事先) + vent(來, 同 event/invent/adventure) + -ive → 在事情來之前先擋住",
        "synonyms": ["precautionary", "protective", "pre-emptive"],
        "category": "高頻話題字", "topic": "健康", "zh": "預防性的",
    },
    {
        "word": "therapy", "pos": "n.",
        "example": "Talking therapy is now offered before medication in mild cases.",
        "collocations": ["undergo therapy", "physical therapy", "talking therapy"],
        "root": "希臘 therapeia「照料、伺候」→ 治療",
        "synonyms": ["treatment", "rehabilitation", "counselling"],
        "category": "高頻話題字", "topic": "健康", "zh": "治療、療法",
    },
    {
        "word": "symptom", "pos": "n.",
        "example": "Treating the symptoms does nothing about the underlying cause.",
        "collocations": ["show symptoms", "early symptoms", "treat the symptoms"],
        "root": "sym-(一起, 同 sympathy/symmetry) + ptom(落下, 同 asymptote) → 一起出現的現象",
        "synonyms": ["sign", "indication", "manifestation"],
        "category": "高頻話題字", "topic": "健康", "zh": "症狀",
    },
    {
        "word": "outbreak", "pos": "n.",
        "example": "An outbreak of food poisoning closed the canteen for a week.",
        "collocations": ["an outbreak of", "contain an outbreak", "a major outbreak"],
        "root": "out(向外) + break(爆開) → 突然爆出來",
        "synonyms": ["epidemic", "flare-up", "sudden spread"],
        "category": "高頻話題字", "topic": "健康", "zh": "爆發",
    },
    {
        "word": "insomnia", "pos": "n.",
        "example": "Shift workers report insomnia far more often than office staff.",
        "collocations": ["suffer from insomnia", "chronic insomnia", "cause insomnia"],
        "root": "in-(不) + somn(睡, 拉丁 somnus, 同 somnolent) + -ia(病症) → 睡不著",
        "synonyms": ["sleeplessness", "sleep problems", "difficulty sleeping"],
        "category": "高頻話題字", "topic": "健康", "zh": "失眠",
    },
    {
        "word": "addiction", "pos": "n.",
        "example": "Smartphone addiction is now treated in some clinics as a genuine disorder.",
        "collocations": ["treat addiction", "addiction to sugar", "screen addiction"],
        "root": "ad-(朝向) + dict(說, 同 dictate/predict；羅馬法把債務人「判給」債主) + -ion → 被判給某物",
        "synonyms": ["dependency", "compulsion", "craving"],
        "category": "高頻話題字", "topic": "健康", "zh": "成癮",
    },
    {
        "word": "immune", "pos": "adj.",
        "example": "A poor diet gradually weakens the immune system.",
        "collocations": ["the immune system", "immune to infection", "boost immune defences"],
        "root": "im-(不) + mun(義務, 同 municipal/community/commune) → 免除義務 → 免疫",
        "synonyms": ["resistant", "protected", "not susceptible"],
        "category": "高頻話題字", "topic": "健康", "zh": "免疫的",
    },
    {
        "word": "moderation", "pos": "n.",
        "example": "Most nutritionists say sugar is fine in moderation.",
        "collocations": ["in moderation", "practise moderation", "a message of moderation"],
        "root": "mod(尺度, 同 mode/model/modest) + -ation → 守著分寸",
        "synonyms": ["restraint", "balance", "self-control"],
        "category": "高頻話題字", "topic": "健康", "zh": "適量、節制",
    },

    # ==================================================== 都市化
    {
        "word": "congestion", "pos": "n.",
        "example": "Congestion charges have cut traffic in the city centre by a fifth.",
        "collocations": ["traffic congestion", "ease congestion", "severe congestion"],
        "root": "con-(一起) + gest(攜帶, 同 digest/gesture/suggest) + -ion → 全擠在一起",
        "synonyms": ["overcrowding", "gridlock", "traffic jams", "bottlenecks"],
        "category": "高頻話題字", "topic": "都市化", "zh": "壅塞",
    },
    {
        "word": "overpopulation", "pos": "n.",
        "example": "Overpopulation puts enormous strain on housing and water supplies.",
        "collocations": ["the problem of overpopulation", "urban overpopulation", "caused by overpopulation"],
        "root": "over-(超過) + population(人口) → 人口超過負荷",
        "synonyms": ["excessive population", "overcrowding", "population pressure"],
        "category": "高頻話題字", "topic": "都市化", "zh": "人口過多",
    },
    {
        "word": "overcrowding", "pos": "n.",
        "example": "Overcrowding on commuter trains has worsened every year since 2015.",
        "collocations": ["severe overcrowding", "ease overcrowding", "overcrowding in schools"],
        "root": "over-(超過) + crowd(擠) → 擠過了頭",
        "synonyms": ["congestion", "excessive density", "crush"],
        "category": "高頻話題字", "topic": "都市化", "zh": "過度擁擠",
    },
    {
        "word": "commute", "pos": "v.",
        "example": "Nearly half the workforce commutes for more than an hour each way.",
        "collocations": ["commute to work", "a long commute", "daily commuting"],
        "root": "com-(一起) + mut(改變, 同 mutate/mutual) → 原指把單程票「換算」成月票 → 通勤",
        "synonyms": ["travel to work", "make the journey to work"],
        "category": "高頻話題字", "topic": "都市化", "zh": "通勤",
    },
    {
        "word": "suburb", "pos": "n.",
        "example": "Families priced out of the centre have moved to the outer suburbs.",
        "collocations": ["the outer suburbs", "live in the suburbs", "a leafy suburb"],
        "root": "sub-(在下、靠近) + urb(城市, 同 urban/urbane) → 城市旁邊那一圈",
        "synonyms": ["outskirts", "residential area", "commuter belt"],
        "category": "高頻話題字", "topic": "都市化", "zh": "郊區",
    },
    {
        "word": "urban sprawl", "pos": "n. phr.",
        "example": "Green belts were introduced to limit urban sprawl around large cities.",
        "collocations": ["limit urban sprawl", "uncontrolled urban sprawl", "the effects of urban sprawl"],
        "root": "sprawl(四肢攤開) → 城市毫無節制地往外攤開",
        "synonyms": ["unplanned expansion", "suburban spread", "uncontrolled growth"],
        "category": "高頻話題字", "topic": "都市化", "zh": "都市擴張",
    },
    {
        "word": "affordable housing", "pos": "n. phr.",
        "example": "The shortage of affordable housing has pushed young people out of the city.",
        "collocations": ["a shortage of affordable housing", "build affordable housing", "affordable housing schemes"],
        "root": "afford(負擔得起, 古英語 geforthian 提供) + -able → 負擔得起的住宅",
        "synonyms": ["low-cost housing", "social housing", "subsidised housing"],
        "category": "高頻話題字", "topic": "都市化", "zh": "平價住宅",
    },
    {
        "word": "high-rise", "pos": "adj.",
        "example": "Most new homes in the district are in high-rise blocks.",
        "collocations": ["high-rise blocks", "a high-rise development", "live in a high-rise"],
        "root": "high(高) + rise(升起) → 蓋得很高的",
        "synonyms": ["multi-storey", "tower-block", "tall"],
        "category": "高頻話題字", "topic": "都市化", "zh": "高層的",
    },
    {
        "word": "pedestrian", "pos": "n.",
        "example": "The council closed the street to cars and gave it back to pedestrians.",
        "collocations": ["pedestrian zones", "pedestrian safety", "pedestrian crossings"],
        "root": "ped(腳, 同 pedal/pedicure/centipede) + -ian → 用腳走路的人",
        "synonyms": ["person on foot", "walker", "foot traffic"],
        "category": "高頻話題字", "topic": "都市化", "zh": "行人",
    },
    {
        "word": "rush hour", "pos": "n. phr.",
        "example": "Journey times almost double during the morning rush hour.",
        "collocations": ["during rush hour", "avoid rush hour", "rush-hour traffic"],
        "root": "rush(衝) + hour → 大家一起衝的那個時段",
        "synonyms": ["peak time", "peak hours", "the busy period"],
        "category": "高頻話題字", "topic": "都市化", "zh": "尖峰時段",
    },
    {
        "word": "migration", "pos": "n.",
        "example": "Rural-to-urban migration has added two million people to the city.",
        "collocations": ["rural-to-urban migration", "internal migration", "mass migration"],
        "root": "migr(遷移, 拉丁 migrare, 同 migrate/emigrate/immigrant) + -ation → 整群搬動",
        "synonyms": ["movement of people", "relocation", "influx"],
        "category": "高頻話題字", "topic": "都市化", "zh": "遷徙",
    },
    {
        "word": "gentrification", "pos": "n.",
        "example": "Gentrification has pushed long-standing residents out of the neighbourhood.",
        "collocations": ["rapid gentrification", "the gentrification of the district", "resist gentrification"],
        "root": "gentry(仕紳階級, 同 gentle 原意「出身好的」) → 變成仕紳住的地方",
        "synonyms": ["upmarket redevelopment", "social upgrading"],
        "category": "高頻話題字", "topic": "都市化", "zh": "仕紳化",
    },
    {
        "word": "slum", "pos": "n.",
        "example": "More than a billion people worldwide still live in slums.",
        "collocations": ["live in slums", "slum clearance", "slum conditions"],
        "root": "十九世紀倫敦俚語，指城市裡潮濕陰暗的後巷 → 貧民區",
        "synonyms": ["shanty town", "informal settlement", "deprived area"],
        "category": "高頻話題字", "topic": "都市化", "zh": "貧民窟",
    },
    {
        "word": "amenities", "pos": "n.",
        "example": "The estate was built with almost no local amenities within walking distance.",
        "collocations": ["local amenities", "basic amenities", "leisure amenities"],
        "root": "拉丁 amoenus「令人愉快的」+ -ity → 讓生活舒服的設施",
        "synonyms": ["facilities", "services", "conveniences"],
        "category": "高頻話題字", "topic": "都市化", "zh": "生活機能設施",
    },
    {
        "word": "density", "pos": "n.",
        "example": "Population density in the old quarter is five times the city average.",
        "collocations": ["population density", "high-density housing", "urban density"],
        "root": "dens(濃密, 拉丁 densus) + -ity → 擠的程度",
        "synonyms": ["concentration", "crowding level", "compactness"],
        "category": "高頻話題字", "topic": "都市化", "zh": "密度",
    },
    {
        "word": "regeneration", "pos": "n.",
        "example": "Urban regeneration turned the derelict docks into a cultural quarter.",
        "collocations": ["urban regeneration", "a regeneration scheme", "regeneration projects"],
        "root": "re-(再) + gener(生, 同 generate/genesis/generation) + -ation → 讓地方再生一次",
        "synonyms": ["renewal", "redevelopment", "revitalisation"],
        "category": "高頻話題字", "topic": "都市化", "zh": "都市再生",
    },
    {
        "word": "green space", "pos": "n. phr.",
        "example": "Access to green space measurably improves residents' mental health.",
        "collocations": ["access to green space", "preserve green space", "public green space"],
        "root": "green(綠) + space(空間) → 城市裡留下來的綠地",
        "synonyms": ["parkland", "open space", "recreational area"],
        "category": "高頻話題字", "topic": "都市化", "zh": "綠地",
    },
    {
        "word": "cost of living", "pos": "n. phr.",
        "example": "The rising cost of living has driven graduates back to their home towns.",
        "collocations": ["the rising cost of living", "a high cost of living", "the cost of living crisis"],
        "root": "cost(花費) + living(過日子) → 過日子要花的錢",
        "synonyms": ["living expenses", "household costs"],
        "category": "高頻話題字", "topic": "都市化", "zh": "生活成本",
    },
    {
        "word": "relocate", "pos": "v.",
        "example": "Several firms relocated to the suburbs when city rents doubled.",
        "collocations": ["relocate to the suburbs", "relocate residents", "relocate the factory"],
        "root": "re-(再) + loc(地方, 同 location/local) + -ate → 換到另一個位置",
        "synonyms": ["move", "resettle", "transfer", "shift"],
        "category": "高頻話題字", "topic": "都市化", "zh": "搬遷",
    },
    {
        "word": "utilities", "pos": "n.",
        "example": "Rent looks cheap until you add utilities and travel costs.",
        "collocations": ["utility bills", "pay for utilities", "essential utilities"],
        "root": "util(有用, 拉丁 uti 使用, 同 use/utilise) + -ity → 水電瓦斯這類有用的基礎服務",
        "synonyms": ["public services", "water and power", "basic services"],
        "category": "高頻話題字", "topic": "都市化", "zh": "水電等公用事業",
    },

    # ==================================================== 犯罪
    {
        "word": "surveillance", "pos": "n.",
        "example": "Critics argue that mass surveillance erodes personal privacy.",
        "collocations": ["CCTV surveillance", "under surveillance", "mass surveillance"],
        "root": "sur-(在上面) + veill(看守, 拉丁 vigilare, 同 vigilant/vigil) + -ance → 在上面盯著看",
        "synonyms": ["monitoring", "observation", "watching"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "監控",
    },
    {
        "word": "deterrent", "pos": "n.",
        "example": "Heavier fines act as a deterrent to dangerous driving.",
        "collocations": ["act as a deterrent", "an effective deterrent", "a strong deterrent"],
        "root": "de-(離開) + terr(恐懼, 同 terror/terrify) + -ent → 讓人因害怕而退開的東西",
        "synonyms": ["disincentive", "discouragement", "check", "restraint"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "嚇阻手段",
    },
    {
        "word": "rehabilitation", "pos": "n.",
        "example": "Prisons that focus on rehabilitation report lower reoffending rates.",
        "collocations": ["offender rehabilitation", "a rehabilitation programme", "focus on rehabilitation"],
        "root": "re-(再) + habilit(能力, 同 ability/able) + -ation → 讓能力回到身上",
        "synonyms": ["reform", "reintegration", "retraining"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "更生、復健",
    },
    {
        "word": "reoffend", "pos": "v.",
        "example": "Young offenders who find work are far less likely to reoffend.",
        "collocations": ["likely to reoffend", "reoffending rates", "stop them reoffending"],
        "root": "re-(再) + offend(冒犯、犯罪) → 再犯一次",
        "synonyms": ["commit further offences", "relapse into crime"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "再犯",
    },
    {
        "word": "custodial sentence", "pos": "n. phr.",
        "example": "First-time offenders rarely receive a custodial sentence for this offence.",
        "collocations": ["receive a custodial sentence", "a lengthy custodial sentence", "avoid a custodial sentence"],
        "root": "custod(看守, 同 custody/custodian) + -ial → 要被看管起來的刑罰",
        "synonyms": ["prison sentence", "jail term", "imprisonment"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "有期徒刑",
    },
    {
        "word": "petty crime", "pos": "n. phr.",
        "example": "Better street lighting cut petty crime in the neighbourhood by a third.",
        "collocations": ["tackle petty crime", "petty crime rates", "a rise in petty crime"],
        "root": "petty 來自法文 petit「小」→ 輕微的犯罪",
        "synonyms": ["minor offences", "low-level crime", "small-scale crime"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "輕微犯罪",
    },
    {
        "word": "vandalism", "pos": "n.",
        "example": "Repairing vandalism costs the council millions every year.",
        "collocations": ["acts of vandalism", "mindless vandalism", "prevent vandalism"],
        "root": "源自洗劫羅馬的日耳曼部族 Vandals（汪達爾人）→ 蓄意破壞",
        "synonyms": ["criminal damage", "defacement", "wilful damage"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "破壞公物",
    },
    {
        "word": "fraud", "pos": "n.",
        "example": "Online fraud now costs consumers more than street theft does.",
        "collocations": ["commit fraud", "online fraud", "a fraud investigation"],
        "root": "拉丁 fraus「欺騙」→ 用詐術取得財物",
        "synonyms": ["deception", "scam", "swindle", "cheating"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "詐欺",
    },
    {
        "word": "burglary", "pos": "n.",
        "example": "Burglary fell steadily after the neighbourhood watch scheme started.",
        "collocations": ["report a burglary", "burglary rates", "a burglary attempt"],
        "root": "burg(城堡、城鎮, 同 borough/burgher) → 闖進人家的屋子偷竊",
        "synonyms": ["break-in", "housebreaking", "robbery"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "闖空門",
    },
    {
        "word": "community service", "pos": "n. phr.",
        "example": "He was sentenced to two hundred hours of community service.",
        "collocations": ["sentenced to community service", "carry out community service", "community service orders"],
        "root": "community(社區) + service(服務) → 用勞務回饋社區來抵刑",
        "synonyms": ["unpaid work", "a community sentence"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "社區服務（刑）",
    },
    {
        "word": "parole", "pos": "n.",
        "example": "She was released on parole after serving half her sentence.",
        "collocations": ["released on parole", "be granted parole", "a parole board"],
        "root": "法文 parole「話語」→ 以「承諾」（口頭保證）換取提早釋放",
        "synonyms": ["conditional release", "early release"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "假釋",
    },
    {
        "word": "prosecute", "pos": "v.",
        "example": "Companies that dump waste illegally are rarely prosecuted.",
        "collocations": ["prosecute offenders", "be prosecuted for", "decide to prosecute"],
        "root": "pro-(向前) + secut(跟隨, 同 sequence/pursue/consecutive) → 一路追訴到底",
        "synonyms": ["take to court", "charge", "bring to trial"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "起訴",
    },
    {
        "word": "juvenile", "pos": "adj.",
        "example": "Juvenile offenders are dealt with in a separate court system.",
        "collocations": ["juvenile crime", "juvenile offenders", "a juvenile court"],
        "root": "juven(年輕, 拉丁 juvenis, 同 junior/rejuvenate) + -ile → 年少的",
        "synonyms": ["youth", "underage", "young"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "青少年的",
    },
    {
        "word": "corruption", "pos": "n.",
        "example": "Corruption in the licensing system was exposed by a whistleblower.",
        "collocations": ["political corruption", "tackle corruption", "corruption scandals"],
        "root": "cor-(完全) + rupt(破裂, 同 rupture/disrupt/erupt) + -ion → 整個爛掉",
        "synonyms": ["bribery", "dishonesty", "graft", "malpractice"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "貪腐",
    },
    {
        "word": "offence", "pos": "n.",
        "example": "Driving without insurance is a criminal offence in most countries.",
        "collocations": ["a criminal offence", "commit an offence", "a minor offence"],
        "root": "of-(朝向) + fend(打, 同 defend/fend off) + -ence → 打到別人 → 冒犯、違法行為",
        "synonyms": ["crime", "violation", "breach", "wrongdoing"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "罪行",
    },
    {
        "word": "victim", "pos": "n.",
        "example": "Support services for victims of crime remain badly underfunded.",
        "collocations": ["victims of crime", "support victims", "fall victim to"],
        "root": "拉丁 victima「祭品」→ 被犧牲掉的人",
        "synonyms": ["casualty", "injured party", "sufferer"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "受害者",
    },
    {
        "word": "incarceration", "pos": "n.",
        "example": "Mass incarceration has proved expensive and largely ineffective.",
        "collocations": ["mass incarceration", "the cost of incarceration", "rates of incarceration"],
        "root": "in-(進入) + carcer(監獄, 拉丁 carcer) + -ation → 關進牢裡",
        "synonyms": ["imprisonment", "jailing", "detention"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "監禁",
    },
    {
        "word": "patrol", "pos": "n.",
        "example": "Regular police patrols reassured residents more than cameras did.",
        "collocations": ["police patrols", "patrol the streets", "step up patrols"],
        "root": "法文 patrouiller「在泥裡踩來踩去」→ 來回走動巡查",
        "synonyms": ["police presence", "round", "watch"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "巡邏",
    },
    {
        "word": "law-abiding", "pos": "adj.",
        "example": "Blanket surveillance treats law-abiding citizens as suspects.",
        "collocations": ["law-abiding citizens", "a law-abiding society", "otherwise law-abiding"],
        "root": "law(法律) + abide(遵守, 古英語 abidan 停留) → 待在法律範圍裡",
        "synonyms": ["honest", "compliant", "respectable"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "守法的",
    },
    {
        "word": "penalty", "pos": "n.",
        "example": "Stiffer penalties alone have never been shown to reduce crime.",
        "collocations": ["stiff penalties", "impose a penalty", "the maximum penalty"],
        "root": "pen(懲罰, 拉丁 poena, 同 punish/penal/pain) + -alty → 罰則",
        "synonyms": ["punishment", "sanction", "fine"],
        "category": "高頻話題字", "topic": "犯罪", "zh": "刑罰、罰則",
    },

    # ==================================================== 媒體
    {
        "word": "undermine", "pos": "v.",
        "example": "The spread of misinformation undermines public trust in journalism.",
        "collocations": ["undermine confidence", "undermine authority", "undermine efforts"],
        "root": "under(下面) + mine(挖礦) → 在底下挖坑 → 動搖根基",
        "synonyms": ["weaken", "erode", "damage", "compromise"],
        "category": "高頻話題字", "topic": "媒體", "zh": "逐漸削弱",
    },
    {
        "word": "impartial", "pos": "adj.",
        "example": "Public broadcasters are expected to remain impartial during elections.",
        "collocations": ["remain impartial", "impartial coverage", "an impartial observer"],
        "root": "im-(不) + partial(偏袒的, part 部分 → 站在某一部分那邊) → 不偏任何一邊",
        "synonyms": ["unbiased", "neutral", "objective", "even-handed"],
        "category": "高頻話題字", "topic": "媒體", "zh": "公正的",
    },
    {
        "word": "tabloid", "pos": "n.",
        "example": "The story was splashed across every tabloid the following morning.",
        "collocations": ["the tabloid press", "tabloid headlines", "a tabloid newspaper"],
        "root": "tablet(小藥片) 的商標名 → 把新聞壓縮成小份、好吞的形式",
        "synonyms": ["popular press", "red-top", "sensational paper"],
        "category": "高頻話題字", "topic": "媒體", "zh": "小報",
    },
    {
        "word": "censorship", "pos": "n.",
        "example": "State censorship makes it impossible to verify what really happened.",
        "collocations": ["state censorship", "impose censorship", "media censorship"],
        "root": "cens(評定, 羅馬的 censor 監察官負責審查風紀) + -ship → 審查制度",
        "synonyms": ["suppression", "control of information", "blocking"],
        "category": "高頻話題字", "topic": "媒體", "zh": "審查制度",
    },
    {
        "word": "coverage", "pos": "n.",
        "example": "The election received far more coverage online than on television.",
        "collocations": ["media coverage", "extensive coverage", "biased coverage"],
        "root": "cover(覆蓋) + -age → 報導所「蓋到」的範圍",
        "synonyms": ["reporting", "media attention", "treatment"],
        "category": "高頻話題字", "topic": "媒體", "zh": "報導（量）",
    },
    {
        "word": "credibility", "pos": "n.",
        "example": "The paper lost credibility after publishing the story without checking it.",
        "collocations": ["lose credibility", "damage credibility", "the credibility of a source"],
        "root": "cred(相信, 同 credit/incredible/creed) + -ibility → 可以被相信的程度",
        "synonyms": ["trustworthiness", "reliability", "believability"],
        "category": "高頻話題字", "topic": "媒體", "zh": "可信度",
    },
    {
        "word": "sensationalism", "pos": "n.",
        "example": "Competition for clicks has encouraged sensationalism over accuracy.",
        "collocations": ["media sensationalism", "accused of sensationalism", "tabloid sensationalism"],
        "root": "sens(感覺, 同 sense/sensation) + -ation + -ism → 一味追求刺激感受",
        "synonyms": ["hype", "exaggeration", "scaremongering"],
        "category": "高頻話題字", "topic": "媒體", "zh": "煽情報導",
    },
    {
        "word": "propaganda", "pos": "n.",
        "example": "Wartime propaganda was designed to keep morale high at home.",
        "collocations": ["state propaganda", "spread propaganda", "a propaganda campaign"],
        "root": "拉丁 propagare「繁殖、散播」(同 propagate) → 把某套觀念大量散出去",
        "synonyms": ["political messaging", "indoctrination", "spin"],
        "category": "高頻話題字", "topic": "媒體", "zh": "政治宣傳",
    },
    {
        "word": "clickbait", "pos": "n.",
        "example": "Headlines written as clickbait rarely deliver what they promise.",
        "collocations": ["clickbait headlines", "rely on clickbait", "pure clickbait"],
        "root": "click(點擊) + bait(誘餌) → 專門引你上鉤的餌",
        "synonyms": ["sensational headlines", "attention-grabbing content"],
        "category": "高頻話題字", "topic": "媒體", "zh": "點擊誘餌",
    },
    {
        "word": "echo chamber", "pos": "n. phr.",
        "example": "Recommendation systems can trap users in an echo chamber of similar views.",
        "collocations": ["an online echo chamber", "trapped in an echo chamber", "create echo chambers"],
        "root": "echo(回音) + chamber(房間) → 只聽得到自己聲音回彈的房間",
        "synonyms": ["filter bubble", "closed information loop"],
        "category": "高頻話題字", "topic": "媒體", "zh": "同溫層",
    },
    {
        "word": "outlet", "pos": "n.",
        "example": "Independent news outlets struggle to compete with social platforms.",
        "collocations": ["a news outlet", "mainstream outlets", "independent outlets"],
        "root": "out(外) + let(讓出, 同 let) → 讓內容流出來的出口",
        "synonyms": ["media organisation", "publication", "channel"],
        "category": "高頻話題字", "topic": "媒體", "zh": "媒體機構",
    },
    {
        "word": "subscription", "pos": "n.",
        "example": "Digital subscriptions now bring in more revenue than print advertising.",
        "collocations": ["a digital subscription", "cancel a subscription", "subscription numbers"],
        "root": "sub-(在下) + script(寫, 同 script/describe/manuscript) + -ion → 在文件底下簽名訂閱",
        "synonyms": ["membership", "paid access"],
        "category": "高頻話題字", "topic": "媒體", "zh": "訂閱",
    },
    {
        "word": "viral", "pos": "adj.",
        "example": "The clip went viral before anyone checked whether it was genuine.",
        "collocations": ["go viral", "a viral video", "viral marketing"],
        "root": "virus(病毒) + -al → 像病毒一樣一傳十十傳百",
        "synonyms": ["rapidly shared", "widely circulated"],
        "category": "高頻話題字", "topic": "媒體", "zh": "爆紅的",
    },
    {
        "word": "influencer", "pos": "n.",
        "example": "Brands now spend more on influencers than on television advertising.",
        "collocations": ["social media influencers", "influencer marketing", "a beauty influencer"],
        "root": "in-(進入) + flu(流, 同 fluent/fluid/fluctuate) + -ence + -er → 讓想法「流進」別人腦中的人",
        "synonyms": ["content creator", "opinion leader"],
        "category": "高頻話題字", "topic": "媒體", "zh": "網紅",
    },
    {
        "word": "defamation", "pos": "n.",
        "example": "The politician sued the magazine for defamation and won.",
        "collocations": ["sue for defamation", "a defamation case", "defamation laws"],
        "root": "de-(去除) + fam(名聲, 同 fame/famous/infamous) + -ation → 把名聲拿掉",
        "synonyms": ["libel", "slander", "character attack"],
        "category": "高頻話題字", "topic": "媒體", "zh": "誹謗",
    },
    {
        "word": "editorial", "pos": "n.",
        "example": "The paper ran an editorial calling for the minister to resign.",
        "collocations": ["an editorial line", "editorial independence", "write an editorial"],
        "root": "edit(拿出來發表, 拉丁 edere 產出, 同 edition) + -orial → 代表報社立場的文章",
        "synonyms": ["opinion piece", "leader", "commentary"],
        "category": "高頻話題字", "topic": "媒體", "zh": "社論",
    },
    {
        "word": "scrutiny", "pos": "n.",
        "example": "Social media companies are finally coming under serious scrutiny.",
        "collocations": ["public scrutiny", "come under scrutiny", "close scrutiny"],
        "root": "拉丁 scrutari「翻找破爛」(scruta 廢棄物) → 一件一件翻出來查",
        "synonyms": ["close examination", "inspection", "oversight"],
        "category": "高頻話題字", "topic": "媒體", "zh": "嚴格審視",
    },
    {
        "word": "circulation", "pos": "n.",
        "example": "The magazine's circulation halved within five years of going online.",
        "collocations": ["falling circulation", "boost circulation", "a circulation of"],
        "root": "circul(圓圈, 同 circle/circuit) + -ation → 一份份流通出去的量",
        "synonyms": ["readership", "distribution", "sales figures"],
        "category": "高頻話題字", "topic": "媒體", "zh": "發行量",
    },
    {
        "word": "anonymity", "pos": "n.",
        "example": "Online anonymity protects whistleblowers but also shields abusers.",
        "collocations": ["online anonymity", "protect anonymity", "the anonymity of the internet"],
        "root": "an-(沒有) + onym(名字, 同 synonym/pseudonym/acronym) + -ity → 沒有名字的狀態",
        "synonyms": ["namelessness", "concealed identity"],
        "category": "高頻話題字", "topic": "媒體", "zh": "匿名",
    },
    {
        "word": "accountability", "pos": "n.",
        "example": "Readers are demanding greater accountability from the platforms they use.",
        "collocations": ["demand accountability", "media accountability", "public accountability"],
        "root": "account(交代, 原意「計算」) + -ability → 要能交代清楚的責任",
        "synonyms": ["answerability", "responsibility", "transparency"],
        "category": "高頻話題字", "topic": "媒體", "zh": "問責",
    },
]
