"""AWL Sublist 2 —— 學術英語第二高頻的一組，四個維度全部寫齊。

（conduct 已寫在 data_awl.py 的 FULL 裡，這裡不重複。）
"""

SUBLIST_2 = [
    {
        "word": "achieve", "pos": "v.",
        "example": "The country achieved its emissions target two years early.",
        "collocations": ["achieve a goal", "achieve success", "hard to achieve"],
        "root": "法文 achever「做到頭」(à chef 到頂點, 同 chief) → 一路做到底",
        "synonyms": ["accomplish", "attain", "reach", "realise"],
        "zh": "達成",
    },
    {
        "word": "acquire", "pos": "v.",
        "example": "Children acquire a second language far faster than adults.",
        "collocations": ["acquire skills", "acquire a taste for", "newly acquired"],
        "root": "ad-(朝向) + quir(尋求, 同 require/inquire/conquer) → 一路追到手",
        "synonyms": ["obtain", "gain", "pick up", "come by"],
        "zh": "取得、習得",
    },
    {
        "word": "administration", "pos": "n.",
        "example": "Too much of a teacher's week goes on administration.",
        "collocations": ["hospital administration", "the administration of", "administration costs"],
        "root": "ad-(朝向) + minister(服務, 同 minister/minor 小的→僕從) + -ation → 為人打理事務",
        "synonyms": ["management", "governance", "running", "paperwork"],
        "zh": "行政、管理",
    },
    {
        "word": "affect", "pos": "v.",
        "example": "Rising sea temperatures affect fish stocks worldwide.",
        "collocations": ["affect the outcome", "badly affected", "seriously affect"],
        "root": "af-(朝向) + fect(做, 同 effect/perfect/factory) → 對某物施加動作 → 影響",
        "synonyms": ["influence", "have an impact on", "change", "alter"],
        "zh": "影響",
        "notes": "affect 是動詞、effect 是名詞 —— 雅思寫作最常見的錯之一",
    },
    {
        "word": "appropriate", "pos": "adj.",
        "example": "Jeans are not appropriate for a formal interview.",
        "collocations": ["appropriate action", "where appropriate", "an appropriate response"],
        "root": "ap-(朝向) + propri(自己的, 同 property/proper) + -ate → 配得上這個場合的",
        "synonyms": ["suitable", "fitting", "proper", "apt"],
        "zh": "適當的",
    },
    {
        "word": "aspect", "pos": "n.",
        "example": "The report examines every aspect of student life.",
        "collocations": ["an important aspect", "every aspect of", "a positive aspect"],
        "root": "a-(朝向) + spect(看, 同 inspect/respect/spectator) → 從某個角度看過去的那一面",
        "synonyms": ["side", "feature", "facet", "element"],
        "zh": "方面",
    },
    {
        "word": "assist", "pos": "v.",
        "example": "Volunteers assist staff with the evening classes.",
        "collocations": ["assist with", "assist in the process", "greatly assist"],
        "root": "as-(朝向) + sist(站, 同 consist/resist/insist) → 站到旁邊幫忙",
        "synonyms": ["help", "aid", "support", "lend a hand"],
        "zh": "協助",
    },
    {
        "word": "category", "pos": "n.",
        "example": "Spending falls into three broad categories.",
        "collocations": ["fall into a category", "a broad category", "three categories"],
        "root": "希臘 katēgoria「公開指稱」(kata 向下 + agora 集會場) → 當眾歸到某個名目下",
        "synonyms": ["class", "group", "type", "classification"],
        "zh": "類別",
    },
    {
        "word": "chapter", "pos": "n.",
        "example": "The final chapter suggests directions for future research.",
        "collocations": ["the opening chapter", "in this chapter", "a chapter on"],
        "root": "拉丁 caput「頭」的小詞(同 capital/captain/chief) → 一個小標頭底下的段落",
        "synonyms": ["section", "part", "division"],
        "zh": "章",
    },
    {
        "word": "commission", "pos": "v.",
        "example": "The council commissioned a study of local air quality.",
        "collocations": ["commission a study", "commission a report", "be commissioned to"],
        "root": "com-(一起) + miss(送, 同 mission/transmit/dismiss) + -ion → 把任務託付送出去",
        "synonyms": ["order", "appoint", "contract", "engage"],
        "zh": "委託",
    },
    {
        "word": "community", "pos": "n.",
        "example": "The library is the only meeting place the community has.",
        "collocations": ["the local community", "a close-knit community", "community support"],
        "root": "com-(一起) + mun(義務、共有, 同 municipal/immune) + -ity → 共同承擔的一群人",
        "synonyms": ["neighbourhood", "population", "the public", "society"],
        "zh": "社區、群體",
    },
    {
        "word": "complex", "pos": "adj.",
        "example": "Traffic is a complex problem with no single solution.",
        "collocations": ["a complex problem", "increasingly complex", "complex systems"],
        "root": "com-(一起) + plex(編織, 同 perplex/plait) → 編在一起拆不開的",
        "synonyms": ["complicated", "intricate", "involved", "multi-layered"],
        "zh": "複雜的",
    },
    {
        "word": "compute", "pos": "v.",
        "example": "The software computes the total cost automatically.",
        "collocations": ["compute the total", "compute the cost", "computed automatically"],
        "root": "com-(一起) + put(算, 拉丁 putare 原意修剪→理清) → 一起算清楚",
        "synonyms": ["calculate", "work out", "reckon", "tally"],
        "zh": "計算",
    },
    {
        "word": "conclude", "pos": "v.",
        "example": "The authors conclude that the policy has largely failed.",
        "collocations": ["conclude that", "the study concludes", "conclude an agreement"],
        "root": "con-(完全) + clud(關閉, 同 include/exclude/close) → 整個收攏關起來",
        "synonyms": ["decide", "determine", "infer", "wrap up"],
        "zh": "得出結論",
    },
    {
        "word": "consequent", "pos": "adj.",
        "example": "Deforestation and the consequent soil erosion worry local farmers.",
        "collocations": ["the consequent rise", "consequent damage", "consequent upon"],
        "root": "con-(一起) + sequ(跟隨, 同 sequence/consecutive/pursue) + -ent → 跟在後面來的",
        "synonyms": ["resulting", "following", "ensuing"],
        "zh": "隨之而來的",
    },
    {
        "word": "construct", "pos": "v.",
        "example": "The bridge was constructed in under two years.",
        "collocations": ["construct a building", "carefully constructed", "construct an argument"],
        "root": "con-(一起) + struct(建造, 同 structure/instruct/destroy) → 組建起來",
        "synonyms": ["build", "assemble", "put together", "erect"],
        "zh": "建造",
    },
    {
        "word": "consume", "pos": "v.",
        "example": "Data centres consume as much power as a small city.",
        "collocations": ["consume energy", "consume resources", "heavily consumed"],
        "root": "con-(完全) + sum(拿取, 同 assume/resume) → 整個拿去用光",
        "synonyms": ["use up", "get through", "expend", "burn"],
        "zh": "消耗",
    },
    {
        "word": "credit", "pos": "n.",
        "example": "The team deserves credit for finishing ahead of schedule.",
        "collocations": ["take credit for", "give credit to", "buy on credit"],
        "root": "cred(相信, 同 credible/incredible/creed) → 因為被信任而給出去的",
        "synonyms": ["recognition", "praise", "acknowledgement"],
        "zh": "功勞；賒帳",
    },
    {
        "word": "culture", "pos": "n.",
        "example": "Working culture varies enormously between the two offices.",
        "collocations": ["popular culture", "a company's culture", "cultural differences"],
        "root": "cult(耕作, 同 cultivate/agriculture) + -ure → 耕出來的東西 → 文化",
        "synonyms": ["way of life", "customs", "traditions", "values"],
        "zh": "文化",
    },
    {
        "word": "design", "pos": "v.",
        "example": "The building was designed to use half the usual energy.",
        "collocations": ["design a system", "specially designed", "designed to reduce"],
        "root": "de-(下) + sign(標記) → 把構想標記下來 → 設計",
        "synonyms": ["plan", "devise", "create", "draw up"],
        "zh": "設計",
    },
    {
        "word": "distinct", "pos": "adj.",
        "example": "The two species look alike but are genetically distinct.",
        "collocations": ["a distinct advantage", "distinct from", "three distinct groups"],
        "root": "di-(分開) + stinct(刺, 同 instinct/extinguish/distinguish) → 刺開來就分得出",
        "synonyms": ["separate", "clear", "different", "unmistakable"],
        "zh": "明顯不同的",
    },
    {
        "word": "element", "pos": "n.",
        "example": "Trust is the one element the plan cannot do without.",
        "collocations": ["a key element", "the elements of", "an essential element"],
        "root": "拉丁 elementum「最基本的組成」→ 構成整體的單位",
        "synonyms": ["component", "part", "ingredient", "factor"],
        "zh": "要素",
    },
    {
        "word": "equate", "pos": "v.",
        "example": "People often equate wealth with success.",
        "collocations": ["equate with", "wrongly equate", "equate A to B"],
        "root": "equ(相等, 同 equal/equator/equity) + -ate → 把兩件事當成相等",
        "synonyms": ["liken", "compare", "treat as the same", "identify with"],
        "zh": "把…等同",
    },
    {
        "word": "evaluate", "pos": "v.",
        "example": "The study evaluates three ways of cutting food waste.",
        "collocations": ["evaluate the results", "critically evaluate", "evaluate options"],
        "root": "e-(出來) + valu(價值, 同 value/valid/available) + -ate → 把價值算出來",
        "synonyms": ["assess", "judge", "appraise", "weigh up"],
        "zh": "評估",
    },
    {
        "word": "feature", "pos": "n.",
        "example": "The main feature of the design is a glass roof.",
        "collocations": ["a key feature", "a distinctive feature", "a safety feature"],
        "root": "拉丁 factura「製作出來的樣子」(fact 做, 同 factory) → 做出來的外顯特點",
        "synonyms": ["characteristic", "attribute", "trait", "aspect"],
        "zh": "特色",
    },
    {
        "word": "final", "pos": "adj.",
        "example": "The final section of the course is entirely practical.",
        "collocations": ["the final stage", "a final decision", "in the final analysis"],
        "root": "fin(結束, 同 finish/define/infinite) + -al → 走到界線的",
        "synonyms": ["last", "concluding", "closing", "ultimate"],
        "zh": "最後的",
    },
    {
        "word": "focus", "pos": "v.",
        "example": "The campaign focuses on cutting waste rather than recycling it.",
        "collocations": ["focus on", "focus attention", "sharply focused"],
        "root": "拉丁 focus「爐灶」→ 家裡大家圍著的中心點 → 聚焦處",
        "synonyms": ["concentrate", "centre", "zero in", "direct attention"],
        "zh": "聚焦",
    },
    {
        "word": "impact", "pos": "n.",
        "example": "The bypass had an immediate impact on traffic in the town.",
        "collocations": ["have an impact on", "a major impact", "environmental impact"],
        "root": "im-(進入) + pact(打緊, 同 compact/pack) → 撞進去的那股力道",
        "synonyms": ["effect", "influence", "consequence", "repercussion"],
        "zh": "衝擊、影響",
    },
    {
        "word": "injure", "pos": "v.",
        "example": "Two workers were injured when the scaffolding collapsed.",
        "collocations": ["seriously injured", "injure yourself", "injure a knee"],
        "root": "in-(不) + jur(法律、正當, 同 jury/justice/perjury) → 對人做不正當的事 → 傷害",
        "synonyms": ["hurt", "harm", "wound", "damage"],
        "zh": "使受傷",
    },
    {
        "word": "institute", "pos": "v.",
        "example": "The company instituted a four-day week last year.",
        "collocations": ["institute a policy", "institute reforms", "institute proceedings"],
        "root": "in-(進入) + stitut(建立, 同 constitute/substitute/statute) → 設立起來開始跑",
        "synonyms": ["establish", "introduce", "set up", "initiate"],
        "zh": "設立、開始實行",
    },
    {
        "word": "invest", "pos": "v.",
        "example": "The city has invested heavily in cycling infrastructure.",
        "collocations": ["invest in", "heavily invest", "invest time"],
        "root": "in-(進入) + vest(衣服, 同 vest/vestment)；原指「給某物穿上外衣」→ 把錢投到某事上",
        "synonyms": ["put money into", "fund", "back", "commit"],
        "zh": "投資",
    },
    {
        "word": "item", "pos": "n.",
        "example": "Every item on the questionnaire was answered by all participants.",
        "collocations": ["an item on the list", "each item", "a news item"],
        "root": "拉丁 item「同樣地」—— 舊清單每一行都以 item 開頭 → 一項",
        "synonyms": ["entry", "article", "thing", "element"],
        "zh": "項目",
    },
    {
        "word": "journal", "pos": "n.",
        "example": "The findings appeared in a leading medical journal.",
        "collocations": ["an academic journal", "publish in a journal", "a peer-reviewed journal"],
        "root": "jour(日, 法文, 同 journey 原意「一天的路程」) + -al → 按期出刊的東西",
        "synonyms": ["periodical", "publication", "magazine"],
        "zh": "期刊",
    },
    {
        "word": "maintain", "pos": "v.",
        "example": "The council can no longer afford to maintain all its parks.",
        "collocations": ["maintain standards", "well maintained", "maintain that"],
        "root": "main(手, 拉丁 manus, 同 manual/manage) + tain(持有, 同 contain/obtain) → 用手一直握著",
        "synonyms": ["keep up", "preserve", "sustain", "uphold"],
        "zh": "維持、保養",
        "notes": "另一個意思是「主張」：maintain that…",
    },
    {
        "word": "normal", "pos": "adj.",
        "example": "Rainfall was well above normal levels this spring.",
        "collocations": ["under normal conditions", "return to normal", "normal practice"],
        "root": "norm(木匠的角尺, 拉丁 norma) + -al → 合乎標準尺度的",
        "synonyms": ["usual", "standard", "typical", "ordinary"],
        "zh": "正常的",
    },
    {
        "word": "obtain", "pos": "v.",
        "example": "Students must obtain written permission before filming on campus.",
        "collocations": ["obtain permission", "obtain results", "hard to obtain"],
        "root": "ob-(朝向) + tain(持有, 同 contain/maintain/retain) → 把東西握到手上",
        "synonyms": ["get", "acquire", "secure", "procure"],
        "zh": "取得",
    },
    {
        "word": "participate", "pos": "v.",
        "example": "More than half the school participates in the recycling scheme.",
        "collocations": ["participate in", "actively participate", "participate fully"],
        "root": "part(部分) + cip(拿, 同 capture/recipient/principle) + -ate → 分到一份 → 參與",
        "synonyms": ["take part", "join in", "be involved", "contribute"],
        "zh": "參與",
    },
    {
        "word": "perceive", "pos": "v.",
        "example": "Cycling is still perceived as dangerous by many parents.",
        "collocations": ["be perceived as", "perceive a difference", "widely perceived"],
        "root": "per-(徹底) + ceiv(拿, 同 receive/conceive/deceive) → 整個接收進來 → 察覺",
        "synonyms": ["see", "regard", "view", "discern"],
        "zh": "感知、視為",
    },
    {
        "word": "positive", "pos": "adj.",
        "example": "Early results of the trial were surprisingly positive.",
        "collocations": ["a positive effect", "positive feedback", "remain positive"],
        "root": "posit(放置, 同 position/compose/deposit) + -ive → 已經擺定的 → 確定的、正向的",
        "synonyms": ["favourable", "constructive", "encouraging", "upbeat"],
        "zh": "正面的",
    },
    {
        "word": "potential", "pos": "n.",
        "example": "Wind power has enormous potential along this coast.",
        "collocations": ["enormous potential", "realise your potential", "the potential for"],
        "root": "potent(有力量, 同 power/potent/possible) + -ial → 還沒使出來的力量",
        "synonyms": ["capacity", "possibility", "promise", "capability"],
        "zh": "潛力",
    },
    {
        "word": "previous", "pos": "adj.",
        "example": "Sales were double those of the previous year.",
        "collocations": ["the previous year", "previous experience", "a previous study"],
        "root": "pre-(之前) + vi(路, 同 via/obvious/deviate) + -ous → 走在前面那一段的",
        "synonyms": ["earlier", "preceding", "prior", "former"],
        "zh": "先前的",
    },
    {
        "word": "primary", "pos": "adj.",
        "example": "The primary cause of the delay was poor weather.",
        "collocations": ["the primary cause", "primary school", "of primary importance"],
        "root": "prim(第一, 同 prime/primitive/prince) + -ary → 排在第一的",
        "synonyms": ["main", "chief", "principal", "foremost"],
        "zh": "主要的；初級的",
    },
    {
        "word": "purchase", "pos": "v.",
        "example": "Tickets purchased online cost ten per cent less.",
        "collocations": ["purchase tickets", "recently purchased", "purchase online"],
        "root": "pur-(向前, 同 pursue) + chase(追) → 一路追到手 → 買下",
        "synonyms": ["buy", "acquire", "obtain", "pay for"],
        "zh": "購買",
        "notes": "比 buy 正式，Task 1 講消費行為好用",
    },
    {
        "word": "range", "pos": "n.",
        "example": "The library offers a wide range of online courses.",
        "collocations": ["a wide range of", "range from", "the age range"],
        "root": "法文 rang「一排」(同 rank/arrange) → 排開來的幅度",
        "synonyms": ["variety", "spread", "span", "selection"],
        "zh": "範圍、幅度",
    },
    {
        "word": "region", "pos": "n.",
        "example": "The northern region receives twice as much rain as the south.",
        "collocations": ["a coastal region", "the region of", "regional differences"],
        "root": "reg(統治、劃線, 同 regular/regime/rule) + -ion → 劃出來管轄的地方",
        "synonyms": ["area", "district", "zone", "territory"],
        "zh": "地區",
    },
    {
        "word": "regulate", "pos": "v.",
        "example": "Few countries regulate the sale of personal data effectively.",
        "collocations": ["regulate the market", "strictly regulated", "regulate access"],
        "root": "reg(規則, 同 regular/rule/regime) + -ate → 按規矩管起來",
        "synonyms": ["control", "govern", "supervise", "police"],
        "zh": "管制、規範",
    },
    {
        "word": "relevant", "pos": "adj.",
        "example": "Only two of the studies are relevant to this question.",
        "collocations": ["relevant experience", "be relevant to", "highly relevant"],
        "root": "re-(再) + lev(舉起, 同 elevate/lever/relieve) + -ant → 扛得起這件事 → 有關係的",
        "synonyms": ["pertinent", "applicable", "related", "germane"],
        "zh": "相關的",
    },
    {
        "word": "reside", "pos": "v.",
        "example": "Nearly a third of students reside outside the city.",
        "collocations": ["reside in", "permanently reside", "reside abroad"],
        "root": "re-(回) + sid(坐, 同 sedentary/preside/president) → 坐回定處 → 定居",
        "synonyms": ["live", "dwell", "be based", "inhabit"],
        "zh": "居住",
    },
    {
        "word": "resource", "pos": "n.",
        "example": "The region's water resources are already under strain.",
        "collocations": ["natural resources", "limited resources", "allocate resources"],
        "root": "re-(再) + source(湧出, 拉丁 surgere, 同 surge) → 能再湧出來的東西",
        "synonyms": ["supply", "asset", "reserve", "means"],
        "zh": "資源",
    },
    {
        "word": "restrict", "pos": "v.",
        "example": "The city restricts lorry access during the day.",
        "collocations": ["restrict access", "severely restricted", "restrict the use of"],
        "root": "re-(往回) + strict(拉緊, 同 strict/constraint/strain) → 往回拉緊 → 限制",
        "synonyms": ["limit", "curb", "confine", "cap"],
        "zh": "限制",
    },
    {
        "word": "secure", "pos": "adj.",
        "example": "Few graduates now expect a secure job for life.",
        "collocations": ["a secure job", "feel secure", "secure storage"],
        "root": "se-(離開) + cur(擔心, 拉丁 cura, 同 cure/curious/accurate) → 不用擔心的",
        "synonyms": ["safe", "protected", "stable", "assured"],
        "zh": "安全的、穩固的",
    },
    {
        "word": "seek", "pos": "v.",
        "example": "Patients now seek information online before visiting a doctor.",
        "collocations": ["seek advice", "seek to improve", "widely sought"],
        "root": "古英語 secan「尋找」→ 主動去找",
        "synonyms": ["look for", "pursue", "try to obtain", "request"],
        "zh": "尋求",
        "notes": "不規則變化 seek → sought → sought",
    },
    {
        "word": "select", "pos": "v.",
        "example": "Judges selected twelve finalists from four hundred entries.",
        "collocations": ["select candidates", "carefully selected", "select from"],
        "root": "se-(分開) + lect(挑, 同 collect/elect/lecture) → 從一堆裡挑出來",
        "synonyms": ["choose", "pick", "opt for", "single out"],
        "zh": "挑選",
    },
    {
        "word": "site", "pos": "n.",
        "example": "The site of the old factory is now a public park.",
        "collocations": ["a building site", "on site", "the site of"],
        "root": "拉丁 situs「位置」(同 situate/situation) → 東西所在的位置",
        "synonyms": ["location", "place", "spot", "position"],
        "zh": "地點、場址",
    },
    {
        "word": "strategy", "pos": "n.",
        "example": "The company's strategy is to sell fewer products at higher prices.",
        "collocations": ["a long-term strategy", "adopt a strategy", "a marketing strategy"],
        "root": "strat(軍隊, 希臘 stratos) + ag(帶領, 同 agent/act) → 帶兵打仗的方法",
        "synonyms": ["plan", "approach", "policy", "tactics"],
        "zh": "策略",
    },
    {
        "word": "survey", "pos": "n.",
        "example": "A survey of two thousand commuters found the same complaint.",
        "collocations": ["conduct a survey", "a national survey", "survey results"],
        "root": "sur-(在上面) + vey(看, 同 view/vision/purvey) → 從上面整個看過一遍",
        "synonyms": ["poll", "study", "questionnaire", "review"],
        "zh": "調查",
    },
    {
        "word": "text", "pos": "n.",
        "example": "The full text of the report is available online.",
        "collocations": ["a written text", "the full text", "textual analysis"],
        "root": "text(編織, 同 textile/texture/context) → 把字織成的東西",
        "synonyms": ["writing", "wording", "document", "content"],
        "zh": "文本",
    },
    {
        "word": "tradition", "pos": "n.",
        "example": "The festival is a tradition that goes back four centuries.",
        "collocations": ["a long tradition", "break with tradition", "by tradition"],
        "root": "tra-(越過) + dit(給, 同 date/betray/edit) + -ion → 一代交給一代",
        "synonyms": ["custom", "convention", "practice", "heritage"],
        "zh": "傳統",
    },
    {
        "word": "transfer", "pos": "v.",
        "example": "Patients are transferred to the main hospital for surgery.",
        "collocations": ["transfer funds", "be transferred to", "transfer skills"],
        "root": "trans-(越過) + fer(帶, 同 refer/offer/ferry) → 帶到另一邊去",
        "synonyms": ["move", "shift", "hand over", "relocate"],
        "zh": "轉移",
    },
]

for _entry in SUBLIST_2:
    _entry["category"] = "AWL"
    _entry["topic"] = "Sublist 2"
