"""AWL Sublist 10 —— 四個維度全部寫齊。最後一組，出現頻率最低但仍是學術核心詞。"""

SUBLIST_10 = [
    {
        "word": "adjacent", "pos": "adj.",
        "example": "The car park is adjacent to the main entrance.",
        "collocations": ["adjacent to", "an adjacent building", "adjacent areas"],
        "root": "ad-(朝向) + jac(躺, 拉丁 jacere, 同 adjacent/eject) + -ent → 躺在旁邊的",
        "synonyms": ["neighbouring", "next to", "adjoining", "bordering"],
        "zh": "鄰接的",
    },
    {
        "word": "albeit", "pos": "conj.",
        "example": "Sales recovered, albeit more slowly than expected.",
        "collocations": ["albeit slowly", "albeit briefly", "albeit with reservations"],
        "root": "all + be + it → 「即使它全都是這樣」縮成一個連接詞",
        "synonyms": ["although", "even though", "though"],
        "zh": "雖然、儘管",
        "notes": "後面通常直接接形容詞或副詞片語，不接完整子句 —— 用對了很加分",
    },
    {
        "word": "assemble", "pos": "v.",
        "example": "Volunteers assembled outside the town hall before dawn.",
        "collocations": ["assemble a team", "assemble parts", "assemble outside"],
        "root": "as-(朝向) + simul(一起, 拉丁 simul, 同 simultaneous/similar) → 聚到一起",
        "synonyms": ["gather", "collect", "put together", "convene"],
        "zh": "集合、組裝",
    },
    {
        "word": "collapse", "pos": "v./n.",
        "example": "Fish stocks collapsed within a decade of the fleet's arrival.",
        "collocations": ["collapse completely", "the collapse of", "an economic collapse"],
        "root": "col-(一起) + laps(滑落, 拉丁 labi, 同 lapse/relapse) → 整個垮下來",
        "synonyms": ["fall apart", "break down", "crumble", "fail"],
        "zh": "崩潰、倒塌",
    },
    {
        "word": "colleague", "pos": "n.",
        "example": "She published the paper with two colleagues from Berlin.",
        "collocations": ["a close colleague", "former colleagues", "a colleague of mine"],
        "root": "col-(一起) + leg(選派, 拉丁 legare, 同 delegate/legal) → 一起被派來做事的人",
        "synonyms": ["co-worker", "associate", "workmate", "peer"],
        "zh": "同事",
    },
    {
        "word": "compile", "pos": "v.",
        "example": "The team compiled data from forty separate weather stations.",
        "collocations": ["compile a list", "compile data", "compile a report"],
        "root": "com-(一起) + pil(堆積, 拉丁 pilare, 同 pile/compilation) → 堆在一起整理",
        "synonyms": ["assemble", "gather", "collate", "put together"],
        "zh": "彙編、整理",
    },
    {
        "word": "conceive", "pos": "v.",
        "example": "The scheme was first conceived in the 1970s but never funded.",
        "collocations": ["conceive an idea", "conceive of", "originally conceived"],
        "root": "con-(完全) + ceive(拿取, 同 receive/perceive/deceive) → 在心裡孕育出來",
        "synonyms": ["imagine", "devise", "think up", "envisage"],
        "zh": "構思、想出",
    },
    {
        "word": "convince", "pos": "v.",
        "example": "The evidence failed to convince the planning committee.",
        "collocations": ["convince someone that", "hard to convince", "convince the public"],
        "root": "con-(徹底) + vinc(征服, 拉丁 vincere, 同 victory/evince) → 說到對方投降",
        "synonyms": ["persuade", "satisfy", "win over", "assure"],
        "zh": "說服",
    },
    {
        "word": "depress", "pos": "v.",
        "example": "The recession depressed house prices for almost five years.",
        "collocations": ["depress prices", "depress demand", "severely depress"],
        "root": "de-(向下) + press(壓) → 往下壓",
        "synonyms": ["lower", "reduce", "dampen", "weaken"],
        "zh": "壓低、使沮喪",
    },
    {
        "word": "encounter", "pos": "v./n.",
        "example": "Teachers encounter the same problem in almost every large class.",
        "collocations": ["encounter a problem", "encounter difficulties", "a chance encounter"],
        "root": "en-(進入) + counter(相對, 拉丁 contra, 同 contrary/counter) → 迎面碰上",
        "synonyms": ["meet", "come across", "face", "run into"],
        "zh": "遭遇、遇到",
    },
    {
        "word": "enormous", "pos": "adj.",
        "example": "Switching to renewables requires an enormous upfront investment.",
        "collocations": ["an enormous amount", "enormous pressure", "an enormous impact"],
        "root": "e-(超出) + norm(標準, 同 norm/normal) + -ous → 超出常規尺度的",
        "synonyms": ["huge", "immense", "vast", "massive"],
        "zh": "巨大的",
    },
    {
        "word": "forthcoming", "pos": "adj.",
        "example": "The findings will appear in a forthcoming issue of the journal.",
        "collocations": ["a forthcoming election", "not forthcoming", "the forthcoming year"],
        "root": "forth(向前) + coming(來) → 即將出現的",
        "synonyms": ["upcoming", "imminent", "approaching", "available"],
        "zh": "即將到來的",
        "notes": "另一個常見意思是「願意提供資訊的」：the funding was not forthcoming",
    },
    {
        "word": "incline", "pos": "v./n.",
        "example": "Younger voters incline towards parties with stronger climate policies.",
        "collocations": ["incline towards", "be inclined to", "a steep incline"],
        "root": "in-(朝向) + clin(傾斜, 拉丁 clinare, 同 decline/recline/climate) → 往某邊倒",
        "synonyms": ["lean", "tend", "be disposed", "slope"],
        "zh": "傾向、傾斜",
    },
    {
        "word": "integrity", "pos": "n.",
        "example": "The integrity of the data was questioned after the audit.",
        "collocations": ["academic integrity", "personal integrity", "the integrity of"],
        "root": "integr(完整, 同 integrate/entire/integral) + -ity → 完整不缺角 → 正直、完整性",
        "synonyms": ["honesty", "soundness", "wholeness", "uprightness"],
        "zh": "正直；完整性",
    },
    {
        "word": "intrinsic", "pos": "adj.",
        "example": "Curiosity is an intrinsic motivation that rewards cannot replace.",
        "collocations": ["intrinsic value", "intrinsic motivation", "intrinsic to"],
        "root": "intra-(在內部, 同 internal) + secus(跟隨) → 從內部來的",
        "synonyms": ["inherent", "innate", "built-in", "essential"],
        "zh": "內在的、本質的",
        "notes": "反義字 extrinsic（外在的）—— 教育題常考這組",
    },
    {
        "word": "invoke", "pos": "v.",
        "example": "The council invoked emergency powers to clear the site.",
        "collocations": ["invoke a law", "invoke powers", "invoke the principle of"],
        "root": "in-(朝向) + voc(呼叫, 同 voice/vocal/advocate) → 把某個依據叫出來用",
        "synonyms": ["cite", "call upon", "appeal to", "apply"],
        "zh": "援引、訴諸",
    },
    {
        "word": "levy", "pos": "v./n.",
        "example": "Several cities levy a small charge on every plastic bag.",
        "collocations": ["levy a tax", "levy a charge", "a carbon levy"],
        "root": "拉丁 levare「舉起」(同 elevate/lever/relieve) → 把錢徵收上來",
        "synonyms": ["impose", "charge", "collect", "tax"],
        "zh": "徵收、稅費",
    },
    {
        "word": "likewise", "pos": "adv.",
        "example": "Bus use fell sharply; likewise, cycling declined in the same period.",
        "collocations": ["likewise, ...", "do likewise", "and likewise"],
        "root": "like(相似) + wise(方式, 同 otherwise/clockwise) → 用同樣的方式",
        "synonyms": ["similarly", "in the same way", "equally", "also"],
        "zh": "同樣地",
        "notes": "Task 1 描述第二組數據走勢相同時很好用",
    },
    {
        "word": "nonetheless", "pos": "adv.",
        "example": "The sample was small; nonetheless, the pattern was striking.",
        "collocations": ["nonetheless, ...", "but nonetheless", "nonetheless remains"],
        "root": "none + the + less → 一點也不因此減少 → 儘管如此",
        "synonyms": ["nevertheless", "even so", "however", "still"],
        "zh": "儘管如此",
    },
    {
        "word": "notwithstanding", "pos": "prep./adv.",
        "example": "Notwithstanding the cost, the scheme went ahead as planned.",
        "collocations": ["notwithstanding the fact", "notwithstanding this", "notwithstanding the cost"],
        "root": "not + withstanding(抵擋, 同 withstand) → 擋不住 → 儘管",
        "synonyms": ["despite", "in spite of", "regardless of", "even so"],
        "zh": "儘管",
        "notes": "很正式，可以放句首也可以放在名詞後面",
    },
    {
        "word": "odd", "pos": "adj.",
        "example": "It seems odd that the busiest station has the fewest staff.",
        "collocations": ["an odd choice", "odd numbers", "the odd occasion"],
        "root": "古北歐語 oddi「三角形的尖端、單數」→ 落單的 → 奇怪的",
        "synonyms": ["strange", "peculiar", "unusual", "curious"],
        "zh": "奇怪的；奇數的",
    },
    {
        "word": "ongoing", "pos": "adj.",
        "example": "The investigation is ongoing and no conclusions have been published.",
        "collocations": ["an ongoing debate", "ongoing research", "ongoing support"],
        "root": "on(持續) + going(進行) → 還在進行中的",
        "synonyms": ["continuing", "current", "in progress", "unfinished"],
        "zh": "持續進行的",
    },
    {
        "word": "panel", "pos": "n.",
        "example": "An independent panel reviewed all forty applications.",
        "collocations": ["an expert panel", "a panel of judges", "a solar panel"],
        "root": "拉丁 pannus「布片」(同 pane/pannier) → 一小片；引申為一小組人",
        "synonyms": ["board", "committee", "jury", "board section"],
        "zh": "小組、面板",
    },
    {
        "word": "persist", "pos": "v.",
        "example": "The shortage of nurses persists despite higher salaries.",
        "collocations": ["persist in", "problems persist", "persist despite"],
        "root": "per-(徹底) + sist(站立, 同 assist/resist/consist) → 一直站著不倒",
        "synonyms": ["continue", "remain", "endure", "carry on"],
        "zh": "持續、堅持",
    },
    {
        "word": "reluctance", "pos": "n.",
        "example": "There is real reluctance among drivers to give up their cars.",
        "collocations": ["reluctance to", "with some reluctance", "widespread reluctance"],
        "root": "re-(往回) + luct(掙扎, 拉丁 luctari, 同 reluctant) + -ance → 心裡往回掙 → 不情願",
        "synonyms": ["unwillingness", "hesitation", "resistance", "disinclination"],
        "zh": "不情願",
    },
    {
        "word": "so-called", "pos": "adj.",
        "example": "The so-called smart motorway has done little to reduce delays.",
        "collocations": ["the so-called experts", "a so-called solution", "so-called reform"],
        "root": "so(如此) + called(被稱為) → 「別人是這樣叫它啦」→ 帶質疑的語氣",
        "synonyms": ["supposed", "alleged", "self-styled", "purported"],
        "zh": "所謂的",
        "notes": "帶懷疑語氣，Task 2 反駁對方立場時很有力",
    },
    {
        "word": "straightforward", "pos": "adj.",
        "example": "The application process is straightforward and takes ten minutes.",
        "collocations": ["a straightforward process", "fairly straightforward", "a straightforward answer"],
        "root": "straight(直) + forward(向前) → 一直往前、不繞彎",
        "synonyms": ["simple", "uncomplicated", "clear", "direct"],
        "zh": "簡單明瞭的、直接的",
    },
    {
        "word": "undergo", "pos": "v.",
        "example": "The city centre has undergone a complete transformation since 2010.",
        "collocations": ["undergo change", "undergo treatment", "undergo a transformation"],
        "root": "under(在下面) + go(走) → 從底下走過去 → 經歷",
        "synonyms": ["experience", "go through", "endure", "be subjected to"],
        "zh": "經歷、接受",
        "notes": "不規則變化：undergo / underwent / undergone",
    },
    {
        "word": "whereby", "pos": "adv.",
        "example": "The council introduced a scheme whereby residents park for free.",
        "collocations": ["a system whereby", "an arrangement whereby", "a scheme whereby"],
        "root": "where(哪裡) + by(藉由) → 藉由那個方式",
        "synonyms": ["by which", "through which", "by means of which"],
        "zh": "藉此、憑藉",
        "notes": "接在 system / scheme / arrangement 後面，是很自然的高分關係詞",
    },
]

for _entry in SUBLIST_10:
    _entry["category"] = "AWL"
    _entry["topic"] = "Sublist 10"
