"""AWL Sublist 7 —— 四個維度全部寫齊。"""

SUBLIST_7 = [
    {
        "word": "adapt", "pos": "v.",
        "example": "Coastal towns are having to adapt to more frequent flooding.",
        "collocations": ["adapt to", "adapt quickly", "adapt a text"],
        "root": "ad-(朝向) + apt(適合, 同 apt/aptitude) → 調整成適合的樣子",
        "synonyms": ["adjust", "modify", "acclimatise", "tailor"],
        "zh": "適應、改編",
    },
    {
        "word": "adult", "pos": "n./adj.",
        "example": "Adult literacy classes are held three evenings a week.",
        "collocations": ["adult education", "young adults", "adult literacy"],
        "root": "ad-(朝向) + ult(成長, 拉丁 alere 養育, 同 adolescent) → 已經長成的",
        "synonyms": ["grown-up", "mature", "of age"],
        "zh": "成人；成年的",
    },
    {
        "word": "aid", "pos": "n./v.",
        "example": "Foreign aid accounts for less than one per cent of the national budget.",
        "collocations": ["foreign aid", "financial aid", "aid workers"],
        "root": "拉丁 adiutare「幫助」(同 adjutant/aide) → 幫忙",
        "synonyms": ["help", "assistance", "support", "relief"],
        "zh": "援助",
    },
    {
        "word": "channel", "pos": "n./v.",
        "example": "The government channelled most of the funding into rural clinics.",
        "collocations": ["channel funds", "a distribution channel", "channel resources into"],
        "root": "拉丁 canalis「水道」(同 canal/channel) → 讓東西流過去的通道",
        "synonyms": ["direct", "route", "conduit", "medium"],
        "zh": "管道；引導",
    },
    {
        "word": "chemical", "pos": "adj./n.",
        "example": "Chemical fertilisers have raised yields but damaged the soil.",
        "collocations": ["chemical fertilisers", "chemical reaction", "toxic chemicals"],
        "root": "chem(煉金術, 阿拉伯 al-kimiya) + -ical → 關於物質變化的",
        "synonyms": ["synthetic", "artificial", "compound", "substance"],
        "zh": "化學的；化學物質",
    },
    {
        "word": "classic", "pos": "adj./n.",
        "example": "The city is a classic example of unplanned urban sprawl.",
        "collocations": ["a classic example", "a classic case", "a modern classic"],
        "root": "拉丁 classicus「第一等的」(同 class/classify) → 屬於最高等級的",
        "synonyms": ["typical", "definitive", "model", "textbook"],
        "zh": "典型的、經典的",
        "notes": "a classic example of 是舉例時的高分說法",
    },
    {
        "word": "comprehensive", "pos": "adj.",
        "example": "The council published a comprehensive plan covering housing, transport and parks.",
        "collocations": ["a comprehensive review", "a comprehensive plan", "comprehensive coverage"],
        "root": "com-(一起) + prehend(抓住, 同 comprehend/apprehend) + -ive → 全部抓進來的",
        "synonyms": ["thorough", "complete", "all-inclusive", "wide-ranging"],
        "zh": "全面的",
    },
    {
        "word": "comprise", "pos": "v.",
        "example": "Women comprise nearly two-thirds of the teaching workforce.",
        "collocations": ["comprise of", "largely comprise", "comprise the majority"],
        "root": "com-(一起) + pris(抓住, 同 prison/surprise/enterprise) → 抓在一起構成",
        "synonyms": ["make up", "consist of", "constitute", "form"],
        "zh": "構成、包含",
        "notes": "標準用法是 A comprises B（不加 of）—— be comprised of 常被視為錯誤",
    },
    {
        "word": "confirm", "pos": "v.",
        "example": "Later studies confirmed the link between diet and heart disease.",
        "collocations": ["confirm a finding", "confirm that", "later confirmed"],
        "root": "con-(徹底) + firm(堅固, 同 firm/affirm) → 使變得確定",
        "synonyms": ["verify", "corroborate", "support", "substantiate"],
        "zh": "證實、確認",
    },
    {
        "word": "contrary", "pos": "adj./n.",
        "example": "Contrary to expectations, cycling increased after the fare cut.",
        "collocations": ["contrary to", "on the contrary", "the contrary view"],
        "root": "contra-(相反, 同 contrast/contradict) + -ary → 方向相反的",
        "synonyms": ["opposite", "conflicting", "opposed", "reverse"],
        "zh": "相反的",
        "notes": "contrary to expectations 是很好用的開頭",
    },
    {
        "word": "convert", "pos": "v.",
        "example": "Several factories were converted into flats during the 1990s.",
        "collocations": ["convert into", "convert to", "convert a building"],
        "root": "con-(完全) + vert(轉, 同 reverse/version/divert) → 整個轉成另一種",
        "synonyms": ["change", "transform", "adapt", "turn"],
        "zh": "轉換、改建",
    },
    {
        "word": "couple", "pos": "n./v.",
        "example": "Rising rents, coupled with stagnant wages, forced families out of the city.",
        "collocations": ["coupled with", "a couple of", "a young couple"],
        "root": "拉丁 copula「連結」(同 copulate/couple) → 把兩個綁在一起",
        "synonyms": ["pair", "combine", "link", "join"],
        "zh": "一對；結合",
        "notes": "coupled with = 加上，Task 2 疊加原因很好用",
    },
    {
        "word": "decade", "pos": "n.",
        "example": "Car ownership has doubled over the past decade.",
        "collocations": ["over the past decade", "the previous decade", "for decades"],
        "root": "希臘 deka「十」(同 decimal/December) → 十年",
        "synonyms": ["ten years", "ten-year period"],
        "zh": "十年",
        "notes": "Task 1 描述長期趨勢常用 over the past decade",
    },
    {
        "word": "definite", "pos": "adj.",
        "example": "There is a definite link between overcrowding and poor exam results.",
        "collocations": ["a definite answer", "a definite improvement", "nothing definite"],
        "root": "de-(徹底) + fin(界線, 同 finish/define/final) + -ite → 界線劃清楚的",
        "synonyms": ["clear", "certain", "unmistakable", "firm"],
        "zh": "明確的",
    },
    {
        "word": "deny", "pos": "v.",
        "example": "The company denied that it had known about the contamination.",
        "collocations": ["deny that", "flatly deny", "deny access"],
        "root": "de-(否定) + ny(說, 拉丁 negare, 同 negative/renegade) → 說不是",
        "synonyms": ["reject", "refute", "dispute", "contradict"],
        "zh": "否認、拒絕給予",
    },
    {
        "word": "differentiate", "pos": "v.",
        "example": "The test cannot differentiate between the two strains of the virus.",
        "collocations": ["differentiate between", "differentiate from", "clearly differentiate"],
        "root": "differ(不同) + -ent + -iate → 指出不同之處",
        "synonyms": ["distinguish", "tell apart", "discriminate", "separate"],
        "zh": "區分、辨別",
    },
    {
        "word": "dispose", "pos": "v.",
        "example": "Households must dispose of batteries at designated collection points.",
        "collocations": ["dispose of", "safely dispose", "disposable income"],
        "root": "dis-(分開) + pos(放置, 同 position/compose/impose) → 分開放好 → 處理掉",
        "synonyms": ["get rid of", "discard", "throw away", "arrange"],
        "zh": "處置、丟棄",
        "notes": "固定接 of：dispose of waste；名詞 disposal",
    },
    {
        "word": "dynamic", "pos": "adj./n.",
        "example": "The dynamic between central and local government has shifted.",
        "collocations": ["a dynamic economy", "group dynamics", "highly dynamic"],
        "root": "希臘 dynamis「力量」(同 dynamite/dynasty) → 有力量在動的",
        "synonyms": ["energetic", "active", "changing", "vigorous"],
        "zh": "動態的、有活力的",
    },
    {
        "word": "eliminate", "pos": "v.",
        "example": "Better street lighting did not eliminate crime, but it did reduce it.",
        "collocations": ["eliminate the need for", "completely eliminate", "eliminate waste"],
        "root": "e-(向外) + limin(門檻, 拉丁 limen, 同 preliminary/subliminal) → 趕出門檻外",
        "synonyms": ["remove", "get rid of", "eradicate", "abolish"],
        "zh": "消除、根除",
    },
    {
        "word": "empirical", "pos": "adj.",
        "example": "There is little empirical evidence that the policy reduced accidents.",
        "collocations": ["empirical evidence", "empirical research", "empirical data"],
        "root": "希臘 empeiria「經驗」(同 experience/expert) + -ical → 靠實際觀察來的",
        "synonyms": ["observed", "experimental", "factual", "evidence-based"],
        "zh": "實證的",
        "notes": "empirical evidence 是學術寫作的高分搭配",
    },
    {
        "word": "equip", "pos": "v.",
        "example": "Schools were equipped with laptops but not with trained staff.",
        "collocations": ["be equipped with", "well equipped", "equip someone for"],
        "root": "古法語 esquiper「裝備船隻」→ 配齊需要的東西",
        "synonyms": ["supply", "provide", "furnish", "kit out"],
        "zh": "配備、裝備",
    },
    {
        "word": "extract", "pos": "v./n.",
        "example": "Companies extract groundwater faster than the aquifer can refill.",
        "collocations": ["extract information", "extract minerals", "an extract from"],
        "root": "ex-(向外) + tract(拉, 同 attract/contract/tractor) → 拉出來",
        "synonyms": ["remove", "draw out", "obtain", "excerpt"],
        "zh": "抽取、萃取；摘錄",
    },
    {
        "word": "file", "pos": "n./v.",
        "example": "Residents filed more than a thousand complaints about the noise.",
        "collocations": ["file a complaint", "on file", "a personnel file"],
        "root": "拉丁 filum「線」(同 filament/profile) → 用線串起來歸檔",
        "synonyms": ["submit", "record", "document", "lodge"],
        "zh": "檔案；提出",
    },
    {
        "word": "finite", "pos": "adj.",
        "example": "Fossil fuels are a finite resource, however efficiently we use them.",
        "collocations": ["a finite resource", "finite supply", "finite number"],
        "root": "fin(界線, 同 finish/define/final) + -ite → 有盡頭的",
        "synonyms": ["limited", "bounded", "restricted", "measurable"],
        "zh": "有限的",
        "notes": "反義字 infinite；環境題常用 finite resources",
    },
    {
        "word": "foundation", "pos": "n.",
        "example": "Early reading skills lay the foundation for all later learning.",
        "collocations": ["lay the foundation", "a solid foundation", "a charitable foundation"],
        "root": "found(奠基, 拉丁 fundus 底部, 同 fund/fundamental) + -ation → 打下的底",
        "synonyms": ["basis", "groundwork", "base", "institution"],
        "zh": "基礎、基金會",
    },
    {
        "word": "globe", "pos": "n.",
        "example": "Similar protests took place across the globe that summer.",
        "collocations": ["across the globe", "around the globe", "the whole globe"],
        "root": "拉丁 globus「球」(同 global/globule) → 地球這顆球",
        "synonyms": ["world", "planet", "earth", "sphere"],
        "zh": "地球、全球",
    },
    {
        "word": "grade", "pos": "n./v.",
        "example": "Students are graded on coursework as well as final examinations.",
        "collocations": ["a high grade", "grade papers", "make the grade"],
        "root": "拉丁 gradus「步伐、等級」(同 gradual/degree/progress) → 一階一階的等級",
        "synonyms": ["level", "rank", "mark", "class"],
        "zh": "等級、評分",
    },
    {
        "word": "guarantee", "pos": "n./v.",
        "example": "Higher spending does not guarantee better results.",
        "collocations": ["guarantee that", "no guarantee", "a money-back guarantee"],
        "root": "古法語 garant「保證人」(同 warrant/warranty) → 打包票",
        "synonyms": ["ensure", "promise", "assure", "warranty"],
        "zh": "保證",
    },
    {
        "word": "hierarchy", "pos": "n.",
        "example": "Flat organisations have fewer levels of hierarchy than traditional firms.",
        "collocations": ["a rigid hierarchy", "social hierarchy", "at the top of the hierarchy"],
        "root": "希臘 hieros(神聖) + arch(統治, 同 monarchy/architect) → 由上而下的位階",
        "synonyms": ["ranking", "pecking order", "structure", "chain of command"],
        "zh": "階層、位階",
    },
    {
        "word": "identical", "pos": "adj.",
        "example": "The two reports reached almost identical conclusions.",
        "collocations": ["virtually identical", "identical to", "identical twins"],
        "root": "ident(相同, 拉丁 idem, 同 identity/identify) + -ical → 完全一樣的",
        "synonyms": ["the same", "indistinguishable", "matching", "equal"],
        "zh": "完全相同的",
        "notes": "identical to 或 identical with，別用 identical as",
    },
    {
        "word": "ideology", "pos": "n.",
        "example": "The reforms were driven by ideology rather than evidence.",
        "collocations": ["political ideology", "a dominant ideology", "driven by ideology"],
        "root": "idea(觀念) + -logy(學問) → 一整套的觀念系統",
        "synonyms": ["belief system", "doctrine", "philosophy", "creed"],
        "zh": "意識形態",
    },
    {
        "word": "infer", "pos": "v.",
        "example": "From the graph we can infer that demand peaks in midsummer.",
        "collocations": ["infer from", "reasonably infer", "infer a conclusion"],
        "root": "in-(進入) + fer(帶, 同 transfer/refer/offer) → 把結論帶進來",
        "synonyms": ["deduce", "conclude", "gather", "work out"],
        "zh": "推論",
        "notes": "作者 imply（暗示），讀者 infer（推論）—— 閱讀題常考這組",
    },
    {
        "word": "innovate", "pos": "v.",
        "example": "Firms that fail to innovate rarely survive a decade.",
        "collocations": ["innovate rapidly", "continue to innovate", "innovate in"],
        "root": "in-(進入) + nov(新, 同 novel/renovate/novice) + -ate → 弄出新東西",
        "synonyms": ["invent", "pioneer", "modernise", "revolutionise"],
        "zh": "創新",
        "notes": "名詞 innovation 更常用：technological innovation",
    },
    {
        "word": "insert", "pos": "v./n.",
        "example": "A new clause was inserted into the agreement at the last minute.",
        "collocations": ["insert into", "insert a clause", "insert a coin"],
        "root": "in-(進入) + sert(接合, 拉丁 serere, 同 series/desert) → 塞進中間",
        "synonyms": ["put in", "add", "introduce", "embed"],
        "zh": "插入、加入",
    },
    {
        "word": "intervene", "pos": "v.",
        "example": "The central bank intervened to stop the currency falling further.",
        "collocations": ["intervene in", "intervene directly", "rarely intervene"],
        "root": "inter-(之間) + ven(來, 同 convene/event/venue) → 走進中間",
        "synonyms": ["step in", "interfere", "mediate", "get involved"],
        "zh": "干預、介入",
        "notes": "Task 2 講政府作為常用：governments should intervene",
    },
    {
        "word": "isolate", "pos": "v.",
        "example": "Poor transport links isolate many villages from basic services.",
        "collocations": ["socially isolated", "isolate a problem", "isolate from"],
        "root": "拉丁 insula「島」(同 insular/peninsula) → 變成孤島",
        "synonyms": ["separate", "cut off", "segregate", "detach"],
        "zh": "孤立、隔離",
    },
    {
        "word": "media", "pos": "n.",
        "example": "Social media has changed how young people follow the news.",
        "collocations": ["social media", "mass media", "media coverage"],
        "root": "medi(中間, 同 medium/mediate/middle) 的複數 → 傳遞訊息的中介",
        "synonyms": ["press", "outlets", "broadcasting", "communications"],
        "zh": "媒體",
        "notes": "單數是 medium；學術寫作 media 常配複數動詞",
    },
    {
        "word": "mode", "pos": "n.",
        "example": "Walking remains the main mode of transport for short trips.",
        "collocations": ["a mode of transport", "a mode of communication", "in this mode"],
        "root": "拉丁 modus「方式、尺度」(同 model/moderate/modify) → 做事的方式",
        "synonyms": ["method", "way", "form", "means"],
        "zh": "方式、模式",
    },
    {
        "word": "paradigm", "pos": "n.",
        "example": "The discovery forced a complete paradigm shift in the field.",
        "collocations": ["a paradigm shift", "the dominant paradigm", "a new paradigm"],
        "root": "para-(旁邊) + deigma(範例, 希臘 deiknynai 顯示, 同 index) → 擺在旁邊的典範",
        "synonyms": ["model", "framework", "pattern", "example"],
        "zh": "典範、模式",
        "notes": "paradigm shift（典範轉移）是學術寫作固定搭配",
    },
    {
        "word": "phenomenon", "pos": "n.",
        "example": "Urban heat islands are a well-documented phenomenon.",
        "collocations": ["a natural phenomenon", "a recent phenomenon", "a global phenomenon"],
        "root": "希臘 phainomenon「顯現的事物」(同 phase/emphasis) → 觀察得到的現象",
        "synonyms": ["occurrence", "event", "trend", "happening"],
        "zh": "現象",
        "notes": "複數是 phenomena —— 寫 a phenomena 是常見扣分點",
    },
    {
        "word": "priority", "pos": "n.",
        "example": "Cutting waiting times is the government's stated priority.",
        "collocations": ["a top priority", "give priority to", "set priorities"],
        "root": "prior(在前, 同 prime/primary) + -ity → 排在前面的事",
        "synonyms": ["precedence", "importance", "first concern", "preference"],
        "zh": "優先事項",
    },
    {
        "word": "prohibit", "pos": "v.",
        "example": "The city prohibits diesel vehicles from entering the old town.",
        "collocations": ["prohibit from", "strictly prohibited", "prohibit the sale of"],
        "root": "pro-(在前) + hib(握住, 同 exhibit/inhibit/habit) → 擋在前面不讓過",
        "synonyms": ["ban", "forbid", "outlaw", "bar"],
        "zh": "禁止",
        "notes": "prohibit sb from doing sth —— 接 from + V-ing",
    },
    {
        "word": "publication", "pos": "n.",
        "example": "Publication of the findings was delayed by six months.",
        "collocations": ["the publication of", "a scientific publication", "prior to publication"],
        "root": "publ(公眾, 同 public/publish) + -ation → 公開出來這件事",
        "synonyms": ["release", "issue", "printing", "journal"],
        "zh": "出版、發表",
    },
    {
        "word": "quote", "pos": "v./n.",
        "example": "The article quotes three experts who disagree with the policy.",
        "collocations": ["quote from", "widely quoted", "a direct quote"],
        "root": "拉丁 quotare「標上號碼」(同 quota/quotient) → 標出出處來引述",
        "synonyms": ["cite", "repeat", "reference", "excerpt"],
        "zh": "引述、報價",
    },
    {
        "word": "release", "pos": "v./n.",
        "example": "Factories release most of their pollutants at night.",
        "collocations": ["release information", "a press release", "release into"],
        "root": "re-(往回) + lease(放鬆, 拉丁 laxare, 同 relax/lax) → 鬆開放走",
        "synonyms": ["emit", "free", "issue", "let go"],
        "zh": "釋放、發布",
    },
    {
        "word": "reverse", "pos": "v./adj./n.",
        "example": "It will take decades to reverse the damage done to the wetland.",
        "collocations": ["reverse a decision", "reverse the trend", "in reverse"],
        "root": "re-(往回) + vers(轉, 同 version/convert/divert) → 轉回去",
        "synonyms": ["overturn", "undo", "invert", "opposite"],
        "zh": "逆轉、相反的",
    },
    {
        "word": "simulate", "pos": "v.",
        "example": "The model simulates how floodwater would move through the city.",
        "collocations": ["simulate conditions", "computer-simulated", "simulate an environment"],
        "root": "simil(相似, 同 similar/assimilate) + -ate → 做出很像的樣子",
        "synonyms": ["model", "imitate", "replicate", "mimic"],
        "zh": "模擬",
    },
    {
        "word": "sole", "pos": "adj.",
        "example": "Tourism is the sole source of income for many island families.",
        "collocations": ["the sole reason", "the sole survivor", "sole responsibility"],
        "root": "拉丁 solus「單獨」(同 solo/solitude/desolate) → 只有一個",
        "synonyms": ["only", "single", "exclusive", "lone"],
        "zh": "唯一的",
        "notes": "副詞 solely = 僅僅，寫作很好用",
    },
    {
        "word": "somewhat", "pos": "adv.",
        "example": "The results are somewhat weaker than the researchers had hoped.",
        "collocations": ["somewhat higher", "somewhat surprising", "somewhat different"],
        "root": "some(某種) + what(程度) → 有那麼一點",
        "synonyms": ["rather", "slightly", "fairly", "a little"],
        "zh": "有點、稍微",
        "notes": "Task 1 描述小幅差異時比 a bit 正式",
    },
    {
        "word": "submit", "pos": "v.",
        "example": "Applications must be submitted before the end of March.",
        "collocations": ["submit an application", "submit a report", "submit to"],
        "root": "sub-(在下面) + mit(送, 同 mission/transmit/commit) → 送到上級手裡",
        "synonyms": ["hand in", "present", "put forward", "yield"],
        "zh": "提交、屈服",
    },
    {
        "word": "successor", "pos": "n.",
        "example": "Her successor abandoned the project within a year.",
        "collocations": ["a likely successor", "name a successor", "his successor"],
        "root": "suc-(接著) + cess(走, 同 proceed/exceed/access) + -or → 接著走上來的人",
        "synonyms": ["replacement", "heir", "follower", "next in line"],
        "zh": "繼任者",
    },
    {
        "word": "survive", "pos": "v.",
        "example": "Few small bookshops survived the arrival of online retailers.",
        "collocations": ["survive on", "barely survive", "survive a crisis"],
        "root": "sur-(超過) + viv(活, 同 vivid/revive/survival) → 活過那個時間點",
        "synonyms": ["endure", "last", "outlive", "withstand"],
        "zh": "存活、倖存",
    },
    {
        "word": "thesis", "pos": "n.",
        "example": "Her thesis argues that congestion charging is regressive.",
        "collocations": ["a doctoral thesis", "the central thesis", "defend a thesis"],
        "root": "希臘 tithenai「放置」(同 hypothesis/synthesis) → 擺出來的主張",
        "synonyms": ["dissertation", "argument", "proposition", "claim"],
        "zh": "論文、論點",
        "notes": "複數是 theses",
    },
    {
        "word": "topic", "pos": "n.",
        "example": "Climate change is now a topic in almost every school subject.",
        "collocations": ["a controversial topic", "on the topic of", "a topic sentence"],
        "root": "希臘 topos「地方」(同 topography/utopia) → 談話落在哪個地方 → 主題",
        "synonyms": ["subject", "issue", "theme", "matter"],
        "zh": "主題、話題",
        "notes": "topic sentence（主題句）是每段第一句，Task 2 評分看這個",
    },
    {
        "word": "transmit", "pos": "v.",
        "example": "The disease is transmitted through contaminated water.",
        "collocations": ["transmit a signal", "transmit a disease", "transmit information"],
        "root": "trans-(橫越) + mit(送, 同 mission/submit/commit) → 送過去",
        "synonyms": ["send", "pass on", "convey", "spread"],
        "zh": "傳送、傳播",
    },
    {
        "word": "ultimate", "pos": "adj.",
        "example": "The ultimate aim is to make the city carbon neutral by 2040.",
        "collocations": ["the ultimate aim", "the ultimate goal", "ultimate responsibility"],
        "root": "ultim(最後, 拉丁 ultimus, 同 ultimatum) + -ate → 最後那一個",
        "synonyms": ["final", "eventual", "greatest", "supreme"],
        "zh": "最終的",
        "notes": "副詞 ultimately = 最終，很好用的結論連接詞",
    },
    {
        "word": "unique", "pos": "adj.",
        "example": "Each city faces a unique combination of pressures.",
        "collocations": ["a unique opportunity", "unique to", "absolutely unique"],
        "root": "un(一, 拉丁 unus, 同 unit/union/universe) + -ique → 只有一個",
        "synonyms": ["distinctive", "one-of-a-kind", "singular", "unparalleled"],
        "zh": "獨特的",
        "notes": "嚴格說 unique 沒有比較級，very unique 會被視為錯誤",
    },
    {
        "word": "visible", "pos": "adj.",
        "example": "The effects of the drought are visible from space.",
        "collocations": ["clearly visible", "highly visible", "barely visible"],
        "root": "vis(看, 同 vision/visit/supervise) + -ible → 看得到的",
        "synonyms": ["noticeable", "apparent", "observable", "evident"],
        "zh": "看得見的、明顯的",
    },
    {
        "word": "voluntary", "pos": "adj.",
        "example": "The scheme is voluntary, which explains the low participation rate.",
        "collocations": ["voluntary work", "on a voluntary basis", "the voluntary sector"],
        "root": "volunt(意願, 拉丁 voluntas, 同 volunteer/volition) + -ary → 出於自己意願的",
        "synonyms": ["optional", "willing", "unpaid", "elective"],
        "zh": "自願的、志願的",
    },
]

for _entry in SUBLIST_7:
    _entry["category"] = "AWL"
    _entry["topic"] = "Sublist 7"
